import type { CalcConfig } from './types'
import { calcularIMC, calcularTMB, calcularAguaDiaria } from '@/lib/calculos/saude'

const DIS_SAUDE = 'Apenas informativo. Consulte um médico para avaliação completa.'

export const CALCS_SAUDE: CalcConfig[] = [
  {
    slug: 'calculadora-imc',
    titulo: 'Calculadora de IMC',
    desc: 'Calcule seu Índice de Massa Corporal e saiba se seu peso está saudável.',
    cat: 'saude', icon: '⚖️',
    comp: 'CalculadoraIMC',
    campos: [],
    fn: () => ({ principal: { valor: 0, label: '', fmt: 'num' } }),
  },
  { slug: 'calculadora-peso-ideal', titulo: 'Calculadora de Peso Ideal', desc: 'Calcule seu peso ideal com base na altura.', cat: 'saude', icon: '⚖️', campos: [{ k: 'altura', l: 'Altura (cm)', p: '170', min: 100, max: 250 }], fn: (v) => { const altM = v.altura / 100; const min = Math.round(18.5 * altM * altM * 10) / 10; const max = Math.round(24.9 * altM * altM * 10) / 10; return { principal: { valor: Math.round((min + max) / 2 * 10) / 10, label: 'Peso Ideal Médio (kg)', fmt: 'num' }, detalhes: [{ l: 'Mínimo saudável', v: min, fmt: 'num' }, { l: 'Máximo saudável', v: max, fmt: 'num' }] } }, dis: DIS_SAUDE },
  {
    slug: 'calculadora-tmb',
    titulo: 'Calculadora de TMB',
    desc: 'Calcule sua Taxa Metabólica Basal e gasto calórico diário.',
    cat: 'saude', icon: '🔥',
    campos: [
      { k: 'peso', l: 'Peso (kg)', p: '70', min: 20, u: 'kg' },
      { k: 'altura', l: 'Altura (cm)', p: '170', min: 100 },
      { k: 'idade', l: 'Idade (anos)', p: '30', min: 10 },
      { k: 'sexo', l: 'Sexo', t: 'sel', op: [['1','Masculino'],['0','Feminino']] },
    ],
    fn: (v) => {
      const r = calcularTMB(v.peso, v.altura, v.idade, v.sexo === 1 ? 'M' : 'F')
      return {
        principal: { valor: r.tmb, label: 'TMB (kcal/dia)', fmt: 'num' },
        detalhes: [
          { l: 'Sedentário (×1.2)', v: r.sedentario, fmt: 'num' },
          { l: 'Levemente ativo (×1.375)', v: r.levementeAtivo, fmt: 'num' },
          { l: 'Moderado (×1.55)', v: r.moderadamenteAtivo, fmt: 'num' },
          { l: 'Muito ativo (×1.725)', v: r.muitoAtivo, fmt: 'num' },
        ],
      }
    },
    dis: DIS_SAUDE,
  },
  { slug: 'calculadora-tdee', titulo: 'TDEE — Gasto Calórico Total', desc: 'Calcule seu gasto energético total diário (TDEE).', cat: 'saude', icon: '🔥', campos: [{ k: 'tmb', l: 'TMB (kcal)', p: '1700', min: 500 }, { k: 'nivel', l: 'Nível de atividade', t: 'sel', op: [['1','Sedentário'],['2','Leve'],['3','Moderado'],['4','Intenso'],['5','Atleta']] }], fn: (v) => { const fat: Record<number, number> = { 1: 1.2, 2: 1.375, 3: 1.55, 4: 1.725, 5: 1.9 }; const tdee = Math.round(v.tmb * (fat[v.nivel] || 1.55)); return { principal: { valor: tdee, label: 'TDEE (kcal/dia)', fmt: 'num' }, detalhes: [{ l: 'Para emagrecer (-500kcal)', v: tdee - 500, fmt: 'num' }, { l: 'Para ganhar massa (+300kcal)', v: tdee + 300, fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-percentual-gordura', titulo: 'Percentual de Gordura Corporal', desc: 'Estime seu percentual de gordura pela fórmula Deurenberg.', cat: 'saude', icon: '📊', campos: [{ k: 'peso', l: 'Peso (kg)', p: '70', u: 'kg' }, { k: 'altura', l: 'Altura (cm)', p: '170' }, { k: 'idade', l: 'Idade', p: '30', min: 10 }, { k: 'sexo', l: 'Sexo', t: 'sel', op: [['1','Masculino'],['0','Feminino']] }], fn: (v) => { const altM = v.altura / 100; const imc = v.peso / (altM * altM); const gordura = 1.2 * imc + 0.23 * v.idade - 10.8 * v.sexo - 5.4; return { principal: { valor: Math.round(gordura * 10) / 10, label: 'Gordura Corporal Estimada (%)', fmt: 'pct' }, detalhes: [{ l: 'Saudável (H)', v: '10–20%', fmt: 'txt' }, { l: 'Saudável (M)', v: '20–30%', fmt: 'txt' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-frequencia-cardiaca-maxima', titulo: 'Frequência Cardíaca Máxima', desc: 'Calcule sua FCmáx e zonas de treino.', cat: 'saude', icon: '❤️', campos: [{ k: 'idade', l: 'Idade (anos)', p: '35', min: 10 }], fn: (v) => { const fcmax = 220 - v.idade; return { principal: { valor: fcmax, label: 'FC Máxima (bpm)', fmt: 'num' }, detalhes: [{ l: 'Zona 1 (50–60%)', v: `${Math.round(fcmax * 0.5)}–${Math.round(fcmax * 0.6)} bpm`, fmt: 'txt' }, { l: 'Zona 2 (60–70%)', v: `${Math.round(fcmax * 0.6)}–${Math.round(fcmax * 0.7)} bpm`, fmt: 'txt' }, { l: 'Zona 3 (70–80%)', v: `${Math.round(fcmax * 0.7)}–${Math.round(fcmax * 0.8)} bpm`, fmt: 'txt' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-zona-treino', titulo: 'Calculadora de Zona de Treino', desc: 'Calcule as zonas de frequência cardíaca para treino.', cat: 'saude', icon: '🏃', campos: [{ k: 'fcMax', l: 'FC Máxima (bpm)', p: '185', min: 100 }, { k: 'fcRepouso', l: 'FC em Repouso (bpm)', p: '60', min: 30 }], fn: (v) => { const reserva = v.fcMax - v.fcRepouso; const z1 = Math.round(v.fcRepouso + reserva * 0.5); const z3 = Math.round(v.fcRepouso + reserva * 0.7); return { principal: { valor: z1, label: 'Zona 1 — Aquecimento (bpm)', fmt: 'num' }, detalhes: [{ l: 'Zona 2 — Aeróbico leve', v: Math.round(v.fcRepouso + reserva * 0.6), fmt: 'num' }, { l: 'Zona 3 — Aeróbico', v: z3, fmt: 'num' }, { l: 'Zona 4 — Anaeróbico', v: Math.round(v.fcRepouso + reserva * 0.8), fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-macros-emagrecimento', titulo: 'Macros para Emagrecimento', desc: 'Calcule proteínas, carboidratos e gorduras para emagrecer.', cat: 'saude', icon: '🥗', campos: [{ k: 'peso', l: 'Peso (kg)', p: '70', u: 'kg' }, { k: 'calorias', l: 'Meta calórica/dia', p: '1800' }], fn: (v) => { const prot = v.peso * 2; const prot_kcal = prot * 4; const gord = v.peso * 0.8; const gord_kcal = gord * 9; const carb_kcal = v.calorias - prot_kcal - gord_kcal; const carb = carb_kcal / 4; return { principal: { valor: Math.round(prot), label: 'Proteína (g/dia)', fmt: 'num' }, detalhes: [{ l: 'Carboidratos (g/dia)', v: Math.round(Math.max(carb, 50)), fmt: 'num' }, { l: 'Gorduras (g/dia)', v: Math.round(gord), fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-macros-hipertrofia', titulo: 'Macros para Hipertrofia', desc: 'Calcule macros para ganho de massa muscular.', cat: 'saude', icon: '💪', campos: [{ k: 'peso', l: 'Peso (kg)', p: '70', u: 'kg' }, { k: 'calorias', l: 'Meta calórica/dia', p: '2800' }], fn: (v) => { const prot = v.peso * 2.5; const prot_kcal = prot * 4; const gord = v.peso * 1; const gord_kcal = gord * 9; const carb = (v.calorias - prot_kcal - gord_kcal) / 4; return { principal: { valor: Math.round(prot), label: 'Proteína (g/dia)', fmt: 'num' }, detalhes: [{ l: 'Carboidratos (g/dia)', v: Math.round(Math.max(carb, 100)), fmt: 'num' }, { l: 'Gorduras (g/dia)', v: Math.round(gord), fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-agua-diaria', titulo: 'Quantidade de Água Diária', desc: 'Saiba quantos litros de água você deve beber por dia.', cat: 'saude', icon: '💧', campos: [{ k: 'peso', l: 'Peso (kg)', p: '70', u: 'kg' }], fn: (v) => { const r = calcularAguaDiaria(v.peso); return { principal: { valor: r.litros, label: 'Litros de Água por Dia', fmt: 'num' }, detalhes: [{ l: 'Em mL', v: r.ml, fmt: 'num' }, { l: 'Copos de 200mL', v: r.copos, fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-deficit-calorico', titulo: 'Calculadora de Déficit Calórico', desc: 'Calcule o déficit para perder peso de forma saudável.', cat: 'saude', icon: '📉', campos: [{ k: 'tdee', l: 'TDEE (gasto diário kcal)', p: '2200' }, { k: 'deficit', l: 'Déficit desejado (kcal)', p: '500', min: 100, max: 1000 }], fn: (v) => { const meta = v.tdee - v.deficit; const kg500kcal = 0.5 / 3500 * v.deficit * 7; return { principal: { valor: meta, label: 'Meta Calórica Diária', fmt: 'num' }, detalhes: [{ l: 'Estimativa perda semanal (kg)', v: Math.round(kg500kcal * 100) / 100, fmt: 'num' }, { l: 'Meses para perder 5kg', v: Math.round((5 / (kg500kcal * 4)) * 10) / 10, fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-idade-biologica', titulo: 'Calculadora de Idade Biológica', desc: 'Estime sua idade biológica com base em hábitos de saúde.', cat: 'saude', icon: '🧬', campos: [{ k: 'idadeCronologica', l: 'Idade atual (anos)', p: '35', min: 15 }, { k: 'exercicio', l: 'Exercício semanal (dias)', p: '3', min: 0, max: 7 }, { k: 'sono', l: 'Horas de sono por noite', p: '7', min: 3, max: 12 }, { k: 'fumo', l: 'Fumante?', t: 'sel', op: [['0','Não'],['1','Sim']] }], fn: (v) => { let adj = 0; adj -= (v.exercicio - 3) * 0.5; adj += (7 - v.sono) * 0.3; adj += v.fumo * 5; const bioAge = Math.round(v.idadeCronologica + adj); return { principal: { valor: bioAge, label: 'Idade Biológica Estimada', fmt: 'num' }, detalhes: [{ l: 'Diferença', v: bioAge - v.idadeCronologica, fmt: 'num', cor: bioAge <= v.idadeCronologica ? '#16c784' : '#ef4444' }], aviso: bioAge < v.idadeCronologica ? 'Seus hábitos estão favorecendo um envelhecimento saudável!' : 'Melhorar hábitos pode reduzir sua idade biológica.' } }, dis: DIS_SAUDE },
  { slug: 'calculadora-pressao-arterial', titulo: 'Classificação da Pressão Arterial', desc: 'Classifique sua pressão arterial conforme valores medidos.', cat: 'saude', icon: '❤️', campos: [{ k: 'sistolica', l: 'Pressão Sistólica (mmHg)', p: '120', min: 60, max: 250 }, { k: 'diastolica', l: 'Pressão Diastólica (mmHg)', p: '80', min: 40, max: 150 }], fn: (v) => { let class_ = 'Ótima'; let cor = '#16c784'; if (v.sistolica >= 180 || v.diastolica >= 110) { class_ = 'Hipertensão Grau 3'; cor = '#9f1239'; } else if (v.sistolica >= 160 || v.diastolica >= 100) { class_ = 'Hipertensão Grau 2'; cor = '#dc2626'; } else if (v.sistolica >= 140 || v.diastolica >= 90) { class_ = 'Hipertensão Grau 1'; cor = '#ef4444'; } else if (v.sistolica >= 130 || v.diastolica >= 85) { class_ = 'Pré-hipertensão'; cor = '#f59e0b'; } else if (v.sistolica >= 120 || v.diastolica >= 80) { class_ = 'Normal'; cor = '#16c784'; } return { principal: { valor: class_, label: 'Classificação', fmt: 'txt' }, detalhes: [{ l: 'Sistólica', v: v.sistolica, fmt: 'num' }, { l: 'Diastólica', v: v.diastolica, fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-glicemia', titulo: 'Classificação da Glicemia', desc: 'Classifique os valores de glicemia em jejum.', cat: 'saude', icon: '🩸', campos: [{ k: 'glicemia', l: 'Glicemia em Jejum (mg/dL)', p: '100', min: 40, max: 500 }], fn: (v) => { let class_ = 'Normal'; let cor = '#16c784'; if (v.glicemia >= 200) { class_ = 'Diabetes (confirmação necessária)'; cor = '#dc2626'; } else if (v.glicemia >= 126) { class_ = 'Diabetes Mellitus'; cor = '#ef4444'; } else if (v.glicemia >= 100) { class_ = 'Pré-diabetes'; cor = '#f59e0b'; } return { principal: { valor: class_, label: 'Classificação', fmt: 'txt' }, detalhes: [{ l: 'Valor', v: v.glicemia, fmt: 'num' }, { l: 'Normal: < 100 mg/dL', v: 'Em jejum de 8h', fmt: 'txt' }], aviso: v.glicemia >= 100 ? 'Consulte seu médico para avaliação.' : undefined } }, dis: DIS_SAUDE },
  { slug: 'calculadora-circunferencia-abdominal', titulo: 'Circunferência Abdominal', desc: 'Classifique o risco cardiovascular pela circunferência abdominal.', cat: 'saude', icon: '📏', campos: [{ k: 'cintura', l: 'Circunferência da cintura (cm)', p: '85', min: 40, max: 200 }, { k: 'sexo', l: 'Sexo', t: 'sel', op: [['1','Masculino'],['0','Feminino']] }], fn: (v) => { const limite = v.sexo === 1 ? 94 : 80; const alto = v.sexo === 1 ? 102 : 88; const risco = v.cintura >= alto ? 'Alto' : v.cintura >= limite ? 'Moderado' : 'Baixo'; return { principal: { valor: v.cintura, label: 'Cintura (cm)', fmt: 'num' }, detalhes: [{ l: 'Risco Cardiovascular', v: risco, fmt: 'txt', cor: risco === 'Alto' ? '#ef4444' : risco === 'Moderado' ? '#f59e0b' : '#16c784' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-queima-gordura-atividade', titulo: 'Queima de Gordura por Atividade', desc: 'Calcule calorias e gordura queimada em atividades físicas.', cat: 'saude', icon: '🏃', campos: [{ k: 'peso', l: 'Peso (kg)', p: '70', u: 'kg' }, { k: 'minutos', l: 'Duração (minutos)', p: '30', min: 5 }, { k: 'atividade', l: 'Atividade', t: 'sel', op: [['7','Corrida (7 MET)'],['4','Caminhada (4 MET)'],['8','Ciclismo (8 MET)'],['5','Natação (5 MET)'],['6','Musculação (6 MET)']] }], fn: (v) => { const kcal = v.atividade * v.peso * (v.minutos / 60); const gordura = kcal / 9; return { principal: { valor: Math.round(kcal), label: 'Calorias Queimadas', fmt: 'num' }, detalhes: [{ l: 'Gordura queimada (g)', v: Math.round(gordura * 10) / 10, fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-queimas-para-perder-1kg', titulo: 'Calorias para Perder 1kg', desc: 'Quantas sessões de exercício para queimar 1kg de gordura.', cat: 'saude', icon: '🏋️', campos: [{ k: 'kcalPorSessao', l: 'Calorias por sessão', p: '400', min: 50 }], fn: (v) => { const sessoes = Math.ceil(7700 / v.kcalPorSessao); return { principal: { valor: sessoes, label: 'Sessões para perder 1kg', fmt: 'num' }, detalhes: [{ l: '1kg = 7.700 kcal', v: '7700 kcal', fmt: 'txt' }, { l: 'Calorias por sessão', v: v.kcalPorSessao, fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'simulador-deficit-calorico', titulo: 'Simulador Déficit Calórico Progressivo', desc: 'Simule quanto tempo para atingir seu peso alvo com déficit calórico.', cat: 'saude', icon: '📉', campos: [{ k: 'pesoAtual', l: 'Peso atual (kg)', p: '80', u: 'kg' }, { k: 'pesoAlvo', l: 'Peso alvo (kg)', p: '70', u: 'kg' }, { k: 'deficit', l: 'Déficit calórico diário', p: '500' }], fn: (v) => { const kgPerder = v.pesoAtual - v.pesoAlvo; const dias = (kgPerder * 7700) / v.deficit; const meses = dias / 30; return { principal: { valor: Math.round(meses * 10) / 10, label: 'Meses para atingir o peso alvo', fmt: 'num' }, detalhes: [{ l: 'Kg a perder', v: kgPerder, fmt: 'num' }, { l: 'Dias estimados', v: Math.round(dias), fmt: 'num' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-tdee-completo', titulo: 'TDEE Completo com Harris-Benedict', desc: 'Cálculo completo de gasto energético com dados físicos.', cat: 'saude', icon: '🔥', campos: [{ k: 'peso', l: 'Peso (kg)', p: '70', u: 'kg' }, { k: 'altura', l: 'Altura (cm)', p: '170' }, { k: 'idade', l: 'Idade', p: '30' }, { k: 'sexo', l: 'Sexo', t: 'sel', op: [['1','M'],['0','F']] }, { k: 'atividade', l: 'Atividade', t: 'sel', op: [['1','Sedentário'],['2','Leve'],['3','Moderado'],['4','Ativo'],['5','Muito ativo']] }], fn: (v) => { const r = calcularTMB(v.peso, v.altura, v.idade, v.sexo === 1 ? 'M' : 'F'); const fat: Record<number, number> = { 1: 1.2, 2: 1.375, 3: 1.55, 4: 1.725, 5: 1.9 }; const tdee = Math.round(r.tmb * (fat[v.atividade] || 1.55)); return { principal: { valor: tdee, label: 'TDEE Diário (kcal)', fmt: 'num' }, detalhes: [{ l: 'TMB', v: r.tmb, fmt: 'num' }, { l: 'Meta emagrecer', v: tdee - 500, fmt: 'num' }, { l: 'Meta hipertrofia', v: tdee + 300, fmt: 'num' }] } }, dis: DIS_SAUDE },
  // Saúde mental
  { slug: 'calculadora-custo-psicologo', titulo: 'Custo Mensal de Psicólogo', desc: 'Calcule o custo mensal de acompanhamento psicológico.', cat: 'saude', icon: '🧠', campos: [{ k: 'valorSessao', l: 'Valor por sessão', p: '150', u: 'R$' }, { k: 'sessoesMes', l: 'Sessões por mês', p: '4', min: 1 }], fn: (v) => { const total = v.valorSessao * v.sessoesMes; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Mensal', fmt: 'brl' }, detalhes: [{ l: 'Anual', v: Math.round(total * 12 * 100) / 100, fmt: 'brl' }, { l: 'CAPS: Gratuito pelo SUS', v: 'Procure o CAPS da sua cidade', fmt: 'txt' }] } } },
  { slug: 'calculadora-custo-psiquiatra', titulo: 'Custo Consulta Psiquiatra', desc: 'Calcule o custo de acompanhamento psiquiátrico.', cat: 'saude', icon: '🧠', campos: [{ k: 'valorConsulta', l: 'Valor da consulta', p: '300', u: 'R$' }, { k: 'consultasMes', l: 'Consultas por mês', p: '1', min: 1 }], fn: (v) => { const total = v.valorConsulta * v.consultasMes; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Mensal', fmt: 'brl' }, detalhes: [{ l: 'Anual', v: Math.round(total * 12 * 100) / 100, fmt: 'brl' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-plano-saude-mental', titulo: 'Plano de Saúde Mental — Custo', desc: 'Calcule o custo de um plano com cobertura de saúde mental.', cat: 'saude', icon: '💊', campos: [{ k: 'mensalidade', l: 'Mensalidade do plano', p: '400', u: 'R$' }, { k: 'cobertura', l: 'Sessões cobertas por mês', p: '4', min: 0 }, { k: 'valorSessao', l: 'Valor da sessão particular', p: '150', u: 'R$' }], fn: (v) => { const valorCoberto = v.cobertura * v.valorSessao; const custo = v.mensalidade - valorCoberto; return { principal: { valor: v.mensalidade, label: 'Mensalidade do Plano', fmt: 'brl' }, detalhes: [{ l: 'Cobertura mensal em sessões', v: Math.round(valorCoberto * 100) / 100, fmt: 'brl' }, { l: 'Custo efetivo mensal', v: Math.max(0, Math.round(custo * 100) / 100), fmt: 'brl' }] } } },
  { slug: 'calculadora-afastamento-burnout', titulo: 'Afastamento por Burnout — Valor', desc: 'Calcule o valor do auxílio-doença INSS em caso de burnout/afastamento.', cat: 'saude', icon: '😔', campos: [{ k: 'salario', l: 'Salário Bruto', p: '4000', u: 'R$' }], fn: (v) => { const auxilio = Math.max(1621, v.salario * 0.91); return { principal: { valor: Math.round(auxilio * 100) / 100, label: 'Auxílio-Doença INSS Estimado', fmt: 'brl' }, detalhes: [{ l: 'Aguardar carência de 15 dias pela empresa', v: 'Primeiros 15 dias pagos pela empresa', fmt: 'txt' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-terapia-online-vs-presencial', titulo: 'Terapia Online vs Presencial', desc: 'Compare custos de terapia online e presencial.', cat: 'saude', icon: '💻', campos: [{ k: 'precoOnline', l: 'Preço sessão online', p: '100', u: 'R$' }, { k: 'precoPresencial', l: 'Preço sessão presencial', p: '180', u: 'R$' }, { k: 'sessoesMes', l: 'Sessões por mês', p: '4', min: 1 }], fn: (v) => { const online = v.precoOnline * v.sessoesMes; const presencial = v.precoPresencial * v.sessoesMes; const economia = presencial - online; return { principal: { valor: Math.round(economia * 100) / 100, label: 'Economia com Online por Mês', fmt: 'brl' }, detalhes: [{ l: 'Custo online/mês', v: online, fmt: 'brl' }, { l: 'Custo presencial/mês', v: presencial, fmt: 'brl' }, { l: 'Economia anual', v: Math.round(economia * 12 * 100) / 100, fmt: 'brl' }] } } },
  // Exames / check-up
  { slug: 'calculadora-exames-periodicos', titulo: 'Custo Exames Periódicos', desc: 'Estime o custo anual de exames de rotina.', cat: 'saude', icon: '🔬', campos: [{ k: 'hemograma', l: 'Hemograma completo', p: '40', u: 'R$' }, { k: 'colesterol', l: 'Colesterol total + frações', p: '60', u: 'R$' }, { k: 'glicemia', l: 'Glicemia + HbA1c', p: '50', u: 'R$' }, { k: 'outros', l: 'Outros exames', p: '150', u: 'R$' }], fn: (v) => { const total = v.hemograma + v.colesterol + v.glicemia + v.outros; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Total Exames Anuais', fmt: 'brl' }, detalhes: [{ l: 'Por mês amortizado', v: Math.round(total / 12 * 100) / 100, fmt: 'brl' }] } } },
  { slug: 'calculadora-check-up-anual', titulo: 'Custo Check-up Anual Completo', desc: 'Calcule o custo de um check-up médico completo anual.', cat: 'saude', icon: '🏥', campos: [{ k: 'consultas', l: 'Consultas médicas (valor cada)', p: '200', u: 'R$' }, { k: 'qtdConsultas', l: 'Número de consultas', p: '3', min: 1 }, { k: 'exames', l: 'Pacote de exames', p: '400', u: 'R$' }], fn: (v) => { const total = v.consultas * v.qtdConsultas + v.exames; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Check-up Anual', fmt: 'brl' }, detalhes: [{ l: 'Consultas', v: v.consultas * v.qtdConsultas, fmt: 'brl' }, { l: 'Exames', v: v.exames, fmt: 'brl' }] } } },
  { slug: 'calculadora-risco-cardiovascular', titulo: 'Risco Cardiovascular', desc: 'Estime o risco cardiovascular com base em fatores de risco.', cat: 'saude', icon: '❤️', campos: [{ k: 'idade', l: 'Idade', p: '50', min: 20 }, { k: 'sistolica', l: 'Pressão sistólica (mmHg)', p: '130', min: 80 }, { k: 'fumo', l: 'Fumante?', t: 'sel', op: [['0','Não'],['1','Sim']] }, { k: 'diabetes', l: 'Diabetes?', t: 'sel', op: [['0','Não'],['1','Sim']] }], fn: (v) => { let score = 0; if (v.idade > 55) score += 2; if (v.sistolica > 140) score += 2; score += v.fumo * 3; score += v.diabetes * 2; const risco = score >= 5 ? 'Alto' : score >= 2 ? 'Moderado' : 'Baixo'; return { principal: { valor: risco, label: 'Risco Cardiovascular', fmt: 'txt' }, detalhes: [{ l: 'Score', v: score, fmt: 'num' }, { l: 'Consulte cardiologista', v: risco !== 'Baixo' ? 'Recomendado' : 'Preventivo a cada 2 anos', fmt: 'txt' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-colesterol-ldl-hdl', titulo: 'Relação LDL/HDL Colesterol', desc: 'Calcule a relação LDL/HDL e o risco cardiovascular.', cat: 'saude', icon: '🩸', campos: [{ k: 'ldl', l: 'LDL (mg/dL)', p: '130', min: 0 }, { k: 'hdl', l: 'HDL (mg/dL)', p: '50', min: 0 }], fn: (v) => { const relacao = v.hdl > 0 ? v.ldl / v.hdl : 0; const risco = relacao < 3 ? 'Baixo' : relacao < 4 ? 'Moderado' : 'Alto'; return { principal: { valor: Math.round(relacao * 100) / 100, label: 'Relação LDL/HDL', fmt: 'num' }, detalhes: [{ l: 'Risco', v: risco, fmt: 'txt', cor: risco === 'Alto' ? '#ef4444' : risco === 'Moderado' ? '#f59e0b' : '#16c784' }, { l: 'Ideal: < 3', v: 'LDL/HDL < 3', fmt: 'txt' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-risco-diabetes', titulo: 'Risco de Diabetes', desc: 'Estime o risco de desenvolver diabetes tipo 2.', cat: 'saude', icon: '🩸', campos: [{ k: 'imc', l: 'IMC', p: '27', min: 10, max: 60 }, { k: 'idade', l: 'Idade', p: '45', min: 10 }, { k: 'historico', l: 'Histórico familiar diabetes?', t: 'sel', op: [['0','Não'],['1','Sim']] }], fn: (v) => { let score = 0; if (v.imc >= 30) score += 3; else if (v.imc >= 25) score += 1; if (v.idade >= 45) score += 2; score += v.historico * 2; const risco = score >= 5 ? 'Alto' : score >= 2 ? 'Moderado' : 'Baixo'; return { principal: { valor: risco, label: 'Risco Diabetes Tipo 2', fmt: 'txt' }, detalhes: [{ l: 'Score', v: score, fmt: 'num' }], aviso: risco !== 'Baixo' ? 'Consulte um médico para exame de glicemia.' : undefined } }, dis: DIS_SAUDE },
  // Odontologia / estética
  { slug: 'calculadora-custo-ortodontico', titulo: 'Custo do Aparelho Ortodôntico', desc: 'Calcule o custo total do tratamento ortodôntico.', cat: 'saude', icon: '🦷', campos: [{ k: 'instalacao', l: 'Custo de instalação', p: '2000', u: 'R$' }, { k: 'manutencaoMes', l: 'Manutenção mensal', p: '200', u: 'R$' }, { k: 'meses', l: 'Duração estimada (meses)', p: '24', min: 6 }], fn: (v) => { const total = v.instalacao + v.manutencaoMes * v.meses; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Total do Tratamento', fmt: 'brl' }, detalhes: [{ l: 'Instalação', v: v.instalacao, fmt: 'brl' }, { l: 'Manutenção total', v: Math.round(v.manutencaoMes * v.meses * 100) / 100, fmt: 'brl' }] } } },
  { slug: 'calculadora-custo-implante', titulo: 'Custo de Implante Dentário', desc: 'Calcule o custo total de implante dentário.', cat: 'saude', icon: '🦷', campos: [{ k: 'custoPorImplante', l: 'Custo por implante', p: '3000', u: 'R$' }, { k: 'quantidade', l: 'Quantidade de implantes', p: '1', min: 1 }], fn: (v) => { const total = v.custoPorImplante * v.quantidade; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Total Implantes', fmt: 'brl' }, detalhes: [{ l: 'Parcelado em 12x', v: Math.round((total / 12) * 100) / 100, fmt: 'brl' }] } } },
  { slug: 'calculadora-plano-odontologico', titulo: 'Plano Odontológico — Custo-Benefício', desc: 'Veja se vale a pena ter plano odontológico.', cat: 'saude', icon: '🦷', campos: [{ k: 'mensalidade', l: 'Mensalidade do plano', p: '80', u: 'R$' }, { k: 'consultas', l: 'Consultas/procedimentos por ano', p: '4' }, { k: 'valorMedio', l: 'Valor médio por consulta/proc.', p: '200', u: 'R$' }], fn: (v) => { const gastoSemPlano = v.consultas * v.valorMedio; const gastosComPlano = v.mensalidade * 12; const economia = gastoSemPlano - gastosComPlano; return { principal: { valor: Math.round(economia * 100) / 100, label: economia > 0 ? 'Economia com o plano' : 'Custo extra com plano', fmt: 'brl' }, detalhes: [{ l: 'Sem plano (por ano)', v: gastoSemPlano, fmt: 'brl' }, { l: 'Com plano (por ano)', v: gastosComPlano, fmt: 'brl' }] } } },
  { slug: 'calculadora-custo-clareamento', titulo: 'Custo Clareamento Dental', desc: 'Compare custos de clareamento caseiro vs. consultório.', cat: 'saude', icon: '😁', campos: [{ k: 'tipo', l: 'Tipo', t: 'sel', op: [['1','Caseiro (~R$200)'],['2','Consultório (~R$1500)'],['3','Laser (~R$2500)']] }], fn: (v) => { const custos: Record<number, number> = { 1: 200, 2: 1500, 3: 2500 }; const custo = custos[v.tipo] || 200; return { principal: { valor: custo, label: 'Custo do Clareamento', fmt: 'brl' }, detalhes: [{ l: 'Duração estimada', v: v.tipo === 1 ? '6–12 meses' : '1–2 anos', fmt: 'txt' }] } } },
  { slug: 'calculadora-custo-cirurgia-plastica', titulo: 'Custo Cirurgia Plástica', desc: 'Estime o custo de procedimentos estéticos cirúrgicos.', cat: 'saude', icon: '💉', campos: [{ k: 'procedimento', l: 'Procedimento', t: 'sel', op: [['1','Rinoplastia (~R$15k)'],['2','Lipoaspiração (~R$12k)'],['3','Abdominoplastia (~R$15k)'],['4','Mastoplastia (~R$13k)']] }], fn: (v) => { const custos: Record<number, number> = { 1: 15000, 2: 12000, 3: 15000, 4: 13000 }; const custo = custos[v.procedimento] || 12000; return { principal: { valor: custo, label: 'Custo Estimado', fmt: 'brl' }, detalhes: [{ l: 'Parcelado em 12x', v: Math.round(custo / 12 * 100) / 100, fmt: 'brl' }, { l: 'Inclui cirurgião + anestesia + hospital', v: 'Cotação necessária', fmt: 'txt' }] } }, dis: 'Valores estimados de mercado. Consulte um cirurgião plástico credenciado pelo CFM.' },
  { slug: 'calculadora-custo-botox', titulo: 'Custo Botox (Toxina Botulínica)', desc: 'Calcule o custo anual de aplicações de botox.', cat: 'saude', icon: '💉', campos: [{ k: 'custoPorSessao', l: 'Custo por sessão', p: '1500', u: 'R$' }, { k: 'sessoesPorAno', l: 'Sessões por ano', p: '2', min: 1 }], fn: (v) => { const total = v.custoPorSessao * v.sessoesPorAno; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Anual Botox', fmt: 'brl' }, detalhes: [{ l: 'Por sessão', v: v.custoPorSessao, fmt: 'brl' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-custo-preenchimento', titulo: 'Custo Preenchimento Facial', desc: 'Calcule o custo de procedimentos de preenchimento.', cat: 'saude', icon: '💉', campos: [{ k: 'custo', l: 'Custo por aplicação', p: '2000', u: 'R$' }, { k: 'aplicacoesPorAno', l: 'Aplicações por ano', p: '2', min: 1 }], fn: (v) => { return { principal: { valor: Math.round(v.custo * v.aplicacoesPorAno * 100) / 100, label: 'Custo Anual', fmt: 'brl' }, detalhes: [{ l: 'Por aplicação', v: v.custo, fmt: 'brl' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-custo-depilacao-laser', titulo: 'Custo Depilação a Laser', desc: 'Calcule o custo total de depilação a laser.', cat: 'saude', icon: '✨', campos: [{ k: 'custoPorSessao', l: 'Custo por sessão', p: '300', u: 'R$' }, { k: 'sessoes', l: 'Sessões necessárias', p: '8', min: 1 }], fn: (v) => { const total = v.custoPorSessao * v.sessoes; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Total', fmt: 'brl' }, detalhes: [{ l: 'Manutenção anual (1 sessão)', v: v.custoPorSessao, fmt: 'brl' }] } } },
  { slug: 'calculadora-custo-transplante-capilar', titulo: 'Custo Transplante Capilar', desc: 'Estime o custo de transplante capilar FUE ou FUT.', cat: 'saude', icon: '💇', campos: [{ k: 'grafts', l: 'Grafts necessários', p: '2000', min: 500 }, { k: 'precoPorGraft', l: 'Preço por graft (R$)', p: '12', min: 5 }], fn: (v) => { const total = v.grafts * v.precoPorGraft; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Estimado Transplante', fmt: 'brl' }, detalhes: [{ l: 'Grafts', v: v.grafts, fmt: 'num' }, { l: 'Preço por graft', v: v.precoPorGraft, fmt: 'brl' }] } }, dis: DIS_SAUDE },
  { slug: 'calculadora-custo-parto', titulo: 'Custo do Parto Hospitalar', desc: 'Estime o custo total do parto em hospital particular ou SUS.', cat: 'saude', icon: '🏥', campos: [{ k: 'tipo', l: 'Tipo de parto', t: 'sel', op: [['1','Normal (particular ~R$8k)'],['2','Cesárea (particular ~R$12k)'],['3','SUS (gratuito)']] }], fn: (v) => { const custos: Record<number, number> = { 1: 8000, 2: 12000, 3: 0 }; const custo = custos[v.tipo] || 0; return { principal: { valor: custo, label: 'Custo Estimado do Parto', fmt: 'brl' }, detalhes: [{ l: 'SUS', v: 'Parto gratuito pelo SUS', fmt: 'txt' }, { l: 'Plano de saúde', v: 'Verifique cobertura maternidade', fmt: 'txt' }] } } },
  { slug: 'calculadora-custo-pre-natal', titulo: 'Custo Pré-Natal Completo', desc: 'Calcule o custo total das consultas e exames do pré-natal.', cat: 'saude', icon: '🤰', campos: [{ k: 'valorConsulta', l: 'Consulta com obstetra', p: '300', u: 'R$' }, { k: 'exames', l: 'Exames por trimestre', p: '300', u: 'R$' }], fn: (v) => { const consultas = v.valorConsulta * 14; /* ~14 consultas total */ const examesTotal = v.exames * 3; const total = consultas + examesTotal; return { principal: { valor: Math.round(total * 100) / 100, label: 'Custo Total Pré-Natal', fmt: 'brl' }, detalhes: [{ l: 'Consultas (14 total)', v: Math.round(consultas * 100) / 100, fmt: 'brl' }, { l: 'Exames (3 trimestres)', v: Math.round(examesTotal * 100) / 100, fmt: 'brl' }, { l: 'SUS: gratuito com pré-natal completo', v: 'Procure uma UBS', fmt: 'txt' }] } } },
]
