import type { CalcConfig } from './types'
import { BOLSA_FAMILIA_2026, BPC_2026, VALE_GAS_2026, SALARIO_MINIMO_2026 } from '@/lib/calculos/tabelas-vigentes'
import { calcularINSS } from '@/lib/calculos/trabalhista'
import { calcularFinanciamentoPrice } from '@/lib/calculos/investimentos'

const DIS_SOCIAL = 'Valores estimados conforme regras vigentes em 2026. Consulte o CRAS ou gov.br para confirmação.'

function calcBF(membros: number, renda: number, c06: number, c718: number, gest: number, nutr: number): number {
  const rpc = renda / membros
  const elegivel = rpc <= BOLSA_FAMILIA_2026.renda_maxima_per_capita
  if (!elegivel) return 0
  return BOLSA_FAMILIA_2026.base + c06 * BOLSA_FAMILIA_2026.adicional_primeira_infancia + (c718 + gest + nutr) * BOLSA_FAMILIA_2026.adicional_variavel
}

export const CALCS_PROGRAMAS_SOCIAIS: CalcConfig[] = [
  {
    slug: 'simulador-bolsa-familia',
    titulo: 'Simulador Bolsa Família 2026',
    desc: 'Simule se você tem direito ao Bolsa Família e calcule o valor.',
    cat: 'programas-sociais', icon: '👨‍👩‍👧',
    campos: [
      { k: 'membros', l: 'Pessoas na família', p: '4', min: 1 },
      { k: 'renda', l: 'Renda Familiar Total', p: '600', u: 'R$' },
      { k: 'c06', l: 'Crianças 0–6 anos', p: '1', min: 0 },
      { k: 'c718', l: 'Crianças/jovens 7–18 anos', p: '1', min: 0 },
      { k: 'gestante', l: 'Gestantes na família', p: '0', min: 0 },
      { k: 'nutriz', l: 'Nutrizes (amamentando)', p: '0', min: 0 },
    ],
    fn: (v) => {
      const rpc = v.renda / v.membros
      const valor = calcBF(v.membros, v.renda, v.c06, v.c718, v.gestante, v.nutriz)
      const elegivel = rpc <= BOLSA_FAMILIA_2026.renda_maxima_per_capita
      return {
        principal: { valor, label: elegivel ? 'Valor Estimado do Benefício' : 'Sem Direito (renda acima)', fmt: 'brl' },
        detalhes: [
          { l: 'Renda per capita', v: Math.round(rpc * 100) / 100, fmt: 'brl' },
          { l: 'Limite per capita', v: BOLSA_FAMILIA_2026.renda_maxima_per_capita, fmt: 'brl' },
          { l: 'Benefício base', v: BOLSA_FAMILIA_2026.base, fmt: 'brl' },
          { l: 'Adicionais', v: valor - BOLSA_FAMILIA_2026.base, fmt: 'brl' },
        ],
        aviso: elegivel ? undefined : `Renda per capita R$${rpc.toFixed(2)} supera o limite de R$${BOLSA_FAMILIA_2026.renda_maxima_per_capita}.`,
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'calculadora-bolsa-familia-filhos',
    titulo: 'Bolsa Família — Adicional por Filhos',
    desc: 'Calcule o adicional do Bolsa Família conforme número e idade dos filhos.',
    cat: 'programas-sociais', icon: '👶',
    campos: [
      { k: 'c06', l: 'Filhos de 0–6 anos', p: '2', min: 0 },
      { k: 'c718', l: 'Filhos de 7–18 anos', p: '1', min: 0 },
    ],
    fn: (v) => {
      const add06 = v.c06 * BOLSA_FAMILIA_2026.adicional_primeira_infancia
      const add718 = v.c718 * BOLSA_FAMILIA_2026.adicional_variavel
      const total = BOLSA_FAMILIA_2026.base + add06 + add718
      return {
        principal: { valor: total, label: 'Benefício Total Estimado', fmt: 'brl' },
        detalhes: [
          { l: 'Benefício base', v: BOLSA_FAMILIA_2026.base, fmt: 'brl' },
          { l: `Adicional 0–6 anos (${v.c06} × R$150)`, v: add06, fmt: 'brl', cor: '#16c784' },
          { l: `Adicional 7–18 anos (${v.c718} × R$50)`, v: add718, fmt: 'brl', cor: '#16c784' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'verificador-elegibilidade-bolsa-familia',
    titulo: 'Verificador Elegibilidade Bolsa Família',
    desc: 'Verifique se sua família está dentro do critério de renda do Bolsa Família.',
    cat: 'programas-sociais', icon: '✅',
    campos: [
      { k: 'membros', l: 'Membros da família', p: '3', min: 1 },
      { k: 'renda', l: 'Renda Familiar Mensal', p: '500', u: 'R$' },
    ],
    fn: (v) => {
      const rpc = v.renda / v.membros
      const elegivel = rpc <= BOLSA_FAMILIA_2026.renda_maxima_per_capita
      const regraProtecao = rpc <= BOLSA_FAMILIA_2026.regra_protecao_limite && rpc > BOLSA_FAMILIA_2026.renda_maxima_per_capita
      return {
        principal: { valor: Math.round(rpc * 100) / 100, label: 'Renda per Capita', fmt: 'brl' },
        detalhes: [
          { l: 'Status', v: elegivel ? 'ELEGÍVEL' : regraProtecao ? 'Regra de Proteção' : 'NÃO ELEGÍVEL', fmt: 'txt', cor: elegivel ? '#16c784' : regraProtecao ? '#f59e0b' : '#ef4444' },
          { l: 'Limite per capita', v: BOLSA_FAMILIA_2026.renda_maxima_per_capita, fmt: 'brl' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'calculadora-renda-maxima-bolsa-familia',
    titulo: 'Renda Máxima Bolsa Família por Família',
    desc: 'Calcule a renda máxima para sua família receber o Bolsa Família.',
    cat: 'programas-sociais', icon: '💰',
    campos: [
      { k: 'membros', l: 'Membros da família', p: '4', min: 1 },
    ],
    fn: (v) => {
      const rendaMax = v.membros * BOLSA_FAMILIA_2026.renda_maxima_per_capita
      return {
        principal: { valor: Math.round(rendaMax * 100) / 100, label: 'Renda Máxima para Elegibilidade', fmt: 'brl' },
        detalhes: [
          { l: 'Membros', v: v.membros, fmt: 'num' },
          { l: 'Limite por pessoa', v: BOLSA_FAMILIA_2026.renda_maxima_per_capita, fmt: 'brl' },
          { l: 'Benefício base (se elegível)', v: BOLSA_FAMILIA_2026.base, fmt: 'brl' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'regra-protecao-bolsa-familia',
    titulo: 'Regra de Proteção Bolsa Família',
    desc: 'Veja se sua família se enquadra na regra de proteção (emancipação gradual).',
    cat: 'programas-sociais', icon: '🛡️',
    campos: [
      { k: 'membros', l: 'Membros', p: '4', min: 1 },
      { k: 'renda', l: 'Nova Renda Familiar', p: '900', u: 'R$' },
    ],
    fn: (v) => {
      const rpc = v.renda / v.membros
      const regra = rpc > BOLSA_FAMILIA_2026.renda_maxima_per_capita && rpc <= BOLSA_FAMILIA_2026.regra_protecao_limite
      return {
        principal: { valor: Math.round(rpc * 100) / 100, label: 'Renda per Capita', fmt: 'brl' },
        detalhes: [
          { l: 'Enquadrado na Regra de Proteção', v: regra ? 'SIM — mantém 50% do benefício' : 'NÃO', fmt: 'txt', cor: regra ? '#f59e0b' : '#ef4444' },
          { l: 'Limite regra de proteção', v: BOLSA_FAMILIA_2026.regra_protecao_limite, fmt: 'brl' },
        ],
        aviso: regra ? 'Você mantém 50% do benefício durante a transição por até 24 meses.' : undefined,
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'calculadora-adicional-primeira-infancia',
    titulo: 'Adicional Primeira Infância — Bolsa Família',
    desc: 'Calcule o adicional de R$150 por criança de 0 a 6 anos no Bolsa Família.',
    cat: 'programas-sociais', icon: '🍼',
    campos: [
      { k: 'criancas', l: 'Crianças de 0 a 6 anos', p: '2', min: 0 },
    ],
    fn: (v) => {
      const adicional = v.criancas * BOLSA_FAMILIA_2026.adicional_primeira_infancia
      const total = BOLSA_FAMILIA_2026.base + adicional
      return {
        principal: { valor: adicional, label: 'Adicional Primeira Infância', fmt: 'brl' },
        detalhes: [
          { l: 'Por criança', v: BOLSA_FAMILIA_2026.adicional_primeira_infancia, fmt: 'brl' },
          { l: 'Benefício base', v: BOLSA_FAMILIA_2026.base, fmt: 'brl' },
          { l: 'Total estimado', v: total, fmt: 'brl' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'calculadora-bolsa-familia-gestante',
    titulo: 'Bolsa Família — Adicional para Gestante',
    desc: 'Calcule o adicional de R$50 para gestantes no Bolsa Família.',
    cat: 'programas-sociais', icon: '🤰',
    campos: [
      { k: 'gestantes', l: 'Gestantes na família', p: '1', min: 0 },
    ],
    fn: (v) => {
      const adicional = v.gestantes * BOLSA_FAMILIA_2026.adicional_variavel
      const total = BOLSA_FAMILIA_2026.base + adicional
      return {
        principal: { valor: adicional, label: 'Adicional para Gestante', fmt: 'brl' },
        detalhes: [
          { l: 'Por gestante', v: BOLSA_FAMILIA_2026.adicional_variavel, fmt: 'brl' },
          { l: 'Total estimado', v: total, fmt: 'brl' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'calculadora-bolsa-familia-familia-grande',
    titulo: 'Bolsa Família — Família Numerosa',
    desc: 'Calcule o Bolsa Família para famílias com muitos filhos.',
    cat: 'programas-sociais', icon: '👨‍👩‍👧‍👦',
    campos: [
      { k: 'membros', l: 'Total de membros', p: '6', min: 1 },
      { k: 'renda', l: 'Renda Familiar', p: '800', u: 'R$' },
      { k: 'c06', l: 'Filhos 0–6 anos', p: '2', min: 0 },
      { k: 'c718', l: 'Filhos 7–18 anos', p: '3', min: 0 },
    ],
    fn: (v) => {
      const valor = calcBF(v.membros, v.renda, v.c06, v.c718, 0, 0)
      const rpc = v.renda / v.membros
      return {
        principal: { valor, label: 'Benefício Estimado', fmt: 'brl' },
        detalhes: [
          { l: 'Renda per capita', v: Math.round(rpc * 100) / 100, fmt: 'brl' },
          { l: 'Adicional crianças 0–6', v: v.c06 * BOLSA_FAMILIA_2026.adicional_primeira_infancia, fmt: 'brl' },
          { l: 'Adicional crianças 7–18', v: v.c718 * BOLSA_FAMILIA_2026.adicional_variavel, fmt: 'brl' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'simulador-bloqueio-bolsa-familia',
    titulo: 'Simulador de Bloqueio do Bolsa Família',
    desc: 'Veja quando o Bolsa Família pode ser bloqueado por excesso de renda.',
    cat: 'programas-sociais', icon: '🔒',
    campos: [
      { k: 'membros', l: 'Membros', p: '4', min: 1 },
      { k: 'novaRenda', l: 'Nova Renda Familiar', p: '1200', u: 'R$' },
    ],
    fn: (v) => {
      const rpc = v.novaRenda / v.membros
      const bloqueado = rpc > BOLSA_FAMILIA_2026.regra_protecao_limite
      const regraProtecao = rpc > BOLSA_FAMILIA_2026.renda_maxima_per_capita && rpc <= BOLSA_FAMILIA_2026.regra_protecao_limite
      return {
        principal: { valor: Math.round(rpc * 100) / 100, label: 'Renda per Capita', fmt: 'brl' },
        detalhes: [
          { l: 'Status', v: bloqueado ? 'BLOQUEADO' : regraProtecao ? 'Meia parcela (proteção)' : 'Mantido', fmt: 'txt', cor: bloqueado ? '#ef4444' : regraProtecao ? '#f59e0b' : '#16c784' },
          { l: 'Limite bloqueio', v: BOLSA_FAMILIA_2026.regra_protecao_limite, fmt: 'brl' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'calculadora-bolsa-familia-anual',
    titulo: 'Bolsa Família — Total Anual',
    desc: 'Calcule o total recebido em 12 meses com o Bolsa Família.',
    cat: 'programas-sociais', icon: '📅',
    campos: [
      { k: 'membros', l: 'Membros', p: '4', min: 1 },
      { k: 'renda', l: 'Renda Familiar', p: '600', u: 'R$' },
      { k: 'c06', l: 'Crianças 0–6', p: '1', min: 0 },
      { k: 'c718', l: 'Crianças 7–18', p: '1', min: 0 },
    ],
    fn: (v) => {
      const mensal = calcBF(v.membros, v.renda, v.c06, v.c718, 0, 0)
      const anual = mensal * 13 /* 13 meses (inclui extra dezembro) */
      return {
        principal: { valor: Math.round(anual * 100) / 100, label: 'Total Anual (13 parcelas)', fmt: 'brl' },
        detalhes: [
          { l: 'Benefício Mensal', v: mensal, fmt: 'brl' },
          { l: 'Total 12 meses', v: mensal * 12, fmt: 'brl' },
          { l: '13ª parcela (dezembro)', v: mensal, fmt: 'brl' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'simulador-trabalhar-ou-bolsa',
    titulo: 'Simulador: Trabalhar ou Perder Bolsa Família?',
    desc: 'Veja se vale a pena aceitar um emprego ou risco perder o Bolsa Família.',
    cat: 'programas-sociais', icon: '⚖️',
    campos: [
      { k: 'beneficioAtual', l: 'Benefício Atual do Bolsa Família', p: '800', u: 'R$' },
      { k: 'salarioEmprego', l: 'Salário do Emprego', p: '1621', u: 'R$' },
      { k: 'membros', l: 'Membros da família', p: '4', min: 1 },
    ],
    fn: (v) => {
      const novaRenda = v.salarioEmprego
      const rpc = novaRenda / v.membros
      const manteBeneficio = rpc <= BOLSA_FAMILIA_2026.renda_maxima_per_capita
      const ganhoLiquido = v.salarioEmprego + (manteBeneficio ? v.beneficioAtual : 0) - v.beneficioAtual
      return {
        principal: { valor: Math.round(ganhoLiquido * 100) / 100, label: 'Ganho Real com Emprego', fmt: 'brl' },
        detalhes: [
          { l: 'Mantém Bolsa Família', v: manteBeneficio ? 'SIM' : 'NÃO', fmt: 'txt', cor: manteBeneficio ? '#16c784' : '#ef4444' },
          { l: 'Renda total com emprego', v: v.salarioEmprego + (manteBeneficio ? v.beneficioAtual : 0), fmt: 'brl' },
          { l: 'Renda atual (só benefício)', v: v.beneficioAtual, fmt: 'brl' },
        ],
        aviso: 'Mesmo perdendo o benefício, trabalhar gera direitos trabalhistas (FGTS, férias, 13º).',
      }
    },
    dis: DIS_SOCIAL,
  },
  {
    slug: 'calculadora-renda-per-capita',
    titulo: 'Calculadora de Renda Per Capita Familiar',
    desc: 'Calcule a renda per capita da sua família para programas sociais.',
    cat: 'programas-sociais', icon: '👥',
    campos: [
      { k: 'renda', l: 'Renda Familiar Total', p: '1200', u: 'R$' },
      { k: 'membros', l: 'Número de membros', p: '4', min: 1 },
    ],
    fn: (v) => {
      const rpc = v.renda / v.membros
      return {
        principal: { valor: Math.round(rpc * 100) / 100, label: 'Renda Per Capita', fmt: 'brl' },
        detalhes: [
          { l: 'Bolsa Família (limite R$218)', v: rpc <= 218 ? 'Elegível' : 'Acima do limite', fmt: 'txt', cor: rpc <= 218 ? '#16c784' : '#ef4444' },
          { l: 'BPC (limite R$405,25)', v: rpc <= 405.25 ? 'Elegível' : 'Acima do limite', fmt: 'txt', cor: rpc <= 405.25 ? '#16c784' : '#ef4444' },
          { l: 'Vale Gás (limite R$218)', v: rpc <= 218 ? 'Elegível' : 'Acima do limite', fmt: 'txt', cor: rpc <= 218 ? '#16c784' : '#ef4444' },
        ],
      }
    },
    dis: DIS_SOCIAL,
  },
  { slug: 'calculadora-bolsa-familia-vale-gas', titulo: 'Bolsa Família + Vale Gás', desc: 'Calcule o benefício total recebendo Bolsa Família e Vale Gás simultaneamente.', cat: 'programas-sociais', icon: '⛽', campos: [{ k: 'membros', l: 'Membros', p: '4', min: 1 }, { k: 'renda', l: 'Renda Familiar', p: '600', u: 'R$' }, { k: 'c06', l: 'Crianças 0–6', p: '1', min: 0 }], fn: (v) => { const bf = calcBF(v.membros, v.renda, v.c06, 0, 0, 0); const vg = VALE_GAS_2026.valor / 2; return { principal: { valor: Math.round((bf + vg) * 100) / 100, label: 'Total Mensal (BF + VG)', fmt: 'brl' }, detalhes: [{ l: 'Bolsa Família', v: bf, fmt: 'brl' }, { l: 'Vale Gás (bimestral ÷ 2)', v: vg, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-bolsa-familia-pe-de-meia', titulo: 'Bolsa Família + Pé-de-Meia', desc: 'Calcule o total com Bolsa Família e o Pé-de-Meia para estudante.', cat: 'programas-sociais', icon: '📚', campos: [{ k: 'membros', l: 'Membros', p: '4', min: 1 }, { k: 'renda', l: 'Renda Familiar', p: '700', u: 'R$' }, { k: 'estudantes', l: 'Estudantes do Ensino Médio', p: '1', min: 0 }], fn: (v) => { const bf = calcBF(v.membros, v.renda, 0, 0, 0, 0); const pm = v.estudantes * 200; return { principal: { valor: Math.round((bf + pm) * 100) / 100, label: 'Total Mensal', fmt: 'brl' }, detalhes: [{ l: 'Bolsa Família', v: bf, fmt: 'brl' }, { l: 'Pé-de-Meia (por estudante)', v: pm, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-atualizacao-cadunico', titulo: 'Simulador Atualização CadÚnico', desc: 'Veja o impacto de atualizar o CadÚnico na renda per capita.', cat: 'programas-sociais', icon: '📋', campos: [{ k: 'rendaAnterior', l: 'Renda Anterior Cadastrada', p: '400', u: 'R$' }, { k: 'rendaAtual', l: 'Renda Atual Real', p: '700', u: 'R$' }, { k: 'membros', l: 'Membros', p: '3', min: 1 }], fn: (v) => { const rpcAnterior = v.rendaAnterior / v.membros; const rpcAtual = v.rendaAtual / v.membros; return { principal: { valor: Math.round(rpcAtual * 100) / 100, label: 'Renda per capita atual', fmt: 'brl' }, detalhes: [{ l: 'RPC cadastrada', v: Math.round(rpcAnterior * 100) / 100, fmt: 'brl' }, { l: 'Diferença', v: Math.round((rpcAtual - rpcAnterior) * 100) / 100, fmt: 'brl' }, { l: 'Status BF com renda atual', v: rpcAtual <= 218 ? 'Mantém direito' : 'Perde direito', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-vale-gas', titulo: 'Calculadora Vale Gás 2026', desc: 'Verifique o valor do Vale Gás nacional e quantas parcelas recebe.', cat: 'programas-sociais', icon: '⛽', campos: [{ k: 'bimestres', l: 'Bimestres no ano', p: '6', min: 1, max: 6 }], fn: (v) => { const total = VALE_GAS_2026.valor * v.bimestres; return { principal: { valor: VALE_GAS_2026.valor, label: 'Vale Gás por Bimestre', fmt: 'brl' }, detalhes: [{ l: 'Total no ano', v: Math.round(total * 100) / 100, fmt: 'brl' }, { l: 'Frequência', v: 'A cada 2 meses', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'verificador-elegibilidade-gas', titulo: 'Verificador Elegibilidade Vale Gás', desc: 'Verifique se você tem direito ao Vale Gás.', cat: 'programas-sociais', icon: '✅', campos: [{ k: 'membros', l: 'Membros', p: '3', min: 1 }, { k: 'renda', l: 'Renda Familiar', p: '500', u: 'R$' }], fn: (v) => { const rpc = v.renda / v.membros; const elegivel = rpc <= BOLSA_FAMILIA_2026.renda_maxima_per_capita; return { principal: { valor: elegivel ? VALE_GAS_2026.valor : 0, label: elegivel ? 'Valor do Vale Gás' : 'Sem direito', fmt: 'brl' }, detalhes: [{ l: 'Renda per capita', v: Math.round(rpc * 100) / 100, fmt: 'brl' }, { l: 'Limite', v: BOLSA_FAMILIA_2026.renda_maxima_per_capita, fmt: 'brl' }, { l: 'Status', v: elegivel ? 'ELEGÍVEL' : 'NÃO ELEGÍVEL', fmt: 'txt', cor: elegivel ? '#16c784' : '#ef4444' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-frequencia-vale-gas', titulo: 'Vale Gás — Frequência de Pagamentos', desc: 'Veja quando você receberá os próximos pagamentos do Vale Gás.', cat: 'programas-sociais', icon: '📅', campos: [{ k: 'parcelas', l: 'Parcelas recebidas até agora', p: '2', min: 0, max: 6 }], fn: (v) => { const restantes = 6 - v.parcelas; const valorRestante = restantes * VALE_GAS_2026.valor; return { principal: { valor: valorRestante, label: 'Total Restante no Ano', fmt: 'brl' }, detalhes: [{ l: 'Parcelas restantes', v: restantes, fmt: 'num' }, { l: 'Por parcela', v: VALE_GAS_2026.valor, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-vale-gas-bolsa', titulo: 'Vale Gás vs Preço do Botijão', desc: 'Veja quantos botijões o Vale Gás cobre.', cat: 'programas-sociais', icon: '🔥', campos: [{ k: 'precoBotijao', l: 'Preço do Botijão', p: '120', u: 'R$' }], fn: (v) => { const botijoes = VALE_GAS_2026.valor / v.precoBotijao; const diferenca = VALE_GAS_2026.valor - v.precoBotijao; return { principal: { valor: Math.round(botijoes * 100) / 100, label: 'Botijões cobertos pelo Vale Gás', fmt: 'num' }, detalhes: [{ l: 'Vale Gás', v: VALE_GAS_2026.valor, fmt: 'brl' }, { l: 'Sobra/falta por botijão', v: Math.round(diferenca * 100) / 100, fmt: 'brl', cor: diferenca >= 0 ? '#16c784' : '#ef4444' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-economia-gas', titulo: 'Calculadora Economia com Vale Gás', desc: 'Calcule quanto você economiza por ano com o Vale Gás.', cat: 'programas-sociais', icon: '💰', campos: [{ k: 'precoBotijao', l: 'Preço do Botijão', p: '120', u: 'R$' }, { k: 'botojoesAno', l: 'Botijões usados por ano', p: '8', min: 1 }], fn: (v) => { const gastoSemBeneficio = v.precoBotijao * v.botojoesAno; const beneficioAnual = VALE_GAS_2026.valor * 6; const economia = Math.min(beneficioAnual, gastoSemBeneficio); return { principal: { valor: Math.round(economia * 100) / 100, label: 'Economia Anual com Vale Gás', fmt: 'brl' }, detalhes: [{ l: 'Gasto total sem benefício', v: gastoSemBeneficio, fmt: 'brl' }, { l: 'Vale Gás anual (6 bimestres)', v: beneficioAnual, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-botijoes-por-ano', titulo: 'Botijões por Ano — Família', desc: 'Calcule quantos botijões sua família usa por ano e o custo.', cat: 'programas-sociais', icon: '🔥', campos: [{ k: 'membros', l: 'Membros da família', p: '4', min: 1 }, { k: 'duracao', l: 'Duração do botijão (dias)', p: '45', min: 1 }, { k: 'preco', l: 'Preço do botijão', p: '120', u: 'R$' }], fn: (v) => { const botojoesAno = Math.round(365 / v.duracao); const custoAnual = botojoesAno * v.preco; return { principal: { valor: botojoesAno, label: 'Botijões por Ano', fmt: 'num' }, detalhes: [{ l: 'Custo anual', v: custoAnual, fmt: 'brl' }, { l: 'Custo mensal', v: Math.round((custoAnual / 12) * 100) / 100, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-renda-maxima-gas', titulo: 'Renda Máxima para Vale Gás', desc: 'Calcule a renda máxima para ter direito ao Vale Gás.', cat: 'programas-sociais', icon: '💰', campos: [{ k: 'membros', l: 'Membros', p: '3', min: 1 }], fn: (v) => { const max = v.membros * BOLSA_FAMILIA_2026.renda_maxima_per_capita; return { principal: { valor: max, label: 'Renda Máxima para Vale Gás', fmt: 'brl' }, detalhes: [{ l: 'Limite per capita', v: BOLSA_FAMILIA_2026.renda_maxima_per_capita, fmt: 'brl' }, { l: 'Membros', v: v.membros, fmt: 'num' }] } }, dis: DIS_SOCIAL },
  { slug: 'verificador-elegibilidade-bpc', titulo: 'Verificador Elegibilidade BPC', desc: 'Verifique se você ou familiar tem direito ao BPC/LOAS.', cat: 'programas-sociais', icon: '✅', campos: [{ k: 'membros', l: 'Membros da família', p: '3', min: 1 }, { k: 'renda', l: 'Renda Familiar Total', p: '800', u: 'R$' }], fn: (v) => { const rpc = v.renda / v.membros; const elegivel = rpc <= BPC_2026.renda_maxima_per_capita; return { principal: { valor: elegivel ? BPC_2026.valor : 0, label: elegivel ? 'Valor do BPC' : 'Sem direito', fmt: 'brl' }, detalhes: [{ l: 'Renda per capita', v: Math.round(rpc * 100) / 100, fmt: 'brl' }, { l: 'Limite BPC (25% SM)', v: BPC_2026.renda_maxima_per_capita, fmt: 'brl' }, { l: 'Status', v: elegivel ? 'ELEGÍVEL' : 'NÃO ELEGÍVEL', fmt: 'txt', cor: elegivel ? '#16c784' : '#ef4444' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-bpc-idoso', titulo: 'BPC para Idoso (65+)', desc: 'Calcule se o idoso tem direito ao BPC e qual o valor.', cat: 'programas-sociais', icon: '👴', campos: [{ k: 'membros', l: 'Membros da família', p: '2', min: 1 }, { k: 'renda', l: 'Renda Familiar', p: '600', u: 'R$' }, { k: 'idade', l: 'Idade do idoso', p: '70', min: 65 }], fn: (v) => { const rpc = v.renda / v.membros; const elegivel = rpc <= BPC_2026.renda_maxima_per_capita && v.idade >= 65; return { principal: { valor: elegivel ? BPC_2026.valor : 0, label: elegivel ? 'BPC Idoso' : 'Sem direito', fmt: 'brl' }, detalhes: [{ l: 'Renda per capita', v: Math.round(rpc * 100) / 100, fmt: 'brl' }, { l: 'Limite', v: BPC_2026.renda_maxima_per_capita, fmt: 'brl' }, { l: 'Idade mínima: 65 anos', v: 'OK', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-bpc-deficiencia', titulo: 'BPC para Pessoa com Deficiência', desc: 'Verifique o direito ao BPC para PcD de qualquer idade.', cat: 'programas-sociais', icon: '♿', campos: [{ k: 'membros', l: 'Membros', p: '3', min: 1 }, { k: 'renda', l: 'Renda Familiar', p: '700', u: 'R$' }], fn: (v) => { const rpc = v.renda / v.membros; const elegivel = rpc <= BPC_2026.renda_maxima_per_capita; return { principal: { valor: elegivel ? BPC_2026.valor : 0, label: elegivel ? 'BPC PcD' : 'Sem direito', fmt: 'brl' }, detalhes: [{ l: 'Renda per capita', v: Math.round(rpc * 100) / 100, fmt: 'brl' }, { l: 'Limite', v: BPC_2026.renda_maxima_per_capita, fmt: 'brl' }], aviso: 'É necessário laudo médico comprovando a deficiência e avaliação social pelo INSS.' } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-bpc-familia', titulo: 'BPC — Composição Familiar', desc: 'Calcule a renda per capita familiar para fins do BPC.', cat: 'programas-sociais', icon: '👨‍👩‍👧', campos: [{ k: 'renda1', l: 'Renda membro 1', p: '1621', u: 'R$' }, { k: 'renda2', l: 'Renda membro 2', p: '0', u: 'R$' }, { k: 'membros', l: 'Membros', p: '3', min: 1 }], fn: (v) => { const renda = v.renda1 + v.renda2; const rpc = renda / v.membros; const elegivel = rpc <= BPC_2026.renda_maxima_per_capita; return { principal: { valor: Math.round(rpc * 100) / 100, label: 'Renda per capita', fmt: 'brl' }, detalhes: [{ l: 'Renda total', v: renda, fmt: 'brl' }, { l: 'Elegível BPC', v: elegivel ? 'SIM' : 'NÃO', fmt: 'txt', cor: elegivel ? '#16c784' : '#ef4444' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-margem-consignavel-bpc', titulo: 'Margem Consignável BPC', desc: 'Calcule quanto do BPC pode ser usado em empréstimo consignado.', cat: 'programas-sociais', icon: '💳', campos: [{ k: 'percentual', l: 'Percentual consignável (%)', p: '35', u: '%' }], fn: (v) => { const margem = BPC_2026.valor * (v.percentual / 100); return { principal: { valor: Math.round(margem * 100) / 100, label: 'Margem Consignável', fmt: 'brl' }, detalhes: [{ l: 'BPC 2026', v: BPC_2026.valor, fmt: 'brl' }, { l: 'Percentual', v: v.percentual, fmt: 'pct' }, { l: 'Saldo disponível', v: Math.round((BPC_2026.valor - margem) * 100) / 100, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-bpc-vs-aposentadoria', titulo: 'BPC vs Aposentadoria', desc: 'Compare o BPC com a aposentadoria por idade.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'contribuicoes', l: 'Anos de contribuição INSS', p: '15', min: 0 }, { k: 'salario', l: 'Média salarial', p: '2000', u: 'R$' }], fn: (v) => { const apos = Math.max(SALARIO_MINIMO_2026, v.salario * 0.6 + v.contribuicoes * 0.02 * v.salario); return { principal: { valor: Math.max(BPC_2026.valor, Math.round(apos * 100) / 100), label: 'Melhor benefício estimado', fmt: 'brl' }, detalhes: [{ l: 'BPC (se elegível)', v: BPC_2026.valor, fmt: 'brl' }, { l: 'Aposentadoria estimada', v: Math.round(apos * 100) / 100, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-renda-per-capita-bpc', titulo: 'Renda per Capita — BPC', desc: 'Calcule a renda per capita para fins de elegibilidade ao BPC.', cat: 'programas-sociais', icon: '🧮', campos: [{ k: 'renda', l: 'Renda Familiar', p: '900', u: 'R$' }, { k: 'membros', l: 'Membros', p: '3', min: 1 }], fn: (v) => { const rpc = v.renda / v.membros; return { principal: { valor: Math.round(rpc * 100) / 100, label: 'Renda per Capita', fmt: 'brl' }, detalhes: [{ l: 'Limite BPC', v: BPC_2026.renda_maxima_per_capita, fmt: 'brl' }, { l: 'Elegível', v: rpc <= BPC_2026.renda_maxima_per_capita ? 'SIM' : 'NÃO', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-bpc-suspensao', titulo: 'BPC — Suspensão por Emprego', desc: 'Entenda quando o BPC é suspenso por trabalho formal.', cat: 'programas-sociais', icon: '⚠️', campos: [{ k: 'salarioEmprego', l: 'Salário do Emprego CLT', p: '1621', u: 'R$' }], fn: (v) => { return { principal: { valor: v.salarioEmprego, label: 'Salário do Emprego', fmt: 'brl' }, detalhes: [{ l: 'BPC será suspenso?', v: 'SIM — suspenso durante o emprego', fmt: 'txt', cor: '#f59e0b' }, { l: 'Pode reativar ao sair?', v: 'SIM — sem reavaliar deficiência', fmt: 'txt', cor: '#16c784' }], aviso: 'O BPC é suspenso durante o emprego mas pode ser reativado ao encerrar o vínculo.' } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-pe-de-meia-anual', titulo: 'Pé-de-Meia — Total Anual', desc: 'Calcule o total do Pé-de-Meia recebido no ano escolar.', cat: 'programas-sociais', icon: '💰', campos: [{ k: 'estudantes', l: 'Estudantes do EM no Bolsa Família', p: '1', min: 0 }, { k: 'meses', l: 'Meses letivos', p: '10', min: 1, max: 12 }], fn: (v) => { const mensal = 200; const bonus = 1000; const total = v.estudantes * (mensal * v.meses + bonus); return { principal: { valor: total, label: 'Total Pé-de-Meia no Ano', fmt: 'brl' }, detalhes: [{ l: 'Por estudante/mês', v: mensal, fmt: 'brl' }, { l: 'Bônus por estudante (conclusão)', v: bonus, fmt: 'brl' }, { l: 'Estudantes', v: v.estudantes, fmt: 'num' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-pe-de-meia-3-anos', titulo: 'Pé-de-Meia — Simulação 3 Anos', desc: 'Simule o total acumulado no Pé-de-Meia ao longo do Ensino Médio.', cat: 'programas-sociais', icon: '📈', campos: [{ k: 'estudantes', l: 'Estudantes', p: '1', min: 1 }], fn: (v) => { const total = v.estudantes * (200 * 30 + 1000 * 3); return { principal: { valor: total, label: 'Total 3 anos por estudante', fmt: 'brl' }, detalhes: [{ l: 'Mensalidade (30 meses)', v: 200 * 30, fmt: 'brl' }, { l: 'Bônus (3 anos)', v: 1000 * 3, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-poupanca-pe-de-meia', titulo: 'Poupança Pé-de-Meia com Rendimento', desc: 'Veja o montante do Pé-de-Meia com rendimento da poupança.', cat: 'programas-sociais', icon: '🐷', campos: [{ k: 'meses', l: 'Meses acumulados', p: '24', min: 1 }], fn: (v) => { const deposito = 200; const taxa = 0.005; let total = 0; for (let i = 0; i < v.meses; i++) { total = (total + deposito) * (1 + taxa); } return { principal: { valor: Math.round(total * 100) / 100, label: 'Poupança Acumulada', fmt: 'brl' }, detalhes: [{ l: 'Depósitos', v: deposito * v.meses, fmt: 'brl' }, { l: 'Rendimento poupança', v: Math.round((total - deposito * v.meses) * 100) / 100, fmt: 'brl', cor: '#16c784' }] } }, dis: DIS_SOCIAL },
  { slug: 'verificador-pe-de-meia', titulo: 'Verificador Pé-de-Meia', desc: 'Veja se o estudante tem direito ao Pé-de-Meia.', cat: 'programas-sociais', icon: '✅', campos: [{ k: 'bolsaFamilia', l: 'Recebe Bolsa Família?', t: 'sel', op: [['1','Sim'],['0','Não']] }, { k: 'serieEM', l: 'Série do Ensino Médio', t: 'sel', op: [['1','1º ano'],['2','2º ano'],['3','3º ano']] }], fn: (v) => { const elegivel = v.bolsaFamilia === 1; return { principal: { valor: elegivel ? 200 : 0, label: elegivel ? 'Valor Mensal Pé-de-Meia' : 'Sem direito', fmt: 'brl' }, detalhes: [{ l: 'Requisito: Bolsa Família', v: elegivel ? 'OK' : 'Necessário', fmt: 'txt', cor: elegivel ? '#16c784' : '#ef4444' }, { l: 'Requisito: EM público', v: 'OK', fmt: 'txt', cor: '#16c784' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-pe-de-meia-2-filhos', titulo: 'Pé-de-Meia — 2 Filhos no EM', desc: 'Calcule o benefício com dois estudantes no Ensino Médio.', cat: 'programas-sociais', icon: '👨‍👩‍👧‍👦', campos: [{ k: 'meses', l: 'Meses no ano', p: '10', min: 1 }], fn: (v) => { const total = 2 * 200 * v.meses; return { principal: { valor: total, label: 'Pé-de-Meia — 2 filhos', fmt: 'brl' }, detalhes: [{ l: 'Por filho/mês', v: 200, fmt: 'brl' }, { l: 'Total por filho', v: 200 * v.meses, fmt: 'brl' }, { l: 'Bônus conclusão (2 filhos)', v: 2000, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-desconto-tarifa-social', titulo: 'Desconto Tarifa Social de Energia', desc: 'Calcule o desconto na conta de luz pela Tarifa Social.', cat: 'programas-sociais', icon: '⚡', campos: [{ k: 'kwh', l: 'Consumo mensal (kWh)', p: '150', min: 1 }, { k: 'tarifa', l: 'Tarifa (R$/kWh)', p: '0.75', u: 'R$' }], fn: (v) => { let desconto = 0; if (v.kwh <= 30) desconto = 0.65; else if (v.kwh <= 100) desconto = 0.40; else if (v.kwh <= 220) desconto = 0.10; const valorOriginal = v.kwh * v.tarifa; const valorComDesconto = valorOriginal * (1 - desconto); return { principal: { valor: Math.round((valorOriginal - valorComDesconto) * 100) / 100, label: 'Desconto na Conta', fmt: 'brl' }, detalhes: [{ l: 'Conta sem tarifa social', v: Math.round(valorOriginal * 100) / 100, fmt: 'brl' }, { l: 'Conta com desconto', v: Math.round(valorComDesconto * 100) / 100, fmt: 'brl' }, { l: 'Percentual de desconto', v: desconto * 100, fmt: 'pct', cor: '#16c784' }] } }, dis: DIS_SOCIAL },
  { slug: 'verificador-tarifa-social', titulo: 'Verificador Tarifa Social Energia', desc: 'Veja se você tem direito à Tarifa Social de Energia Elétrica.', cat: 'programas-sociais', icon: '✅', campos: [{ k: 'recebeBF', l: 'Recebe Bolsa Família?', t: 'sel', op: [['1','Sim'],['0','Não']] }, { k: 'recebeRPC', l: 'Renda ≤ R$218/pessoa?', t: 'sel', op: [['1','Sim'],['0','Não']] }], fn: (v) => { const elegivel = v.recebeBF === 1 || v.recebeRPC === 1; return { principal: { valor: elegivel ? 1 : 0, label: elegivel ? 'ELEGÍVEL à Tarifa Social' : 'Sem direito', fmt: 'txt' }, detalhes: [{ l: 'Status', v: elegivel ? 'Procure sua distribuidora de energia' : 'Não elegível', fmt: 'txt', cor: elegivel ? '#16c784' : '#ef4444' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-economia-tarifa-social', titulo: 'Economia Anual com Tarifa Social', desc: 'Calcule o total economizado no ano com a Tarifa Social.', cat: 'programas-sociais', icon: '💰', campos: [{ k: 'descontoMes', l: 'Desconto mensal estimado', p: '60', u: 'R$' }], fn: (v) => { return { principal: { valor: Math.round(v.descontoMes * 12 * 100) / 100, label: 'Economia Anual', fmt: 'brl' }, detalhes: [{ l: 'Desconto mensal', v: v.descontoMes, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-conta-luz-tarifa-social', titulo: 'Simulador Conta de Luz com Tarifa Social', desc: 'Simule como ficaria sua conta de luz com a Tarifa Social.', cat: 'programas-sociais', icon: '💡', campos: [{ k: 'kwh', l: 'Consumo (kWh)', p: '100', min: 1 }, { k: 'tarifa', l: 'Tarifa R$/kWh', p: '0.80', u: 'R$' }], fn: (v) => { const desconto = v.kwh <= 30 ? 0.65 : v.kwh <= 100 ? 0.40 : 0.10; const sem = v.kwh * v.tarifa; const com = sem * (1 - desconto); return { principal: { valor: Math.round(com * 100) / 100, label: 'Conta com Tarifa Social', fmt: 'brl' }, detalhes: [{ l: 'Conta normal', v: Math.round(sem * 100) / 100, fmt: 'brl' }, { l: 'Desconto', v: desconto * 100, fmt: 'pct' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-desconto-faixas-tarifa', titulo: 'Faixas de Desconto da Tarifa Social', desc: 'Veja as faixas de desconto da Tarifa Social conforme consumo.', cat: 'programas-sociais', icon: '📊', campos: [{ k: 'kwh', l: 'Consumo mensal (kWh)', p: '120', min: 1 }, { k: 'tarifa', l: 'Tarifa (R$/kWh)', p: '0.75', u: 'R$' }], fn: (v) => { const desconto = v.kwh <= 30 ? 0.65 : v.kwh <= 100 ? 0.40 : v.kwh <= 220 ? 0.10 : 0; const economia = v.kwh * v.tarifa * desconto; return { principal: { valor: Math.round(economia * 100) / 100, label: 'Desconto Calculado', fmt: 'brl' }, detalhes: [{ l: 'Faixa: até 30kWh', v: '65% desconto', fmt: 'txt' }, { l: 'Faixa: 31–100kWh', v: '40% desconto', fmt: 'txt' }, { l: 'Faixa: 101–220kWh', v: '10% desconto', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-mcmv-faixa', titulo: 'Minha Casa Minha Vida — Faixa', desc: 'Descubra em qual faixa do MCMV você se enquadra.', cat: 'programas-sociais', icon: '🏠', campos: [{ k: 'renda', l: 'Renda Familiar Bruta', p: '4000', u: 'R$' }], fn: (v) => { const faixa = v.renda <= 2850 ? 1 : v.renda <= 4700 ? 2 : v.renda <= 8000 ? 3 : 0; const nomes: Record<number, string> = { 1: 'Faixa 1 (até R$2.850)', 2: 'Faixa 2 (até R$4.700)', 3: 'Faixa 3 (até R$8.000)', 0: 'Sem enquadramento MCMV' }; return { principal: { valor: faixa, label: nomes[faixa], fmt: 'txt' }, detalhes: [{ l: 'Renda', v: v.renda, fmt: 'brl' }, { l: 'Subsídio estimado', v: faixa === 1 ? 'Até R$55.000' : faixa === 2 ? 'Até R$30.000' : faixa === 3 ? 'Até R$5.000' : 'Nenhum', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-subsidio-mcmv', titulo: 'Simulador Subsídio MCMV', desc: 'Estime o subsídio recebível no programa Minha Casa Minha Vida.', cat: 'programas-sociais', icon: '🏠', campos: [{ k: 'renda', l: 'Renda Familiar', p: '3000', u: 'R$' }, { k: 'valorImovel', l: 'Valor do Imóvel', p: '200000', u: 'R$' }], fn: (v) => { const subsidio = v.renda <= 2850 ? 55000 : v.renda <= 4700 ? 30000 : v.renda <= 8000 ? 5000 : 0; const entrada = Math.max(0, v.valorImovel * 0.20 - subsidio); return { principal: { valor: subsidio, label: 'Subsídio Estimado', fmt: 'brl' }, detalhes: [{ l: 'Valor do Imóvel', v: v.valorImovel, fmt: 'brl' }, { l: 'Entrada estimada', v: Math.round(entrada * 100) / 100, fmt: 'brl' }, { l: 'A financiar', v: Math.round((v.valorImovel - subsidio) * 100) / 100, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-prestacao-mcmv-faixa1', titulo: 'Prestação MCMV Faixa 1', desc: 'Estime a prestação no MCMV para Faixa 1.', cat: 'programas-sociais', icon: '🏠', campos: [{ k: 'renda', l: 'Renda Familiar', p: '2000', u: 'R$' }], fn: (v) => { const prestacao = Math.min(v.renda * 0.05, 80); return { principal: { valor: Math.round(prestacao * 100) / 100, label: 'Prestação Estimada (Faixa 1)', fmt: 'brl' }, detalhes: [{ l: 'Máximo 5% da renda', v: Math.round(v.renda * 0.05 * 100) / 100, fmt: 'brl' }, { l: 'Teto', v: 80, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-prestacao-mcmv-faixa2', titulo: 'Prestação MCMV Faixa 2', desc: 'Calcule a prestação aproximada no MCMV Faixa 2.', cat: 'programas-sociais', icon: '🏠', campos: [{ k: 'valorFinanciado', l: 'Valor Financiado', p: '150000', u: 'R$' }, { k: 'meses', l: 'Prazo (meses)', p: '360', min: 60 }], fn: (v) => { const r = calcularFinanciamentoPrice(v.valorFinanciado, 0.5, v.meses); return { principal: { valor: r.parcela, label: 'Prestação Estimada (Faixa 2)', fmt: 'brl' }, detalhes: [{ l: 'Total pago', v: r.totalPago, fmt: 'brl' }, { l: 'Juros (estimativa 6%aa)', v: r.totalJuros, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-prestacao-mcmv-faixa3', titulo: 'Prestação MCMV Faixa 3', desc: 'Calcule a prestação no MCMV Faixa 3.', cat: 'programas-sociais', icon: '🏠', campos: [{ k: 'valorFinanciado', l: 'Valor Financiado', p: '200000', u: 'R$' }, { k: 'meses', l: 'Prazo (meses)', p: '360', min: 60 }], fn: (v) => { const r = calcularFinanciamentoPrice(v.valorFinanciado, 0.7, v.meses); return { principal: { valor: r.parcela, label: 'Prestação Estimada (Faixa 3)', fmt: 'brl' }, detalhes: [{ l: 'Total pago', v: r.totalPago, fmt: 'brl' }, { l: 'Juros totais', v: r.totalJuros, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-mcmv-fgts', titulo: 'MCMV com FGTS', desc: 'Use o FGTS como entrada no Minha Casa Minha Vida.', cat: 'programas-sociais', icon: '🏦', campos: [{ k: 'saldoFgts', l: 'Saldo FGTS', p: '15000', u: 'R$' }, { k: 'valorImovel', l: 'Valor do Imóvel', p: '200000', u: 'R$' }, { k: 'subsidio', l: 'Subsídio estimado', p: '30000', u: 'R$' }], fn: (v) => { const valorFinanciado = Math.max(0, v.valorImovel - v.saldoFgts - v.subsidio); return { principal: { valor: Math.round(valorFinanciado * 100) / 100, label: 'Valor a Financiar', fmt: 'brl' }, detalhes: [{ l: 'Valor imóvel', v: v.valorImovel, fmt: 'brl' }, { l: 'FGTS utilizado', v: v.saldoFgts, fmt: 'brl' }, { l: 'Subsídio MCMV', v: v.subsidio, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-mcmv-rural', titulo: 'MCMV Rural', desc: 'Estime o valor do subsídio MCMV para imóvel rural.', cat: 'programas-sociais', icon: '🌾', campos: [{ k: 'renda', l: 'Renda Familiar', p: '1500', u: 'R$' }], fn: (v) => { const subsidio = v.renda <= 2850 ? 50000 : v.renda <= 4700 ? 25000 : 0; return { principal: { valor: subsidio, label: 'Subsídio Rural Estimado', fmt: 'brl' }, detalhes: [{ l: 'Renda familiar', v: v.renda, fmt: 'brl' }, { l: 'Programa', v: 'MCMV Rural / CasaVerde Amarela', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-economia-farmacia-popular', titulo: 'Economia Farmácia Popular', desc: 'Calcule quanto você economiza com medicamentos na Farmácia Popular.', cat: 'programas-sociais', icon: '💊', campos: [{ k: 'precoParticular', l: 'Preço na farmácia comum', p: '80', u: 'R$' }, { k: 'precoPopular', l: 'Preço na Farmácia Popular', p: '0', u: 'R$' }], fn: (v) => { const economia = v.precoParticular - v.precoPopular; const pct = v.precoParticular > 0 ? (economia / v.precoParticular) * 100 : 0; return { principal: { valor: Math.round(economia * 100) / 100, label: 'Economia por Compra', fmt: 'brl' }, detalhes: [{ l: 'Economia anual (12 meses)', v: Math.round(economia * 12 * 100) / 100, fmt: 'brl', cor: '#16c784' }, { l: 'Percentual de desconto', v: Math.round(pct * 100) / 100, fmt: 'pct' }] } }, dis: 'Consulte a lista de medicamentos disponíveis na Farmácia Popular.' },
  { slug: 'calculadora-medicamentos-gratuitos', titulo: 'Medicamentos Gratuitos pelo SUS', desc: 'Estime a economia com medicamentos gratuitos pelo SUS/REME.', cat: 'programas-sociais', icon: '💊', campos: [{ k: 'gastoMensal', l: 'Gasto mensal atual com medicamentos', p: '300', u: 'R$' }], fn: (v) => { return { principal: { valor: Math.round(v.gastoMensal * 12 * 100) / 100, label: 'Potencial Economia Anual', fmt: 'brl' }, detalhes: [{ l: 'Economia mensal potencial', v: v.gastoMensal, fmt: 'brl' }], aviso: 'Medicamentos gratuitos dependem de disponibilidade e prescrição médica na rede SUS.' } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-economia-tratamento-cronico', titulo: 'Economia Tratamento Crônico', desc: 'Calcule economia no tratamento de doenças crônicas via programas públicos.', cat: 'programas-sociais', icon: '❤️', campos: [{ k: 'custoMensal', l: 'Custo mensal do tratamento particular', p: '500', u: 'R$' }, { k: 'anos', l: 'Anos de tratamento', p: '10', min: 1 }], fn: (v) => { const total = v.custoMensal * 12 * v.anos; return { principal: { valor: Math.round(total * 100) / 100, label: 'Total economizável em tratamento', fmt: 'brl' }, detalhes: [{ l: 'Por ano', v: v.custoMensal * 12, fmt: 'brl' }, { l: 'Por mês', v: v.custoMensal, fmt: 'brl' }] } }, dis: 'Programas como Aqui tem Farmácia Popular e REMUME oferecem gratuidade para doenças crônicas.' },
  { slug: 'calculadora-garantia-safra', titulo: 'Calculadora Garantia Safra', desc: 'Estime o benefício do Garantia Safra para agricultor familiar.', cat: 'programas-sociais', icon: '🌾', campos: [{ k: 'municipio', l: 'Município em área de semiárido?', t: 'sel', op: [['1','Sim'],['0','Não']] }], fn: (v) => { const valor = v.municipio === 1 ? 1200 : 0; return { principal: { valor, label: 'Garantia Safra (estimativa)', fmt: 'brl' }, detalhes: [{ l: 'Parcelas', v: valor > 0 ? 6 : 0, fmt: 'num' }, { l: 'Por parcela', v: valor > 0 ? 200 : 0, fmt: 'brl' }], aviso: valor === 0 ? 'Garantia Safra é exclusivo para municípios do semiárido.' : undefined } }, dis: DIS_SOCIAL },
  { slug: 'simulador-seguro-defeso', titulo: 'Simulador Seguro Defeso', desc: 'Estime o valor do Seguro Defeso para pescadores artesanais.', cat: 'programas-sociais', icon: '🎣', campos: [{ k: 'meses', l: 'Meses de defeso', p: '4', min: 1, max: 6 }], fn: (v) => { const valor = SALARIO_MINIMO_2026 * v.meses; return { principal: { valor: Math.round(valor * 100) / 100, label: 'Seguro Defeso Total', fmt: 'brl' }, detalhes: [{ l: 'Por mês', v: SALARIO_MINIMO_2026, fmt: 'brl' }, { l: 'Meses de defeso', v: v.meses, fmt: 'num' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-aposentadoria-rural', titulo: 'Aposentadoria Rural', desc: 'Estime o valor da aposentadoria rural por idade.', cat: 'programas-sociais', icon: '👨‍🌾', campos: [{ k: 'idade', l: 'Idade atual', p: '55', min: 50 }], fn: (v) => { const idadeMin = 55; const elegivel = v.idade >= idadeMin; return { principal: { valor: elegivel ? SALARIO_MINIMO_2026 : 0, label: elegivel ? 'Aposentadoria Rural (1 SM)' : 'Sem direito ainda', fmt: 'brl' }, detalhes: [{ l: 'Idade mínima: 55 anos (mulher) / 60 (homem)', v: `${v.idade} anos`, fmt: 'txt' }, { l: 'Valor', v: SALARIO_MINIMO_2026, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-pronaf', titulo: 'Calculadora PRONAF', desc: 'Estime o valor de crédito rural pelo PRONAF.', cat: 'programas-sociais', icon: '🚜', campos: [{ k: 'modalidade', l: 'Modalidade', t: 'sel', op: [['1','Custeio (até R$250k)'],['2','Investimento (até R$400k)'],['3','Mulher (até R$21k)']] }, { k: 'valor', l: 'Valor solicitado', p: '50000', u: 'R$' }], fn: (v) => { const limites: Record<number, number> = { 1: 250000, 2: 400000, 3: 21000 }; const limite = limites[v.modalidade] || 250000; const aprovado = Math.min(v.valor, limite); return { principal: { valor: aprovado, label: 'Crédito PRONAF Estimado', fmt: 'brl' }, detalhes: [{ l: 'Limite da modalidade', v: limite, fmt: 'brl' }, { l: 'Taxa de juros', v: 'Entre 3% e 6% aa (2026)', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-salario-maternidade-inss', titulo: 'Salário Maternidade — INSS', desc: 'Calcule o salário maternidade pago pelo INSS.', cat: 'programas-sociais', icon: '🤱', campos: [{ k: 'salario', l: 'Média dos últimos 12 salários', p: '2500', u: 'R$' }, { k: 'dias', l: 'Dias de licença', t: 'sel', op: [['120','120 dias'],['180','180 dias']] }], fn: (v) => { const diario = v.salario / 30; const total = diario * v.dias; return { principal: { valor: Math.round(total * 100) / 100, label: 'Total Salário Maternidade', fmt: 'brl' }, detalhes: [{ l: 'Valor diário', v: Math.round(diario * 100) / 100, fmt: 'brl' }, { l: 'Dias', v: v.dias, fmt: 'num' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-salario-maternidade-mei', titulo: 'Salário Maternidade — MEI', desc: 'Calcule o salário maternidade para MEI (1 salário mínimo).', cat: 'programas-sociais', icon: '🤱', campos: [{ k: 'meses', l: 'Meses de contribuição como MEI', p: '10', min: 0 }], fn: (v) => { const elegivel = v.meses >= 10; const total = elegivel ? SALARIO_MINIMO_2026 * 4 : 0; return { principal: { valor: total, label: 'Salário Maternidade MEI (4 meses)', fmt: 'brl' }, detalhes: [{ l: 'Por mês', v: SALARIO_MINIMO_2026, fmt: 'brl' }, { l: 'Mínimo: 10 meses de contribuição', v: elegivel ? 'OK' : 'INSUFICIENTE', fmt: 'txt', cor: elegivel ? '#16c784' : '#ef4444' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-salario-familia', titulo: 'Calculadora Salário Família', desc: 'Calcule o valor do salário família por filho.', cat: 'programas-sociais', icon: '👶', campos: [{ k: 'filhos', l: 'Filhos até 14 anos', p: '2', min: 0 }, { k: 'salario', l: 'Salário Bruto', p: '1800', u: 'R$' }], fn: (v) => { const elegivel = v.salario <= 1900; const valorPorFilho = 62.04; const total = elegivel ? v.filhos * valorPorFilho : 0; return { principal: { valor: Math.round(total * 100) / 100, label: 'Salário Família Total', fmt: 'brl' }, detalhes: [{ l: 'Por filho', v: valorPorFilho, fmt: 'brl' }, { l: 'Filhos elegíveis', v: v.filhos, fmt: 'num' }, { l: 'Elegível pelo salário', v: elegivel ? 'SIM' : 'Salário acima do limite', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-aposentadoria-tempo-contribuicao', titulo: 'Aposentadoria por Tempo de Contribuição', desc: 'Estime o valor da aposentadoria com base no tempo de contribuição.', cat: 'programas-sociais', icon: '👴', campos: [{ k: 'salario', l: 'Média Salarial', p: '3000', u: 'R$' }, { k: 'anos', l: 'Anos de contribuição', p: '35', min: 1 }], fn: (v) => { const pct = Math.min(0.60 + (v.anos - 20) * 0.02, 1.0); const beneficio = Math.max(SALARIO_MINIMO_2026, v.salario * pct); return { principal: { valor: Math.round(beneficio * 100) / 100, label: 'Aposentadoria Estimada', fmt: 'brl' }, detalhes: [{ l: 'Percentual aplicado', v: Math.round(pct * 100), fmt: 'pct' }, { l: 'Mínimo (1 SM)', v: SALARIO_MINIMO_2026, fmt: 'brl' }] } }, dis: 'Estimativa. O valor real depende de cálculo oficial pelo INSS.' },
  { slug: 'calculadora-aposentadoria-por-idade', titulo: 'Aposentadoria por Idade', desc: 'Calcule a aposentadoria por idade (65/62 anos com 15 anos de contribuição).', cat: 'programas-sociais', icon: '🎂', campos: [{ k: 'salario', l: 'Média Salarial', p: '2500', u: 'R$' }, { k: 'anosContribuicao', l: 'Anos de contribuição', p: '20', min: 15 }], fn: (v) => { const pct = 0.60 + (v.anosContribuicao - 15) * 0.02; const beneficio = Math.max(SALARIO_MINIMO_2026, v.salario * Math.min(pct, 1.0)); return { principal: { valor: Math.round(beneficio * 100) / 100, label: 'Aposentadoria por Idade Estimada', fmt: 'brl' }, detalhes: [{ l: 'Percentual', v: Math.round(Math.min(pct, 1.0) * 100), fmt: 'pct' }, { l: 'Requisito: 65 anos (H) / 62 anos (M)', v: 'Confirme sua idade', fmt: 'txt' }] } }, dis: 'Estimativa simplificada. O cálculo real usa todas as contribuições da carreira.' },
  { slug: 'calculadora-pensao-por-morte', titulo: 'Calculadora de Pensão por Morte', desc: 'Estime a pensão por morte do cônjuge ou dependente.', cat: 'programas-sociais', icon: '💙', campos: [{ k: 'beneficioFalecido', l: 'Benefício ou Salário do Falecido', p: '3000', u: 'R$' }], fn: (v) => { const pensao = Math.max(SALARIO_MINIMO_2026, v.beneficioFalecido * 0.50 + SALARIO_MINIMO_2026 * 0.10); return { principal: { valor: Math.round(pensao * 100) / 100, label: 'Pensão por Morte Estimada', fmt: 'brl' }, detalhes: [{ l: 'Parcela fixa (50%)', v: Math.round(v.beneficioFalecido * 0.50 * 100) / 100, fmt: 'brl' }, { l: 'Adicional dependentes', v: Math.round(SALARIO_MINIMO_2026 * 0.10 * 100) / 100, fmt: 'brl' }] } }, dis: 'Valores estimados. O cálculo exato depende de análise do INSS.' },
  { slug: 'calculadora-auxilio-doenca-inss', titulo: 'Auxílio-Doença INSS', desc: 'Calcule o valor do Auxílio-Doença (afastamento médico).', cat: 'programas-sociais', icon: '🏥', campos: [{ k: 'salario', l: 'Média dos últimos 12 salários', p: '2500', u: 'R$' }], fn: (v) => { const auxilio = Math.max(SALARIO_MINIMO_2026, v.salario * 0.91); return { principal: { valor: Math.round(auxilio * 100) / 100, label: 'Auxílio-Doença Estimado', fmt: 'brl' }, detalhes: [{ l: '91% da média salarial', v: Math.round(v.salario * 0.91 * 100) / 100, fmt: 'brl' }, { l: 'Mínimo garantido', v: SALARIO_MINIMO_2026, fmt: 'brl' }] } }, dis: 'Estimativa. Requer perícia médica do INSS. Aguardar carência de 15 dias.' },
  { slug: 'calculadora-auxilio-acidente', titulo: 'Calculadora Auxílio Acidente', desc: 'Estime o valor do auxílio acidente pago pelo INSS.', cat: 'programas-sociais', icon: '⚠️', campos: [{ k: 'salario', l: 'Salário na época do acidente', p: '2500', u: 'R$' }], fn: (v) => { const auxilio = Math.max(SALARIO_MINIMO_2026 * 0.50, v.salario * 0.50); return { principal: { valor: Math.round(auxilio * 100) / 100, label: 'Auxílio Acidente (50%)', fmt: 'brl' }, detalhes: [{ l: 'Base de cálculo', v: v.salario, fmt: 'brl' }, { l: 'Percentual', v: 50, fmt: 'pct' }] } }, dis: 'O auxílio acidente é pago cumulativamente com o salário, após consolidação das lesões.' },
  { slug: 'calculadora-abono-salarial-pis', titulo: 'Calculadora Abono Salarial PIS/PASEP', desc: 'Calcule o valor do abono salarial PIS conforme meses trabalhados.', cat: 'programas-sociais', icon: '💵', campos: [{ k: 'mesesTrabalhados', l: 'Meses trabalhados no ano-base', p: '12', min: 1, max: 12 }, { k: 'salario', l: 'Remuneração média', p: '2000', u: 'R$' }], fn: (v) => { const elegivel = v.salario <= 2 * SALARIO_MINIMO_2026; const valor = elegivel ? (SALARIO_MINIMO_2026 / 12) * v.mesesTrabalhados : 0; return { principal: { valor: Math.round(valor * 100) / 100, label: elegivel ? 'Abono PIS Estimado' : 'Sem direito (salário acima de 2 SM)', fmt: 'brl' }, detalhes: [{ l: 'Limite salarial', v: 2 * SALARIO_MINIMO_2026, fmt: 'brl' }, { l: 'Meses trabalhados', v: v.mesesTrabalhados, fmt: 'num' }] } }, dis: DIS_SOCIAL },
  { slug: 'verificador-abono-salarial', titulo: 'Verificador Abono Salarial', desc: 'Verifique se você tem direito ao abono salarial PIS.', cat: 'programas-sociais', icon: '✅', campos: [{ k: 'salario', l: 'Salário médio do ano-base', p: '1800', u: 'R$' }, { k: 'meses', l: 'Meses trabalhados', p: '12', min: 1 }, { k: 'cadastrado', l: 'Cadastrado há 5+ anos no PIS?', t: 'sel', op: [['1','Sim'],['0','Não']] }], fn: (v) => { const elegivel = v.salario <= 2 * SALARIO_MINIMO_2026 && v.meses >= 1 && v.cadastrado === 1; return { principal: { valor: elegivel ? 1 : 0, label: elegivel ? 'ELEGÍVEL' : 'Sem direito', fmt: 'txt' }, detalhes: [{ l: 'Salário ≤ 2 SM', v: v.salario <= 2 * SALARIO_MINIMO_2026 ? 'OK' : 'Fora do limite', fmt: 'txt', cor: v.salario <= 2 * SALARIO_MINIMO_2026 ? '#16c784' : '#ef4444' }, { l: 'Registro PIS 5+ anos', v: v.cadastrado === 1 ? 'OK' : 'Verificar', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-pis-proporcional', titulo: 'PIS — Valor Proporcional', desc: 'Calcule o PIS proporcional pelos meses trabalhados.', cat: 'programas-sociais', icon: '💵', campos: [{ k: 'meses', l: 'Meses trabalhados', p: '8', min: 1, max: 12 }], fn: (v) => { const valor = (SALARIO_MINIMO_2026 / 12) * v.meses; return { principal: { valor: Math.round(valor * 100) / 100, label: 'PIS Proporcional', fmt: 'brl' }, detalhes: [{ l: 'Por mês', v: Math.round((SALARIO_MINIMO_2026 / 12) * 100) / 100, fmt: 'brl' }, { l: 'PIS cheio (12 meses)', v: SALARIO_MINIMO_2026, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-garantia-safra-valor', titulo: 'Garantia Safra — Valor Total', desc: 'Calcule o total do benefício Garantia Safra recebido.', cat: 'programas-sociais', icon: '🌾', campos: [{ k: 'parcelas', l: 'Número de parcelas', p: '6', min: 1, max: 6 }], fn: (v) => { const porParcela = 200; const total = v.parcelas * porParcela; return { principal: { valor: total, label: 'Total Garantia Safra', fmt: 'brl' }, detalhes: [{ l: 'Por parcela', v: porParcela, fmt: 'brl' }, { l: 'Parcelas', v: v.parcelas, fmt: 'num' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-agua-para-todos', titulo: 'Água para Todos — Estimativa', desc: 'Estime o acesso ao programa Água para Todos.', cat: 'programas-sociais', icon: '💧', campos: [{ k: 'membros', l: 'Membros da família', p: '5', min: 1 }, { k: 'renda', l: 'Renda familiar', p: '700', u: 'R$' }], fn: (v) => { const rpc = v.renda / v.membros; const elegivel = rpc <= BOLSA_FAMILIA_2026.renda_maxima_per_capita; return { principal: { valor: elegivel ? 1 : 0, label: elegivel ? 'Potencialmente elegível' : 'Sem enquadramento', fmt: 'txt' }, detalhes: [{ l: 'Renda per capita', v: Math.round(rpc * 100) / 100, fmt: 'brl' }, { l: 'Programa destinado ao semiárido', v: 'Verificar no CRAS', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-itr-rural', titulo: 'Calculadora ITR Rural', desc: 'Calcule o ITR (Imposto Territorial Rural) da sua propriedade.', cat: 'programas-sociais', icon: '🌾', campos: [{ k: 'areaTotal', l: 'Área total (hectares)', p: '50', min: 0 }, { k: 'areaUtilizada', l: 'Área utilizada (%)', p: '80', u: '%' }, { k: 'vtu', l: 'Valor da terra nua (R$/ha)', p: '5000', u: 'R$' }], fn: (v) => { const gu = v.areaUtilizada / 100; const aliquota = gu >= 0.80 ? 0.0003 : gu >= 0.65 ? 0.002 : gu >= 0.50 ? 0.0064 : 0.016; const vtn = v.areaTotal * v.vtu; const itr = vtn * aliquota; return { principal: { valor: Math.round(itr * 100) / 100, label: 'ITR Anual Estimado', fmt: 'brl' }, detalhes: [{ l: 'VTN total', v: Math.round(vtn * 100) / 100, fmt: 'brl' }, { l: 'Alíquota', v: aliquota * 100, fmt: 'pct' }, { l: 'Grau de Utilização', v: v.areaUtilizada, fmt: 'pct' }] } }, dis: 'Estimativa. O ITR real depende do DIAT e declaração no site da Receita Federal.' },
  { slug: 'calculadora-juros-abusivos', titulo: 'Calculadora de Juros Abusivos', desc: 'Identifique se os juros do seu contrato são abusivos.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'taxaContrato', l: 'Taxa mensal do contrato (%)', p: '15', u: '%' }, { k: 'taxaMercado', l: 'Taxa de mercado referência (%)', p: '6', u: '%' }], fn: (v) => { const diferenca = v.taxaContrato - v.taxaMercado; const abusivo = diferenca > v.taxaMercado; return { principal: { valor: Math.round(diferenca * 100) / 100, label: 'Excesso sobre taxa de mercado', fmt: 'pct' }, detalhes: [{ l: 'Taxa do contrato', v: v.taxaContrato, fmt: 'pct' }, { l: 'Taxa de mercado', v: v.taxaMercado, fmt: 'pct' }, { l: 'Status', v: abusivo ? 'POSSIVELMENTE ABUSIVO' : 'Dentro do mercado', fmt: 'txt', cor: abusivo ? '#ef4444' : '#16c784' }], aviso: abusivo ? 'Consulte um advogado ou PROCON para revisão contratual.' : undefined } }, dis: 'Apenas orientativo. A configuração de juros abusivos depende de análise jurídica.' },
  { slug: 'calculadora-juros-abusivos-cartao', titulo: 'Juros Abusivos — Cartão de Crédito', desc: 'Veja se os juros do seu cartão são abusivos comparados ao mercado.', cat: 'programas-sociais', icon: '💳', campos: [{ k: 'taxaMensal', l: 'Taxa mensal do cartão (%)', p: '15', u: '%' }], fn: (v) => { const mediaCartao = 17.3; const abusivo = v.taxaMensal > mediaCartao * 1.5; return { principal: { valor: Math.round((v.taxaMensal * 12) * 100) / 100, label: 'Juros Anuais', fmt: 'pct' }, detalhes: [{ l: 'Taxa mensal', v: v.taxaMensal, fmt: 'pct' }, { l: 'Média mercado (est.)', v: mediaCartao, fmt: 'pct' }, { l: 'Status', v: abusivo ? 'MUITO ACIMA DA MÉDIA' : 'Próximo do mercado', fmt: 'txt', cor: abusivo ? '#ef4444' : '#16c784' }] } }, dis: 'Consulte PROCON ou Banco Central sobre portabilidade de dívidas.' },
  { slug: 'calculadora-juros-abusivos-cheque', titulo: 'Juros Abusivos — Cheque Especial', desc: 'Verifique se os juros do cheque especial são abusivos (teto: 8% a.m.).', cat: 'programas-sociais', icon: '🏦', campos: [{ k: 'taxaMensal', l: 'Taxa mensal do cheque especial (%)', p: '8', u: '%' }], fn: (v) => { const TETO = 8; const abusivo = v.taxaMensal > TETO; return { principal: { valor: v.taxaMensal, label: 'Taxa Mensal', fmt: 'pct' }, detalhes: [{ l: 'Teto legal (Res. BCB 4.765)', v: TETO, fmt: 'pct' }, { l: 'Status', v: abusivo ? 'ACIMA DO TETO LEGAL' : 'Dentro do teto', fmt: 'txt', cor: abusivo ? '#ef4444' : '#16c784' }] } }, dis: 'Desde 2020 o Banco Central limita os juros do cheque especial a 8% ao mês.' },
  { slug: 'calculadora-juros-abusivos-carro', titulo: 'Juros Abusivos — Financiamento de Carro', desc: 'Identifique se os juros do financiamento do seu carro são abusivos.', cat: 'programas-sociais', icon: '🚗', campos: [{ k: 'taxaMensal', l: 'Taxa mensal do financiamento (%)', p: '2', u: '%' }], fn: (v) => { const mediaMercado = 1.8; const abusivo = v.taxaMensal > mediaMercado * 2; return { principal: { valor: Math.round(v.taxaMensal * 12 * 100) / 100, label: 'Juros Anuais', fmt: 'pct' }, detalhes: [{ l: 'Média mercado auto', v: mediaMercado, fmt: 'pct' }, { l: 'Status', v: abusivo ? 'POSSIVELMENTE ABUSIVO' : 'Dentro do mercado', fmt: 'txt', cor: abusivo ? '#ef4444' : '#16c784' }] } }, dis: 'Consulte o banco emissor e compare com outras instituições antes de questionar.' },
  { slug: 'calculadora-revisao-contrato', titulo: 'Calculadora Revisão Contratual', desc: 'Estime o valor a ser revisado em contratos com juros abusivos.', cat: 'programas-sociais', icon: '📄', campos: [{ k: 'divida', l: 'Saldo devedor atual', p: '20000', u: 'R$' }, { k: 'taxaContrato', l: 'Taxa mensal contrato (%)', p: '10', u: '%' }, { k: 'taxaJusta', l: 'Taxa justa de mercado (%)', p: '3', u: '%' }, { k: 'mesesRestantes', l: 'Meses restantes', p: '24', min: 1 }], fn: (v) => { const i1 = v.taxaContrato / 100; const i2 = v.taxaJusta / 100; const parcelaAtual = v.divida * (i1 * Math.pow(1 + i1, v.mesesRestantes)) / (Math.pow(1 + i1, v.mesesRestantes) - 1); const parcelaJusta = v.divida * (i2 * Math.pow(1 + i2, v.mesesRestantes)) / (Math.pow(1 + i2, v.mesesRestantes) - 1); const economia = (parcelaAtual - parcelaJusta) * v.mesesRestantes; return { principal: { valor: Math.round(economia * 100) / 100, label: 'Economia com Revisão', fmt: 'brl' }, detalhes: [{ l: 'Parcela atual', v: Math.round(parcelaAtual * 100) / 100, fmt: 'brl' }, { l: 'Parcela justa', v: Math.round(parcelaJusta * 100) / 100, fmt: 'brl' }] } }, dis: 'Consulte um advogado especialista em direito do consumidor.' },
  { slug: 'calculadora-juros-consignado-abusivo', titulo: 'Juros Abusivos — Consignado', desc: 'Verifique se os juros do consignado são abusivos (teto 2,14% a.m.).', cat: 'programas-sociais', icon: '💳', campos: [{ k: 'taxaMensal', l: 'Taxa mensal do consignado (%)', p: '2.5', u: '%' }], fn: (v) => { const TETO = 2.14; const abusivo = v.taxaMensal > TETO; return { principal: { valor: v.taxaMensal, label: 'Taxa Consignado', fmt: 'pct' }, detalhes: [{ l: 'Teto INSS 2026', v: TETO, fmt: 'pct' }, { l: 'Status', v: abusivo ? 'ACIMA DO TETO' : 'Dentro do limite', fmt: 'txt', cor: abusivo ? '#ef4444' : '#16c784' }] } }, dis: 'O teto de juros do consignado INSS é definido periodicamente pelo Conselho Nacional de Previdência.' },
  { slug: 'calculadora-divida-juros-abusivos', titulo: 'Dívida com Juros Abusivos', desc: 'Calcule o quanto sua dívida cresceu por conta de juros abusivos.', cat: 'programas-sociais', icon: '📈', campos: [{ k: 'valorOriginal', l: 'Dívida original', p: '10000', u: 'R$' }, { k: 'taxaMensal', l: 'Taxa mensal cobrada (%)', p: '15', u: '%' }, { k: 'meses', l: 'Meses em atraso', p: '12', min: 1 }], fn: (v) => { const atual = v.valorOriginal * Math.pow(1 + v.taxaMensal / 100, v.meses); const excesso = atual - v.valorOriginal; return { principal: { valor: Math.round(atual * 100) / 100, label: 'Dívida Atual com Juros', fmt: 'brl' }, detalhes: [{ l: 'Dívida original', v: v.valorOriginal, fmt: 'brl' }, { l: 'Juros acumulados', v: Math.round(excesso * 100) / 100, fmt: 'brl', cor: '#ef4444' }] } }, dis: 'Consulte um advogado para possível revisão judicial dos juros.' },
  { slug: 'calculadora-spread-bancario', titulo: 'Calculadora de Spread Bancário', desc: 'Calcule o spread entre custo do dinheiro e taxa cobrada pelo banco.', cat: 'programas-sociais', icon: '🏦', campos: [{ k: 'taxaCaptacao', l: 'Taxa de captação (CDI %)', p: '14.75', u: '%' }, { k: 'taxaCobrada', l: 'Taxa cobrada pelo banco (%)', p: '40', u: '%' }], fn: (v) => { const spread = v.taxaCobrada - v.taxaCaptacao; return { principal: { valor: Math.round(spread * 100) / 100, label: 'Spread Bancário (% ao ano)', fmt: 'pct' }, detalhes: [{ l: 'Taxa captação (CDI)', v: v.taxaCaptacao, fmt: 'pct' }, { l: 'Taxa cobrada', v: v.taxaCobrada, fmt: 'pct' }, { l: 'Spread', v: Math.round(spread * 100) / 100, fmt: 'pct', cor: '#ef4444' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-indenizacao-juros-abusivos', titulo: 'Indenização por Juros Abusivos', desc: 'Estime o valor de indenização por cobrança de juros abusivos.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'valorCobradoExcesso', l: 'Valor cobrado a mais (excesso)', p: '5000', u: 'R$' }], fn: (v) => { const indenizacao = v.valorCobradoExcesso + v.valorCobradoExcesso * 0.1; return { principal: { valor: Math.round(indenizacao * 100) / 100, label: 'Indenização Estimada', fmt: 'brl' }, detalhes: [{ l: 'Restituição em dobro (art. 42 CDC)', v: v.valorCobradoExcesso * 2, fmt: 'brl' }, { l: 'Dano moral (estimativa)', v: 2000, fmt: 'brl' }] } }, dis: 'Consulte um advogado especialista em direito do consumidor para ajuizar ação.' },
  { slug: 'calculadora-cet-real', titulo: 'Calculadora CET Real do Empréstimo', desc: 'Calcule o Custo Efetivo Total real do seu empréstimo.', cat: 'programas-sociais', icon: '💰', campos: [{ k: 'valorEmprestimo', l: 'Valor do empréstimo', p: '10000', u: 'R$' }, { k: 'valorPago', l: 'Total pago (todas as parcelas)', p: '15000', u: 'R$' }, { k: 'meses', l: 'Prazo (meses)', p: '24', min: 1 }], fn: (v) => { const custo = v.valorPago - v.valorEmprestimo; const pct = (custo / v.valorEmprestimo) * 100; return { principal: { valor: Math.round(pct * 100) / 100, label: 'CET Real Total (%)', fmt: 'pct' }, detalhes: [{ l: 'Custo total do crédito', v: Math.round(custo * 100) / 100, fmt: 'brl' }, { l: 'CET mensal estimado', v: Math.round((pct / v.meses) * 100) / 100, fmt: 'pct' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-indenizacao-dano-moral', titulo: 'Calculadora Dano Moral', desc: 'Estime o valor de indenização por dano moral.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'salario', l: 'Salário da parte prejudicada', p: '3000', u: 'R$' }, { k: 'gravidade', l: 'Gravidade do dano', t: 'sel', op: [['1','Leve'],['2','Médio'],['3','Grave']] }], fn: (v) => { const multiplicadores: Record<number, number> = { 1: 5, 2: 15, 3: 40 }; const mult = multiplicadores[v.gravidade] || 5; const valor = v.salario * mult; return { principal: { valor: Math.round(valor * 100) / 100, label: 'Dano Moral Estimado', fmt: 'brl' }, detalhes: [{ l: 'Salário base', v: v.salario, fmt: 'brl' }, { l: 'Multiplicador', v: mult, fmt: 'num' }] } }, dis: 'Apenas estimativa. O juiz decide o valor com base no caso concreto.' },
  { slug: 'calculadora-honorarios-advogado', titulo: 'Calculadora Honorários de Advogado', desc: 'Estime os honorários advocatícios conforme tipo de causa.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'valorCausa', l: 'Valor da causa', p: '50000', u: 'R$' }, { k: 'tipo', l: 'Tipo de honorários', t: 'sel', op: [['1','Êxito (10–20%)'],['2','Fixo mensal'],['3','Por ato']] }], fn: (v) => { const honorario = v.tipo === 1 ? v.valorCausa * 0.15 : v.tipo === 2 ? 1500 : 500; return { principal: { valor: Math.round(honorario * 100) / 100, label: 'Honorários Estimados', fmt: 'brl' }, detalhes: [{ l: 'Tipo', v: v.tipo === 1 ? 'Por êxito' : v.tipo === 2 ? 'Mensal' : 'Por ato', fmt: 'txt' }, { l: 'OAB recomenda mínimo 10% do valor da causa', v: Math.round(v.valorCausa * 0.10 * 100) / 100, fmt: 'brl' }] } }, dis: 'Honorários são livremente negociados entre cliente e advogado.' },
  { slug: 'simulador-inventario-itcmd', titulo: 'Simulador Inventário — ITCMD', desc: 'Calcule o ITCMD (imposto sobre herança) do inventário.', cat: 'programas-sociais', icon: '📜', campos: [{ k: 'valorHeranca', l: 'Valor Total da Herança', p: '500000', u: 'R$' }, { k: 'aliquota', l: 'Alíquota ITCMD do Estado (%)', p: '4', u: '%', min: 1, max: 8 }], fn: (v) => { const itcmd = v.valorHeranca * (v.aliquota / 100); const custas = v.valorHeranca * 0.01; return { principal: { valor: Math.round(itcmd * 100) / 100, label: 'ITCMD a Pagar', fmt: 'brl' }, detalhes: [{ l: 'Valor da herança', v: v.valorHeranca, fmt: 'brl' }, { l: 'Custas processuais est.', v: Math.round(custas * 100) / 100, fmt: 'brl' }, { l: 'Total inventário', v: Math.round((itcmd + custas) * 100) / 100, fmt: 'brl' }] } }, dis: 'Consulte um advogado e o cartório local para valores exatos.' },
  { slug: 'calculadora-partilha-bens', titulo: 'Calculadora de Partilha de Bens', desc: 'Calcule o valor a receber em partilha de bens (divórcio/herança).', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'patrimonioTotal', l: 'Patrimônio Total do Casal', p: '300000', u: 'R$' }, { k: 'herdeiros', l: 'Número de herdeiros/cônjuges', p: '2', min: 1 }], fn: (v) => { const parcela = v.patrimonioTotal / v.herdeiros; return { principal: { valor: Math.round(parcela * 100) / 100, label: 'Valor por Herdeiro', fmt: 'brl' }, detalhes: [{ l: 'Patrimônio total', v: v.patrimonioTotal, fmt: 'brl' }, { l: 'Herdeiros', v: v.herdeiros, fmt: 'num' }] } }, dis: 'Cálculo simplificado. A partilha real depende de meação, regime e dívidas.' },
  { slug: 'calculadora-multa-contratual', titulo: 'Calculadora de Multa Contratual', desc: 'Calcule a multa por rescisão antecipada de contrato.', cat: 'programas-sociais', icon: '📝', campos: [{ k: 'valorContrato', l: 'Valor total do contrato', p: '12000', u: 'R$' }, { k: 'pctMulta', l: 'Percentual de multa (%)', p: '10', u: '%' }, { k: 'mesesRestantes', l: 'Meses restantes', p: '6', min: 0 }], fn: (v) => { const multa = v.valorContrato * (v.pctMulta / 100); const proporcional = v.valorContrato > 0 ? multa * (v.mesesRestantes / 12) : 0; return { principal: { valor: Math.round(multa * 100) / 100, label: 'Multa Contratual', fmt: 'brl' }, detalhes: [{ l: 'Multa proporcional', v: Math.round(proporcional * 100) / 100, fmt: 'brl' }, { l: 'Percentual', v: v.pctMulta, fmt: 'pct' }] } }, dis: 'Verifique as cláusulas do contrato. O CDC pode limitar multas abusivas.' },
  { slug: 'simulador-acao-trabalhista', titulo: 'Simulador de Ação Trabalhista', desc: 'Estime o valor de uma ação trabalhista por verbas não pagas.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'salario', l: 'Salário Bruto', p: '3000', u: 'R$' }, { k: 'meses', l: 'Meses de verbas pendentes', p: '12', min: 1 }], fn: (v) => { const verbas = v.salario * v.meses; const ferias = (v.salario / 12) * (v.meses / 12) * v.meses * 1.333; const fgts = v.salario * 0.08 * v.meses * 1.4; const total = verbas + ferias + fgts; return { principal: { valor: Math.round(total * 100) / 100, label: 'Valor Estimado da Ação', fmt: 'brl' }, detalhes: [{ l: 'Verbas salariais', v: Math.round(verbas * 100) / 100, fmt: 'brl' }, { l: 'Férias + 1/3', v: Math.round(ferias * 100) / 100, fmt: 'brl' }, { l: 'FGTS + multa 40%', v: Math.round(fgts * 100) / 100, fmt: 'brl' }] } }, dis: 'Estimativa. Consulte um advogado trabalhista para análise do seu caso.' },
  { slug: 'calculadora-correcao-monetaria-judicial', titulo: 'Correção Monetária Judicial', desc: 'Calcule a correção monetária de uma dívida judicial.', cat: 'programas-sociais', icon: '📈', campos: [{ k: 'valor', l: 'Valor original', p: '10000', u: 'R$' }, { k: 'anos', l: 'Anos de atraso', p: '3', min: 1 }, { k: 'ipca', l: 'IPCA médio anual (%)', p: '5', u: '%' }], fn: (v) => { const corrigido = v.valor * Math.pow(1 + v.ipca / 100, v.anos); const juros = v.valor * 0.01 * 12 * v.anos; return { principal: { valor: Math.round((corrigido + juros) * 100) / 100, label: 'Valor Corrigido', fmt: 'brl' }, detalhes: [{ l: 'Correção IPCA', v: Math.round((corrigido - v.valor) * 100) / 100, fmt: 'brl' }, { l: 'Juros 1% am', v: Math.round(juros * 100) / 100, fmt: 'brl' }] } }, dis: 'Verifique o índice aplicado na decisão judicial. Alguns usam Selic ou IPCA-E.' },
  { slug: 'calculadora-juros-mora', titulo: 'Calculadora de Juros de Mora', desc: 'Calcule os juros de mora em 1% ao mês sobre dívidas em atraso.', cat: 'programas-sociais', icon: '⏰', campos: [{ k: 'valor', l: 'Valor da dívida', p: '5000', u: 'R$' }, { k: 'meses', l: 'Meses em atraso', p: '6', min: 1 }], fn: (v) => { const juros = v.valor * 0.01 * v.meses; const total = v.valor + juros; return { principal: { valor: Math.round(juros * 100) / 100, label: 'Juros de Mora', fmt: 'brl' }, detalhes: [{ l: 'Valor original', v: v.valor, fmt: 'brl' }, { l: 'Total devido', v: Math.round(total * 100) / 100, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-prazo-prescricional', titulo: 'Calculadora Prazo Prescricional', desc: 'Verifique se a dívida ou ação ainda pode ser cobrada judicialmente.', cat: 'programas-sociais', icon: '⏳', campos: [{ k: 'tipo', l: 'Tipo de dívida/ação', t: 'sel', op: [['1','Trabalhista (2 anos)'],['2','Consumidor (5 anos)'],['3','Civil geral (10 anos)'],['4','Tributária (5 anos)']] }, { k: 'anosPassados', l: 'Anos desde a origem', p: '3', min: 0 }], fn: (v) => { const prazos: Record<number, number> = { 1: 2, 2: 5, 3: 10, 4: 5 }; const prazo = prazos[v.tipo] || 5; const restante = prazo - v.anosPassados; const prescrito = restante <= 0; return { principal: { valor: Math.max(0, restante), label: prescrito ? 'PRESCRITO' : `Anos restantes`, fmt: prescrito ? 'txt' : 'num' }, detalhes: [{ l: 'Prazo total', v: prazo, fmt: 'num' }, { l: 'Status', v: prescrito ? 'Dívida prescrita — não pode ser cobrada' : 'Ainda dentro do prazo', fmt: 'txt', cor: prescrito ? '#16c784' : '#f59e0b' }] } }, dis: 'A prescrição tem exceções. Consulte um advogado para confirmar.' },
  { slug: 'calculadora-itcmd-heranca', titulo: 'ITCMD sobre Herança', desc: 'Calcule o ITCMD (imposto de transmissão por herança) por estado.', cat: 'programas-sociais', icon: '📜', campos: [{ k: 'valorHeranca', l: 'Valor da herança', p: '300000', u: 'R$' }, { k: 'aliquota', l: 'Alíquota ITCMD (%)', p: '4', u: '%', min: 1, max: 8 }], fn: (v) => { const itcmd = v.valorHeranca * (v.aliquota / 100); return { principal: { valor: Math.round(itcmd * 100) / 100, label: 'ITCMD a Pagar', fmt: 'brl' }, detalhes: [{ l: 'Valor líquido', v: Math.round((v.valorHeranca - itcmd) * 100) / 100, fmt: 'brl' }, { l: 'Alíquota', v: v.aliquota, fmt: 'pct' }] } }, dis: 'A alíquota varia por estado: SP=4%, RJ=4%, MG=5%. Consulte a Fazenda Estadual.' },
  { slug: 'calculadora-custas-processuais', titulo: 'Custas Processuais', desc: 'Estime as custas para entrar com uma ação judicial.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'valorCausa', l: 'Valor da causa', p: '30000', u: 'R$' }, { k: 'tipo', l: 'Tipo de ação', t: 'sel', op: [['1','Trabalhista (gratuita)'],['2','Cível (2–3%)'],['3','JEC — Juizados (gratuita)']] }], fn: (v) => { const custas = v.tipo === 2 ? v.valorCausa * 0.02 : 0; return { principal: { valor: Math.round(custas * 100) / 100, label: v.tipo !== 2 ? 'Gratuita (sem custas)' : 'Custas Estimadas', fmt: 'brl' }, detalhes: [{ l: 'Valor da causa', v: v.valorCausa, fmt: 'brl' }, { l: 'Justiça gratuita disponível se necessário', v: 'Solicite ao advogado', fmt: 'txt' }] } }, dis: 'Custas variam por estado e tribunal. Verifique na tabela do TJ local.' },
  { slug: 'calculadora-renda-total-beneficios', titulo: 'Renda Total com Benefícios', desc: 'Some todos os benefícios recebidos pela família.', cat: 'programas-sociais', icon: '💰', campos: [{ k: 'salario', l: 'Salário/Renda própria', p: '1621', u: 'R$' }, { k: 'bolsaFamilia', l: 'Bolsa Família', p: '600', u: 'R$' }, { k: 'bpc', l: 'BPC', p: '0', u: 'R$' }, { k: 'outros', l: 'Outros benefícios', p: '0', u: 'R$' }], fn: (v) => { const total = v.salario + v.bolsaFamilia + v.bpc + v.outros; return { principal: { valor: Math.round(total * 100) / 100, label: 'Renda Total Mensal', fmt: 'brl' }, detalhes: [{ l: 'Salário/Renda', v: v.salario, fmt: 'brl' }, { l: 'Bolsa Família', v: v.bolsaFamilia, fmt: 'brl' }, { l: 'BPC', v: v.bpc, fmt: 'brl' }, { l: 'Outros', v: v.outros, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'verificador-acumulo-beneficios', titulo: 'Verificador Acúmulo de Benefícios', desc: 'Veja quais benefícios podem ou não ser acumulados.', cat: 'programas-sociais', icon: '✅', campos: [{ k: 'recebeBF', l: 'Recebe Bolsa Família?', t: 'sel', op: [['1','Sim'],['0','Não']] }, { k: 'recebeBPC', l: 'Recebe BPC?', t: 'sel', op: [['1','Sim'],['0','Não']] }], fn: (v) => { const conflito = v.recebeBF === 1 && v.recebeBPC === 1; return { principal: { valor: conflito ? 1 : 0, label: conflito ? 'ATENÇÃO: BF e BPC não acumulam' : 'Sem conflito identificado', fmt: 'txt' }, detalhes: [{ l: 'BF + BPC', v: 'NÃO pode acumular', fmt: 'txt', cor: '#ef4444' }, { l: 'BF + Vale Gás', v: 'PODE acumular', fmt: 'txt', cor: '#16c784' }, { l: 'BF + Pé-de-Meia', v: 'PODE acumular', fmt: 'txt', cor: '#16c784' }], aviso: conflito ? 'BPC e Bolsa Família não podem ser recebidos simultaneamente.' : undefined } }, dis: DIS_SOCIAL },
  { slug: 'simulador-regras-transicao-inss', titulo: 'Simulador Regras de Transição INSS', desc: 'Descubra qual regra de transição é mais vantajosa para sua aposentadoria.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'idade', l: 'Idade atual', p: '50', min: 18 }, { k: 'anosContrib', l: 'Anos de contribuição', p: '25', min: 0 }], fn: (v) => { const pontos = v.idade + v.anosContrib; const metaPontos = 103; const faltaPontos = Math.max(0, metaPontos - pontos); const faltaIdade = Math.max(0, 65 - v.idade); return { principal: { valor: Math.min(faltaPontos, faltaIdade), label: 'Mínimo de anos para aposentar', fmt: 'num' }, detalhes: [{ l: 'Pontos atuais', v: pontos, fmt: 'num' }, { l: 'Meta pontos (103)', v: metaPontos, fmt: 'num' }, { l: 'Regra da idade (65 anos)', v: `${faltaIdade} anos restantes`, fmt: 'txt' }] } }, dis: 'Resultado aproximado. Verifique no Meu INSS.' },
  { slug: 'calculadora-sistema-pontos-inss', titulo: 'Sistema de Pontos INSS', desc: 'Calcule quando você atinge os pontos para aposentadoria.', cat: 'programas-sociais', icon: '🎯', campos: [{ k: 'idade', l: 'Idade atual', p: '48', min: 18 }, { k: 'anosContrib', l: 'Anos de contribuição', p: '22', min: 0 }], fn: (v) => { const pontos = v.idade + v.anosContrib; const META_H = 105; const META_M = 100; const faltaH = Math.max(0, META_H - pontos); const faltaM = Math.max(0, META_M - pontos); return { principal: { valor: pontos, label: 'Pontos Atuais', fmt: 'num' }, detalhes: [{ l: 'Meta homem (105)', v: faltaH > 0 ? `Faltam ${faltaH} pontos` : 'Atingido!', fmt: 'txt', cor: faltaH <= 0 ? '#16c784' : undefined }, { l: 'Meta mulher (100)', v: faltaM > 0 ? `Faltam ${faltaM} pontos` : 'Atingido!', fmt: 'txt', cor: faltaM <= 0 ? '#16c784' : undefined }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-aposentadoria-especial', titulo: 'Aposentadoria Especial', desc: 'Calcule quando você tem direito à aposentadoria especial (atividades insalubres).', cat: 'programas-sociais', icon: '⚠️', campos: [{ k: 'tipo', l: 'Tempo de contribuição especial', t: 'sel', op: [['25','25 anos (muito alto risco)'],['20','20 anos (alto risco)'],['15','15 anos (risco excepcional)']] }, { k: 'anosAtual', l: 'Anos de contribuição especial atual', p: '10', min: 0 }], fn: (v) => { const falta = Math.max(0, v.tipo - v.anosAtual); return { principal: { valor: falta, label: 'Anos restantes para aposentadoria especial', fmt: 'num' }, detalhes: [{ l: 'Exigência', v: v.tipo, fmt: 'num' }, { l: 'Contribuição atual', v: v.anosAtual, fmt: 'num' }, { l: 'Valor: 100% do salário de benefício', v: 'Verificar no INSS', fmt: 'txt' }] } }, dis: 'Requer comprovação via LTCAT e PPP da empresa.' },
  { slug: 'simulador-mei-aposentadoria', titulo: 'MEI — Simulador de Aposentadoria', desc: 'Simule a aposentadoria para MEI contribuindo com 5% do salário mínimo.', cat: 'programas-sociais', icon: '🏪', campos: [{ k: 'anosContrib', l: 'Anos contribuindo como MEI', p: '15', min: 0 }, { k: 'idade', l: 'Idade atual', p: '50', min: 18 }], fn: (v) => { const beneficio = SALARIO_MINIMO_2026; const contribuicaoMensal = SALARIO_MINIMO_2026 * 0.05; return { principal: { valor: beneficio, label: 'Aposentadoria MEI (1 SM)', fmt: 'brl' }, detalhes: [{ l: 'Contribuição mensal', v: Math.round(contribuicaoMensal * 100) / 100, fmt: 'brl' }, { l: 'Anos de contribuição', v: v.anosContrib, fmt: 'num' }, { l: 'ATENÇÃO: MEI só tem direito à aposentadoria por idade', v: 'Para aposentadoria por tempo, contribuir com 20%', fmt: 'txt' }] } }, dis: 'MEI que contribui com 5% têm apenas aposentadoria por idade e invalidez.' },
  { slug: 'calculadora-contribuicao-facultativa', titulo: 'Contribuição Facultativa INSS', desc: 'Calcule o valor da contribuição facultativa para garantir benefícios INSS.', cat: 'programas-sociais', icon: '📊', campos: [{ k: 'rendimento', l: 'Rendimento mensal', p: '3000', u: 'R$' }, { k: 'aliquota', l: 'Alíquota', t: 'sel', op: [['20','20% (plano completo)'],['11','11% (aposentadoria por idade)'],['5','5% (MEI)']] }], fn: (v) => { const contribuicao = Math.min(v.rendimento * (v.aliquota / 100), 8157.41 * (v.aliquota / 100)); return { principal: { valor: Math.round(contribuicao * 100) / 100, label: 'Contribuição Mensal', fmt: 'brl' }, detalhes: [{ l: 'Rendimento', v: v.rendimento, fmt: 'brl' }, { l: 'Alíquota', v: v.aliquota, fmt: 'pct' }, { l: 'Anual', v: Math.round(contribuicao * 12 * 100) / 100, fmt: 'brl' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-adiar-aposentadoria', titulo: 'Simulador: Vale a Pena Adiar a Aposentadoria?', desc: 'Calcule o ganho de adiar a aposentadoria por alguns anos.', cat: 'programas-sociais', icon: '⏰', campos: [{ k: 'beneficioHoje', l: 'Benefício se aposentar hoje', p: '3000', u: 'R$' }, { k: 'anosAdiar', l: 'Anos para adiar', p: '3', min: 1 }, { k: 'incremento', l: 'Incremento por ano adiado (%)', p: '5', u: '%' }], fn: (v) => { const beneficioFuturo = v.beneficioHoje * Math.pow(1 + v.incremento / 100, v.anosAdiar); const ganhoMensal = beneficioFuturo - v.beneficioHoje; const mesesParaRecuperar = (v.beneficioHoje * v.anosAdiar * 12) / ganhoMensal; return { principal: { valor: Math.round(beneficioFuturo * 100) / 100, label: 'Benefício após adiar', fmt: 'brl' }, detalhes: [{ l: 'Ganho mensal', v: Math.round(ganhoMensal * 100) / 100, fmt: 'brl', cor: '#16c784' }, { l: 'Meses para recuperar o que deixou de receber', v: Math.round(mesesParaRecuperar), fmt: 'num' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-beneficio-primeira-infancia', titulo: 'Benefício Primeira Infância', desc: 'Calcule todos os benefícios disponíveis para famílias com bebês.', cat: 'programas-sociais', icon: '👶', campos: [{ k: 'membros', l: 'Membros', p: '3', min: 1 }, { k: 'renda', l: 'Renda familiar', p: '700', u: 'R$' }, { k: 'bebes', l: 'Bebês 0–6 anos', p: '1', min: 0 }], fn: (v) => { const bf = calcBF(v.membros, v.renda, v.bebes, 0, 0, 0); const salMaternidade = 4 * SALARIO_MINIMO_2026; return { principal: { valor: bf, label: 'Bolsa Família Mensal', fmt: 'brl' }, detalhes: [{ l: 'Adicional 1ª infância', v: v.bebes * 150, fmt: 'brl' }, { l: 'Salário maternidade (mãe MEI)', v: salMaternidade, fmt: 'brl' }, { l: 'Pé-de-Meia (até 6 meses)', v: 'Verificar elegibilidade', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-programa-crianca-feliz', titulo: 'Programa Criança Feliz', desc: 'Veja os benefícios do Programa Criança Feliz para primeira infância.', cat: 'programas-sociais', icon: '😊', campos: [{ k: 'idadeCrianca', l: 'Idade da criança (meses)', p: '18', min: 0, max: 72 }], fn: (v) => { const elegivel = v.idadeCrianca <= 72; return { principal: { valor: elegivel ? 1 : 0, label: elegivel ? 'Criança elegível ao programa' : 'Fora da faixa etária', fmt: 'txt' }, detalhes: [{ l: 'Visitas domiciliares', v: 'Mensais por profissional', fmt: 'txt' }, { l: 'Faixa etária', v: '0 a 72 meses (6 anos)', fmt: 'txt' }, { l: 'Acompanhamento', v: 'Gratuito pelo município', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-nutriz', titulo: 'Adicional Nutriz — Bolsa Família', desc: 'Calcule o adicional para mães amamentando no Bolsa Família.', cat: 'programas-sociais', icon: '🤱', campos: [{ k: 'nutrizes', l: 'Mães amamentando', p: '1', min: 0 }], fn: (v) => { const adicional = v.nutrizes * BOLSA_FAMILIA_2026.adicional_variavel; return { principal: { valor: adicional, label: 'Adicional Nutriz', fmt: 'brl' }, detalhes: [{ l: 'Por nutriz', v: BOLSA_FAMILIA_2026.adicional_variavel, fmt: 'brl' }, { l: 'Duração', v: 'Até 6 meses após o parto', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-auxilio-recluso', titulo: 'Calculadora Auxílio Recluso', desc: 'Verifique o valor do auxílio-recluso para dependentes de preso.', cat: 'programas-sociais', icon: '⚖️', campos: [{ k: 'salarioAnterior', l: 'Último salário do segurado', p: '1800', u: 'R$' }], fn: (v) => { const elegivel = v.salarioAnterior <= 1.4 * SALARIO_MINIMO_2026; const valor = elegivel ? SALARIO_MINIMO_2026 : 0; return { principal: { valor, label: elegivel ? 'Auxílio-Recluso' : 'Sem direito (salário acima do limite)', fmt: 'brl' }, detalhes: [{ l: 'Limite salarial', v: Math.round(1.4 * SALARIO_MINIMO_2026 * 100) / 100, fmt: 'brl' }, { l: 'Valor', v: SALARIO_MINIMO_2026, fmt: 'brl' }] } }, dis: 'O auxílio-recluso é pago aos dependentes de segurado de baixa renda encarcerado em regime fechado.' },
  { slug: 'verificador-isencao-ipva-pcd', titulo: 'Verificador Isenção IPVA PcD', desc: 'Verifique a isenção de IPVA para Pessoas com Deficiência.', cat: 'programas-sociais', icon: '♿', campos: [{ k: 'estado', l: 'Estado', t: 'sel', op: [['1','SP (isento)'],['2','RJ (isento)'],['3','MG (isento)'],['4','Outros']] }, { k: 'valorFipe', l: 'Valor FIPE do veículo', p: '50000', u: 'R$' }, { k: 'aliquota', l: 'Alíquota normal (%)', p: '4', u: '%' }], fn: (v) => { const ipvaNormal = v.valorFipe * (v.aliquota / 100); return { principal: { valor: Math.round(ipvaNormal * 100) / 100, label: 'Economia com isenção PcD', fmt: 'brl' }, detalhes: [{ l: 'IPVA normal', v: Math.round(ipvaNormal * 100) / 100, fmt: 'brl' }, { l: 'Com isenção PcD', v: 0, fmt: 'brl', cor: '#16c784' }, { l: 'Requerer na DETRAN com laudo médico', v: 'Verifique na DETRAN', fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'calculadora-isencao-ir-doenca', titulo: 'Isenção IR por Doença Grave', desc: 'Verifique a isenção de Imposto de Renda por doença grave.', cat: 'programas-sociais', icon: '💊', campos: [{ k: 'rendimentoAposentadoria', l: 'Rendimento de aposentadoria/pensão', p: '5000', u: 'R$' }], fn: (v) => { return { principal: { valor: Math.round(v.rendimentoAposentadoria * 0.275 * 100) / 100, label: 'Economia anual com isenção IR', fmt: 'brl' }, detalhes: [{ l: 'Rendimento isento', v: v.rendimentoAposentadoria, fmt: 'brl' }, { l: 'Doenças isentas', v: 'Câncer, AIDS, cardiopatia grave, Parkinson e outras', fmt: 'txt' }] } }, dis: 'A isenção deve ser solicitada na Receita Federal com laudo médico oficial.' },
  { slug: 'calculadora-isencao-concurso-cadunico', titulo: 'Isenção Concurso Público — CadÚnico', desc: 'Calcule economia com isenção de taxa de concurso pelo CadÚnico.', cat: 'programas-sociais', icon: '📝', campos: [{ k: 'taxaConcurso', l: 'Taxa de inscrição', p: '80', u: 'R$' }, { k: 'concursos', l: 'Concursos no ano', p: '5', min: 1 }], fn: (v) => { const economia = v.taxaConcurso * v.concursos; return { principal: { valor: Math.round(economia * 100) / 100, label: 'Economia com Isenção', fmt: 'brl' }, detalhes: [{ l: 'Inscrição insenta por concurso', v: v.taxaConcurso, fmt: 'brl' }, { l: 'Requer CadÚnico e renda ≤ 2 SM', v: `Limite: R$${(2 * SALARIO_MINIMO_2026).toFixed(2)}`, fmt: 'txt' }] } }, dis: DIS_SOCIAL },
  { slug: 'simulador-carteira-idoso', titulo: 'Simulador Carteira do Idoso', desc: 'Veja os benefícios da Carteira do Idoso no transporte público.', cat: 'programas-sociais', icon: '🎫', campos: [{ k: 'viagensMes', l: 'Viagens de ônibus/mês', p: '20', min: 0 }, { k: 'tarifaPassagem', l: 'Tarifa da passagem', p: '5', u: 'R$' }, { k: 'renda', l: 'Renda do idoso', p: '1621', u: 'R$' }], fn: (v) => { const gratuito = v.renda <= 2 * SALARIO_MINIMO_2026; const economia = gratuito ? v.viagensMes * v.tarifaPassagem * 2 : 0; return { principal: { valor: Math.round(economia * 100) / 100, label: 'Economia mensal no transporte', fmt: 'brl' }, detalhes: [{ l: 'Gratuidade: 2 viagens/dia', v: gratuito ? 'ELEGÍVEL' : 'Acima do limite de renda', fmt: 'txt', cor: gratuito ? '#16c784' : '#ef4444' }] } }, dis: 'Gratuidade garantida para idosos com renda ≤ 2 salários mínimos (Estatuto do Idoso).' },
]
