// lib/mei/slugs.ts
// 350+ slugs para a seção /mei — MEI, PJ, Autônomo, Comparativos

export const SLUGS_MEI: string[] = [

  // ── MEI — Abertura e gestão (50 slugs) ───────────────────────────────────
  'como-abrir-mei-2026',
  'mei-portal-empreendedor',
  'cnpj-mei-gratuito',
  'mei-atividades-permitidas-2026',
  'mei-atividades-vedadas',
  'mei-limite-faturamento-2026',
  'das-mei-2026',
  'das-mei-vencimento',
  'das-mei-atraso-multa',
  'parcelamento-das-mei',
  'declaracao-anual-mei-2026',
  'dasn-mei-prazo-2026',
  'mei-funcionario-clt',
  'mei-pode-contratar-funcionario',
  'nota-fiscal-mei',
  'nfe-mei-como-emitir',
  'nfse-mei-servicos',
  'mei-simples-nacional-diferenca',
  'mei-faturamento-acima-limite',
  'mei-desenquadramento-2026',
  'cancelar-mei-2026',
  'baixa-mei-como-fazer',
  'mei-em-atraso-o-que-fazer',
  'divida-ativa-mei',
  'refis-mei-2026',
  'parcelamento-mei-divida',
  'mei-banco-conta-pj',
  'mei-maquininha-cartao',
  'mei-investimento-estrangeiro',
  'mei-atividade-rural',
  'mei-motorista-uber-2026',
  'mei-entregador-ifood',
  'mei-manicure-2026',
  'mei-cabeleireiro-2026',
  'mei-fotografo-2026',
  'mei-designer-pode-ser-mei',
  'mei-programador-pode-ser-mei',
  'mei-advogado-pode-ser-mei',
  'mei-medico-pode-ser-mei',
  'mei-corretor-imoveis',
  'mei-contador-obrigatorio',
  'mei-imposto-renda-2026',
  'mei-declarar-ir',
  'mei-receita-federal-obrigacoes',
  'mei-alvara-funcionamento',
  'mei-vigilancia-sanitaria',
  'mei-licencas-necessarias',
  'mei-endereco-fiscal',
  'mei-home-office',
  'mei-certificado-digital',

  // ── MEI — Benefícios e previdência (30 slugs) ────────────────────────────
  'aposentadoria-mei-2026',
  'aposentadoria-por-idade-mei',
  'mei-nao-tem-aposentadoria-tempo',
  'auxilio-doenca-mei',
  'salario-maternidade-mei',
  'auxilio-acidente-mei',
  'pensao-morte-mei',
  'inss-mei-como-funciona',
  'contribuicao-mei-conta-para-aposentadoria',
  'contribuicao-complementar-mei',
  'mei-complementar-inss-11-porcento',
  'mei-plano-de-saude',
  'mei-fgts-tem-direito',
  'mei-seguro-desemprego',
  'mei-ferias-tem-direito',
  'mei-13-salario-tem-direito',
  'tempo-contribuicao-mei-como-calcular',
  'mei-microempreendedor-direitos',
  'mei-vs-autonomo-previdencia',
  'mei-vs-clt-beneficios',
  'mei-vs-pj-beneficios',
  'mei-contratante-responsabilidade',
  'vinculo-empregaticio-mei-riscos',
  'pejotizacao-o-que-e',
  'mei-rescisao-indireta',
  'mei-doenca-o-que-fazer',
  'afastamento-mei-doenca',
  'periodo-carencia-inss-mei',
  'mei-gravida-direitos',
  'licenca-maternidade-mei',

  // ── PJ / Empresa (50 slugs) ──────────────────────────────────────────────
  'abrir-empresa-2026',
  'como-abrir-empresa',
  'tipos-empresa-brasil',
  'ltda-como-abrir',
  'eireli-extinta-2026',
  'slu-sociedade-limitada-unipessoal',
  'sociedade-simples-como-abrir',
  'regime-tributario-como-escolher',
  'simples-nacional-2026',
  'simples-nacional-aliquotas-2026',
  'simples-nacional-anexo-i',
  'simples-nacional-anexo-iii',
  'simples-nacional-anexo-v',
  'lucro-presumido-2026',
  'lucro-real-2026',
  'mei-vs-simples-nacional',
  'simples-vs-lucro-presumido',
  'quando-sair-mei-para-simples',
  'pro-labore-2026',
  'distribuicao-lucros-2026',
  'dividendos-pj-2026',
  'pj-imposto-renda-2026',
  'pj-vs-clt-calculo-completo',
  'terceirizacao-pj-riscos',
  'cnpj-como-abrir-gratis',
  'contabilidade-pj-custo',
  'contador-obrigatorio-pj',
  'nota-fiscal-empresa-como-emitir',
  'escrituracao-contabil',
  'balanco-patrimonial-obrigatorio',
  'encerramento-empresa-2026',
  'falencia-empresa-pequena',
  'recuperacao-judicial-pequena-empresa',
  'debentures-empresa-pequena',
  'capital-social-minimo',
  'socio-responsabilidade-ltda',
  'alteracao-contrato-social',
  'transferencia-cotas-empresa',
  'empresa-familiar-gestao',
  'holding-familiar-2026',
  'offshore-empresa-brasil',
  'empresa-exterior-brasil',
  'filial-empresa-como-abrir',
  'franquia-como-funciona',
  'franquia-vs-empresa-propria',
  'startups-me-epp',
  'mei-para-startup',
  'angel-investor-brasil',
  'crowdfunding-empresa',
  'aceleradoras-brasil',

  // ── Autônomo (40 slugs) ──────────────────────────────────────────────────
  'autonomo-como-funciona-2026',
  'rpa-recibo-pagamento-autonomo',
  'autonomo-inss-2026',
  'autonomo-contribuicao-inss',
  'autonomo-imposto-renda',
  'carne-leao-autonomo-2026',
  'autonomo-vs-pj-calculo',
  'autonomo-vs-mei-diferenca',
  'autonomo-nota-fiscal',
  'iss-autonomo-2026',
  'autonomo-previdencia-social',
  'autonomo-fgts-tem-direito',
  'autonomo-ferias-tem-direito',
  'autonomo-sindico',
  'autonomo-trabalhador-intermitente',
  'trabalho-intermitente-clt',
  'freelancer-brasil-legislacao',
  'plataformas-freelancer-brasil',
  'uber-autonomo-ou-mei',
  'ifood-entregador-autonomo',
  '99-motorista-autonomo',
  'influencer-como-declarar-ir',
  'youtuber-como-tributar',
  'streamer-como-tributar',
  'afiliado-como-tributar',
  'dropshipping-como-tributar',
  'adsense-como-declarar-ir',
  'renda-exterior-autonomo',
  'autonomo-multiplos-cnpjs',
  'autonomo-aposentadoria',
  'contribuicao-11-inss-autonomo',
  'contribuicao-20-inss-autonomo',
  'inss-certo-qual-aliquota',
  'autonomo-limite-contribuicao',
  'autonomo-beneficios-inss',
  'desoneracao-folha-2026',
  'cooperativa-trabalho-2026',
  'terceirizacao-legal-2026',
  'prestacao-servico-contrato',
  'contrato-prestacao-servico-modelo',

  // ── Comparativos e guias (60 slugs) ──────────────────────────────────────
  'clt-vs-pj-2026',
  'clt-vs-mei-2026',
  'pj-vs-mei-2026',
  'autonomo-vs-clt-vantagens',
  'vale-a-pena-ser-pj-2026',
  'vale-a-pena-ser-mei-2026',
  'pejotizacao-riscos-trabalhistas',
  'reforma-trabalhista-pj',
  'mei-escala-7x1',
  'mei-home-office-deducoes',
  'pj-home-office-deducoes',
  'custo-funcionario-clt-pj',
  'terceirizar-ou-contratar-clt',
  'empresa-individual-vs-mei',
  'startup-funcionario-stock-option',
  'participacao-lucros-resultados-plr',
  'plr-como-calcular',
  'beneficios-corporativos-2026',
  'vale-alimentacao-2026',
  'vale-transporte-empresa',
  'plano-saude-empresa-deducao',
  'previdencia-privada-empresa',
  'participacao-acionaria-funcionario',
  'equity-startup-brasil',
  'vesting-brasil-como-funciona',
  'clt-flexivel-2026',
  'teletrabalho-legislacao-2026',
  'contrato-hibrido-2026',
  'trabalho-4-dias-semana-brasil',
  'reforma-trabalhista-2026',

  // ── Mais guias práticos (80 slugs) ───────────────────────────────────────
  'mei-faturamento-como-controlar',
  'como-emitir-das-mei-2026',
  'das-mei-2-via-como-emitir',
  'mei-perdeu-prazo-das',
  'parcelamento-mei-pgmei',
  'mei-pgmei-como-acessar',
  'mei-ccmei-o-que-e',
  'mei-certificate-digital-obrigatorio',
  'mei-altera-atividade',
  'mei-muda-endereco',
  'mei-outro-estado',
  'mei-dois-enderecos',
  'mei-atividade-principal-secundaria',
  'cnaes-mei-lista-2026',
  'mei-sem-movimento',
  'dasn-mei-sem-faturamento',
  'dasn-mei-como-preencher',
  'dasn-mei-retificadora',
  'mei-multa-dasn-nao-entregue',
  'mei-divida-parcelamento-online',
  'mei-certidao-negativa',
  'simples-nacional-exclusao-mei',
  'mei-limite-ultrapassado-o-que-fazer',
  'mei-rescisao-funcionario',
  'mei-e-social',
  'mei-gfip-obrigatorio',
  'mei-folha-pagamento',
  'mei-ferias-funcionario',
  'mei-13-salario-funcionario',
  'mei-rescisao-sem-justa-causa',
  'faturamento-mei-como-calcular',
  'mei-comprovante-renda',
  'mei-financiamento-habitacional',
  'mei-credito-bancario',
  'mei-microfinancas',
  'mei-pronampe-2026',
  'mei-simei',
  'mei-desonerado',
  'mei-iss-fixo-variavel',
  'mei-icms-st',
  'mei-nfe-consumidor-final',
  'mei-venda-online',
  'mei-marketplace',
  'mei-dropshipping',
  'mei-exportacao',
  'mei-importacao',
  'mei-produtos-alimenticios',
  'mei-industria-artesanal',
  'mei-producao-caseira',
  'mei-artesao-2026',
  'contabilidade-custo-mensal-pj',
  'dre-o-que-e',
  'balancete-mensal',
  'livro-caixa-autonomo',
  'carnê-leão-como-pagar',
  'darf-como-gerar',
  'sped-contabil',
  'ecf-declaracao',
  'ecd-escrituracao',
  'defis-simples-nacional',
  'pgdas-simples-como-gerar',
  'das-simples-nacional-como-pagar',
  'parcelamento-simples-nacional',
  'exclusao-simples-nacional-como-evitar',
  'aliquota-efetiva-simples-nacional',
  'fator-r-simples-nacional',
  'fator-r-como-calcular',
  'simples-nacional-anexo-ii',
  'simples-nacional-anexo-iv',
  'quando-ir-lucro-presumido',
  'vantagens-lucro-presumido-servicos',
  'lucro-real-quando-obrigatorio',
  'holding-vantagens-tributarias',
  'planejamento-tributario-pme',
  'elisao-fiscal-o-que-e',
  'mei-bpc-pode-acumular',
  'inss-mei-conta-para-bpc',
  'aposentadoria-rural-mei',
  'mei-idoso',
  'mei-pcd-direitos',

  // ── Guias de nichos (40 slugs) ────────────────────────────────────────────
  'mei-personal-trainer',
  'mei-nutricionista',
  'mei-fisioterapeuta',
  'mei-psicologo-pode',
  'mei-veterinario',
  'mei-pet-shop',
  'mei-loja-roupas',
  'mei-food-truck',
  'mei-confeitaria',
  'mei-buffet',
  'mei-borracharia',
  'mei-mecanico',
  'mei-eletricista',
  'mei-pintor',
  'mei-pedreiro',
  'mei-marceneiro',
  'mei-serralheiro',
  'mei-costureira',
  'mei-sapateiro',
  'mei-chaveiro',
  'mei-assistencia-tecnica',
  'mei-celular-assistencia',
  'mei-informatica-manutencao',
  'mei-desenvolvedor-software',
  'mei-social-media',
  'mei-copywriter',
  'mei-tradutor',
  'mei-professor-particular',
  'mei-musico',
  'mei-fotografo-casamento',
  'mei-videomaker',
  'mei-motoboy',
  'mei-caminhoneiro',
  'mei-taxista',
  'mei-eletrodomesticos',
  'mei-seguranca-patrimonial',
  'mei-porteiro-condominio',
  'mei-diarista-pode-ser-mei',
  'mei-jardineiro',
  'mei-dedetizacao',
]

// ─── Detecção de tipo de slug ─────────────────────────────────────────────────

export type TipoSlugMEI =
  | 'abertura'
  | 'das'
  | 'beneficios'
  | 'previdencia'
  | 'pj'
  | 'simples'
  | 'autonomo'
  | 'comparativo'
  | 'niche'
  | 'generico'

export function detectarTipoMEI(slug: string): TipoSlugMEI {
  if (slug.includes('das') || slug.includes('pgmei') || slug.includes('parcelamento-mei') || slug.includes('dasn')) return 'das'
  if (slug.includes('aposentadoria') || slug.includes('inss-mei') || slug.includes('auxilio') || slug.includes('salario-maternidade') || slug.includes('contribuicao-mei') || slug.includes('carencia') || slug.includes('previdencia') || slug.includes('pensao') || slug.includes('afastamento')) return 'previdencia'
  if (slug.includes('beneficio') || slug.includes('fgts-tem') || slug.includes('ferias-tem') || slug.includes('13-salario-tem') || slug.includes('direito')) return 'beneficios'
  if (slug.includes('simples-nacional') || slug.includes('lucro-presumido') || slug.includes('lucro-real') || slug.includes('pro-labore') || slug.includes('dividendo') || slug.includes('regime') || slug.includes('ltda') || slug.includes('slu') || slug.includes('holding') || slug.includes('cnpj-como') || slug.includes('abrir-empresa') || slug.includes('tipos-empresa') || slug.includes('capital-social')) return 'pj'
  if (slug.includes('autonomo') || slug.includes('rpa') || slug.includes('carne-leao') || slug.includes('freelancer') || slug.includes('afiliado') || slug.includes('youtuber') || slug.includes('streamer') || slug.includes('influencer') || slug.includes('adsense') || slug.includes('dropshipping')) return 'autonomo'
  if (slug.includes('clt-vs') || slug.includes('vs-clt') || slug.includes('vs-mei') || slug.includes('vs-pj') || slug.includes('pj-vs') || slug.includes('mei-vs') || slug.includes('vale-a-pena') || slug.includes('comparativo') || slug.includes('pejotizacao') || slug.includes('custo-funcionario') || slug.includes('terceirizar')) return 'comparativo'
  if (slug.includes('das-mei') || slug.includes('como-abrir-mei') || slug.includes('portal-empreendedor') || slug.includes('cnpj-mei') || slug.includes('atividades') || slug.includes('limite-faturamento') || slug.includes('nota-fiscal-mei') || slug.includes('cancelar-mei') || slug.includes('baixa-mei')) return 'abertura'
  if (/mei-(personal|nutricionista|fisio|psicologo|veterinario|pet|loja|food|confeit|buffet|borr|mecanico|eletricista|pintor|pedreiro|marce|serralheiro|costureir|sapateiro|chaveir|assistencia|celular|informatica|desenvolved|social|copy|tradutor|professor|musico|fotografo|video|motoboy|caminhon|taxista|eletrodom|segu|porteiro|diar|jardineir|dedet)/.test(slug)) return 'niche'
  return 'generico'
}
