// lib/saude/slugs.ts
// ~250 slugs de páginas sobre Saúde e Plano de Saúde 2026

export const SLUGS_SAUDE: string[] = [

  // ── Planos de saúde — geral (25 slugs) ─────────────────────────────────
  'plano-saude-individual-2026',
  'plano-saude-familiar-2026',
  'plano-saude-mei-2026',
  'plano-saude-empresarial-2026',
  'plano-saude-coletivo-2026',
  'reajuste-plano-saude-2026',
  'reajuste-ans-2026',
  'plano-saude-cancelamento-2026',
  'portabilidade-plano-saude',
  'plano-saude-cobertura-obrigatoria',
  'rol-procedimentos-ans-2026',
  'plano-saude-carencia-2026',
  'plano-saude-coparticipacao',
  'plano-saude-ambulatorial-2026',
  'plano-saude-hospitalar-2026',
  'plano-saude-referencia-2026',
  'plano-saude-rescisao-emprego',
  'plano-saude-demissao-direitos',
  'extensao-plano-saude-demitido',
  'dependente-plano-saude',
  'plano-saude-doenca-preexistente',
  'plano-saude-idoso-precos',
  'plano-saude-quanto-custa-2026',
  'custo-plano-saude-por-faixa-etaria',
  'vale-saude-2026',

  // ── Operadoras (7 slugs) ────────────────────────────────────────────────
  'plano-saude-unimed-2026',
  'plano-saude-bradesco-2026',
  'plano-saude-amil-2026',
  'plano-saude-sulamerica-2026',
  'plano-saude-hapvida-2026',
  'plano-saude-prevent-senior',
  'melhor-plano-saude-2026',

  // ── Por estado (12 slugs) ───────────────────────────────────────────────
  'plano-saude-sp-2026',
  'plano-saude-rj-2026',
  'plano-saude-mg-2026',
  'plano-saude-rs-2026',
  'plano-saude-pr-2026',
  'plano-saude-sc-2026',
  'plano-saude-df-2026',
  'plano-saude-ba-2026',
  'plano-saude-ce-2026',
  'plano-saude-pe-2026',
  'plano-saude-go-2026',
  'plano-saude-am-2026',

  // ── Saúde preventiva e check-up (25 slugs) ──────────────────────────────
  'check-up-anual-exames',
  'check-up-masculino-40-anos',
  'check-up-feminino-30-anos',
  'check-up-idoso-65-anos',
  'rastreamento-cancer-mama',
  'rastreamento-cancer-colo-utero',
  'rastreamento-cancer-prostata',
  'rastreamento-cancer-pulmao',
  'rastreamento-cancer-intestino',
  'exame-colesterol-quando-fazer',
  'pressao-arterial-valores-normais',
  'diabetes-rastreamento-exames',
  'hemograma-completo-o-que-e',
  'tsh-tireoide-valores-referencia',
  'exame-psa-para-que-serve',
  'papanicolau-quando-fazer',
  'mamografia-quando-comecar',
  'densitometria-ossea-para-que-serve',
  'colonoscopia-quando-fazer',
  'exame-ecg-para-que-serve',
  'ecocardiograma-o-que-e',
  'glicemia-jejum-valores-normais',
  'acido-urico-valores-normais',
  'vitamina-d-deficiencia',
  'ferritina-anemia-exame',

  // ── Calculadoras de saúde (15 slugs) ────────────────────────────────────
  'calculadora-imc-adulto',
  'calculadora-taxa-metabolica-basal',
  'calculadora-frequencia-cardiaca-maxima',
  'calculadora-pressao-arterial',
  'calculadora-custo-plano-saude',
  'calculadora-consumo-agua-diario',
  'calculadora-idade-biologica',
  'calculadora-risco-cardiovascular',
  'calculadora-calorias-diarias',
  'calculadora-peso-ideal',
  'calculadora-gestacao-semanas',
  'calculadora-indice-quadril-cintura',
  'calculadora-gasto-calorico',
  'calculadora-percentual-gordura',
  'calculadora-imc-infantil',

  // ── Direitos do paciente (25 slugs) ─────────────────────────────────────
  'direitos-paciente-sus',
  'direito-segunda-opiniao-medica',
  'prazo-atendimento-plano-saude',
  'recurso-negativa-plano-saude',
  'reclamacao-ans-como-fazer',
  'procedimento-negado-plano-saude',
  'glosa-medica-o-que-e',
  'reembolso-plano-saude',
  'ouvidoria-plano-saude',
  'multa-plano-saude-atraso',
  'plano-saude-pode-cancelar',
  'negativa-cobertura-acao-judicial',
  'autororizacao-previa-plano-saude',
  'guia-consulta-plano-saude',
  'coparticipacao-limite-legal',
  'plano-saude-nao-cobre-o-que',
  'procedimento-experimental-plano',
  'urgencia-cobertura-plano-saude',
  'internacao-plano-saude-direitos',
  'alta-hospitalar-plano-saude',
  'acompanhante-hospitalar-direito',
  'prontuario-medico-direito-acesso',
  'consentimento-informado-paciente',
  'sigilo-medico-o-que-e',
  'erro-medico-o-que-fazer',

  // ── SUS e saúde pública (25 slugs) ──────────────────────────────────────
  'sus-como-funciona',
  'sus-atendimento-especialista',
  'medicamento-sus-lista-2026',
  'cirurgia-sus-prazo-espera',
  'farmacia-popular-2026',
  'programa-saude-familia',
  'vacinas-calendario-2026',
  'ubs-o-que-e',
  'caps-saude-mental-sus',
  'regulacao-sus-como-funciona',
  'prontuario-eletronico-sus',
  'samu-como-funciona',
  'upa-vs-pronto-socorro',
  'transplante-sus-como-funciona',
  'sus-cirurgia-eletiva-fila',
  'sus-atendimento-dentista',
  'cisab-sus-o-que-e',
  'sus-medicamento-alto-custo',
  'sus-gratuito-para-estrangeiros',
  'cartao-sus-como-tirar',
  'suas-diferenca-sus',
  'hemorrede-sus-doacao-sangue',
  'banco-de-leite-sus',
  'sus-saude-indigena',
  'sus-saude-prisional',

  // ── Saúde mental (20 slugs) ──────────────────────────────────────────────
  'cobertura-psicologia-plano-saude',
  'terapia-pelo-plano-saude',
  'crise-saude-mental-brasil-2026',
  'burnout-como-tratar',
  'ansiedade-tratamento-sus',
  'depressao-tratamento-plano',
  'psiquiatra-pelo-plano-saude',
  'terapia-online-plano-saude',
  'saude-mental-trabalho-2026',
  'afastamento-saude-mental-inss',
  'toc-tratamento-plano-saude',
  'bipolaridade-tratamento-sus',
  'esquizofrenia-tratamento-sus',
  'autismo-cobertura-plano-saude',
  'transtorno-alimentar-tratamento',
  'dependencia-quimica-sus',
  'caps-ad-alcool-drogas',
  'cvv-suporte-emocional',
  'psicologia-gratuita-sus',
  'medicamentos-psiquiatricos-sus',

  // ── Saúde por faixa etária (25 slugs) ───────────────────────────────────
  'saude-crianca-0-5-anos',
  'saude-adolescente-plano',
  'saude-mulher-20-anos',
  'saude-mulher-30-anos',
  'saude-mulher-50-anos',
  'saude-homem-30-anos',
  'saude-homem-40-anos',
  'saude-idoso-65-anos',
  'saude-gestante-direitos',
  'saude-gestante-sus',
  'plano-saude-gestante-2026',
  'saude-bebe-primeiros-meses',
  'vacinas-crianca-calendario',
  'saude-adolescente-mental',
  'puberdade-saude-adolescente',
  'menopausa-tratamento-plano',
  'andropausa-tratamento',
  'osteoporose-tratamento-sus',
  'alzheimer-cobertura-plano',
  'parkinson-tratamento-sus',
  'saude-idoso-longevidade',
  'fratura-quadril-idoso-sus',
  'saude-mulher-cancer-ovario',
  'endometriose-plano-saude',
  'infertilidade-cobertura-plano',

  // ── Doenças crônicas e condições comuns (25 slugs) ──────────────────────
  'diabetes-tipo-2-tratamento-sus',
  'diabetes-tipo-1-cobertura-plano',
  'hipertensao-medicamento-gratuito',
  'colesterol-alto-tratamento',
  'obesidade-cirurgia-bariatrica-sus',
  'asma-tratamento-sus',
  'dpoc-tratamento-sus',
  'hipotireoidismo-medicamento-sus',
  'insuficiencia-renal-dialise-sus',
  'cancer-tratamento-sus-2026',
  'cancer-mama-tratamento-plano',
  'cancer-prostata-tratamento',
  'avc-reabilitacao-sus',
  'infarto-tratamento-sus',
  'doenca-de-crohn-plano-saude',
  'artrite-reumatoide-tratamento',
  'lupus-tratamento-sus',
  'esclerose-multipla-tratamento',
  'fibromialgia-tratamento-sus',
  'enxaqueca-tratamento-plano',
  'epilepsia-tratamento-sus',
  'parkinsons-tratamento-sus',
  'alcoolismo-tratamento-sus',
  'tabagismo-tratamento-sus',
  'hiv-aids-tratamento-sus',
]
