// lib/trabalhista/slugs.ts
// ~850 slugs para a seção /trabalhista — INSS, FGTS, Rescisão, CLT, Aposentadoria

export const SLUGS_TRABALHISTA: string[] = [

  // ── INSS — Páginas gerais (13 slugs) ─────────────────────────────────────
  'tabela-inss-2026',
  'tabela-inss-2025',
  'calculo-inss-clt',
  'calculo-inss-autonomo',
  'calculo-inss-mei',
  'calculo-inss-domestica',
  'calculo-inss-facultativo',
  'aliquota-inss-2026',
  'teto-inss-2026',
  'isencao-inss',
  'inss-aposentadoria-2026',
  'inss-por-faixa-salarial',
  'inss-salario-minimo-2026',

  // ── INSS por salário (16 slugs) ───────────────────────────────────────────
  'inss-salario-1518',
  'inss-salario-2000',
  'inss-salario-2500',
  'inss-salario-3000',
  'inss-salario-3500',
  'inss-salario-4000',
  'inss-salario-4500',
  'inss-salario-5000',
  'inss-salario-6000',
  'inss-salario-7000',
  'inss-salario-8000',
  'inss-salario-9000',
  'inss-salario-10000',
  'inss-salario-12000',
  'inss-salario-15000',
  'inss-salario-20000',

  // ── INSS — Tópicos detalhados (20 slugs) ─────────────────────────────────
  'inss-progressivo-como-funciona',
  'inss-empregado-domestico-2026',
  'inss-contribuicao-individual',
  'inss-segurado-especial',
  'inss-segurado-facultativo-2026',
  'inss-mei-como-pagar',
  'inss-autônomo-carnê-2026',
  'inss-retroativo-como-calcular',
  'inss-desconto-maximo-2026',
  'inss-base-de-calculo',
  'inss-complementar-saude',
  'inss-rescisao-desconto',
  'inss-13-salario-desconto',
  'inss-ferias-desconto',
  'inss-horas-extras-desconto',
  'inss-pj-como-contribuir',
  'inss-dois-empregos',
  'inss-periodo-de-carencia',
  'contribuicao-minima-inss-2026',
  'codigo-gps-inss-2026',

  // ── FGTS — Geral (14 slugs) ───────────────────────────────────────────────
  'calculo-fgts-2026',
  'tabela-fgts-2026',
  'fgts-demissao-sem-justa-causa',
  'fgts-demissao-justa-causa',
  'fgts-rescisao-acordo',
  'saque-fgts-2026',
  'fgts-aniversario-2026',
  'rendimento-fgts-2026',
  'fgts-por-tempo-de-servico',
  'quando-sacar-fgts',
  'fgts-doenca-grave',
  'fgts-aposentadoria',
  'fgts-casa-propria',
  'multa-fgts-40-porcento',

  // ── FGTS por salário (6 slugs) ────────────────────────────────────────────
  'fgts-salario-1518',
  'fgts-salario-2000',
  'fgts-salario-3000',
  'fgts-salario-5000',
  'fgts-salario-7000',
  'fgts-salario-10000',

  // ── FGTS — Tópicos detalhados (20 slugs) ─────────────────────────────────
  'fgts-o-que-e',
  'fgts-como-funciona',
  'fgts-quem-tem-direito',
  'fgts-extrato-como-consultar',
  'fgts-caixa-como-acessar',
  'fgts-app-fgts-como-usar',
  'fgts-multa-rescisoria-calculo',
  'fgts-acordo-20-porcento',
  'fgts-portabilidade',
  'fgts-mei-tem-direito',
  'fgts-autonomo-tem-direito',
  'fgts-pj-tem-direito',
  'fgts-prazo-deposito-empregador',
  'fgts-deposito-atrasado-multa',
  'fgts-rescisao-prazo-pagamento',
  'fgts-parcelamento-saque',
  'fgts-inativo-como-sacar',
  'fgts-por-tempo-de-servico-5-anos',
  'fgts-por-tempo-de-servico-10-anos',
  'fgts-complemento-aposentadoria',

  // ── Rescisão — Geral (14 slugs) ───────────────────────────────────────────
  'calculo-rescisao-2026',
  'rescisao-sem-justa-causa-2026',
  'rescisao-justa-causa-2026',
  'rescisao-pedido-demissao-2026',
  'rescisao-acordo-trabalhista',
  'aviso-previo-2026',
  'aviso-previo-indenizado',
  'aviso-previo-trabalhado',
  'calculo-13-salario-2026',
  'calculo-ferias-2026',
  'ferias-mais-um-terco',
  'ferias-vencidas',
  'multa-rescisoria-2026',
  'prazo-pagamento-rescisao',

  // ── Rescisão por tempo de serviço (10 slugs) ─────────────────────────────
  'rescisao-1-ano',
  'rescisao-2-anos',
  'rescisao-3-anos',
  'rescisao-4-anos',
  'rescisao-5-anos',
  'rescisao-6-anos',
  'rescisao-7-anos',
  'rescisao-8-anos',
  'rescisao-9-anos',
  'rescisao-10-anos',

  // ── Rescisão por salário (10 slugs) ──────────────────────────────────────
  'rescisao-salario-1518',
  'rescisao-salario-2000',
  'rescisao-salario-2500',
  'rescisao-salario-3000',
  'rescisao-salario-3500',
  'rescisao-salario-4000',
  'rescisao-salario-5000',
  'rescisao-salario-6000',
  'rescisao-salario-8000',
  'rescisao-salario-10000',

  // ── Rescisão — Tópicos detalhados (25 slugs) ─────────────────────────────
  'rescisao-documentos-necessarios',
  'rescisao-como-calcular-passo-a-passo',
  'rescisao-simulador-online',
  'rescisao-verbas-indenizatorias',
  'rescisao-verbas-tributaveis',
  'rescisao-irrf-sobre-rescisao',
  'rescisao-inss-sobre-rescisao',
  'rescisao-acordo-mutuo-como-funciona',
  'rescisao-sem-justa-causa-direitos',
  'rescisao-justa-causa-o-que-perco',
  'rescisao-pedido-demissao-o-que-perco',
  'rescisao-gravidez-demissao',
  'rescisao-estabilidade-provisoria',
  'rescisao-doenca-afastamento',
  'rescisao-prazo-homologacao',
  'rescisao-homologacao-sindicato',
  'rescisao-complementar-empresa',
  'rescisao-contrato-experiencia',
  'rescisao-contrato-determinado',
  'rescisao-aviso-previo-calculo',
  'rescisao-ferias-vencidas-calculo',
  'rescisao-13-salario-proporcional',
  'rescisao-saldo-salario',
  'rescisao-plano-de-saude-demissao',
  'rescisao-seguro-desemprego-calculo',

  // ── Salário Mínimo / CLT — Geral (18 slugs) ──────────────────────────────
  'salario-minimo-2026',
  'salario-minimo-hora-2026',
  'salario-minimo-dia-2026',
  'piso-salarial-2026',
  'reajuste-salario-minimo-2026',
  'projecao-salario-minimo-2027',
  'clt-2026',
  'direitos-clt-2026',
  'horas-extras-clt',
  'banco-de-horas-clt',
  'adicional-noturno-2026',
  'adicional-periculosidade-2026',
  'adicional-insalubridade-2026',
  'vale-transporte-2026',
  'vale-refeicao-2026',
  'plano-de-saude-clt',
  'ponto-facultativo-2026',
  'ferias-coletivas-2026',

  // ── CLT — Tópicos detalhados (30 slugs) ──────────────────────────────────
  'jornada-de-trabalho-clt',
  'hora-extra-limite-clt',
  'hora-extra-como-calcular',
  'adicional-noturno-como-calcular',
  'adicional-insalubridade-como-calcular',
  'adicional-periculosidade-como-calcular',
  'banco-de-horas-como-funciona',
  'banco-de-horas-acordo',
  'vale-transporte-como-funciona',
  'vale-refeicao-como-funciona',
  'ferias-como-tirar-2026',
  'ferias-abono-pecuniario',
  'licenca-maternidade-2026',
  'licenca-paternidade-2026',
  'licenca-medica-clt',
  'estabilidade-gestante-clt',
  'estabilidade-acidentado-clt',
  'contrato-experiencia-como-funciona',
  'trabalho-remoto-clt-2026',
  'home-office-ajuda-de-custo',
  'clt-vs-pj-calculo-2026',
  'clt-vs-mei-calculo-2026',
  'clt-vs-autonomo-calculo-2026',
  'piso-salarial-por-categoria',
  'salario-piso-engenharia',
  'salario-piso-enfermagem',
  'salario-piso-professores',
  'salario-piso-vendedor',
  'salario-piso-cuidador-idoso',
  'salario-piso-auxiliar-administrativo',

  // ── Salário Líquido CLT por valor (10 slugs) ─────────────────────────────
  'salario-liquido-clt-2000',
  'salario-liquido-clt-3000',
  'salario-liquido-clt-4000',
  'salario-liquido-clt-5000',
  'salario-liquido-clt-6000',
  'salario-liquido-clt-8000',
  'salario-liquido-clt-10000',
  'salario-liquido-clt-12000',
  'salario-liquido-clt-15000',
  'salario-liquido-clt-20000',

  // ── Aposentadoria (15 + 6 slugs) ─────────────────────────────────────────
  'calculo-aposentadoria-2026',
  'aposentadoria-por-tempo-contribuicao',
  'aposentadoria-por-idade-2026',
  'aposentadoria-especial-2026',
  'aposentadoria-professores-2026',
  'beneficio-de-prestacao-continuada',
  'teto-aposentadoria-inss-2026',
  'quando-me-aposentar',
  'pontos-aposentadoria-2026',
  'aposentadoria-mulher-2026',
  'aposentadoria-homem-2026',
  'aposentadoria-rural-2026',
  'aposentadoria-invalidez-2026',
  'aposentadoria-progressiva',
  'aposentadoria-antecipada-2026',

  // ── Aposentadoria por anos de contribuição (6 slugs) ─────────────────────
  'aposentadoria-15-anos-contribuicao',
  'aposentadoria-20-anos-contribuicao',
  'aposentadoria-25-anos-contribuicao',
  'aposentadoria-30-anos-contribuicao',
  'aposentadoria-35-anos-contribuicao',
  'aposentadoria-40-anos-contribuicao',

  // ── Aposentadoria — Tópicos detalhados (20 slugs) ────────────────────────
  'como-se-aposentar-2026',
  'quanto-vou-receber-aposentadoria',
  'fator-previdenciario-2026',
  'regra-de-transicao-aposentadoria',
  'pedido-aposentadoria-inss-online',
  'aposentadoria-por-pontos-2026',
  'aposentadoria-sem-contribuicao',
  'aposentadoria-com-doenca-grave',
  'aposentadoria-por-incapacidade',
  'pensao-por-morte-inss-2026',
  'auxilio-doenca-inss-2026',
  'auxilio-acidente-inss-2026',
  'bpc-loas-2026',
  'salario-maternidade-inss-2026',
  'contribuicao-inss-para-se-aposentar',
  'tempo-de-contribuicao-para-aposentar',
  'aposentadoria-pj-autonomo',
  'aposentadoria-microempreendedor',
  'recalculo-aposentadoria',
  'revisao-da-vida-toda',

  // ── Guias gerais trabalhistas (50 slugs) ─────────────────────────────────
  'como-calcular-13-salario',
  'como-calcular-ferias-proporcionais',
  'como-calcular-horas-extras',
  'diferenca-clt-pj',
  'diferenca-clt-mei',
  'vale-a-pena-ser-pj',
  'vale-a-pena-ser-mei',
  'contrato-trabalho-pj-riscos',
  'trabalhador-autonomo-direitos',
  'empregado-domestico-direitos',
  'trabalho-remoto-direitos',
  'horas-extras-limite-legal',
  'negociar-salario-dicas',
  'demissao-sem-justa-causa-o-que-fazer',
  'pedir-demissao-certo-momento',
  'seguro-desemprego-2026',
  'seguro-desemprego-como-solicitar',
  'seguro-desemprego-parcelas-2026',
  'carteira-de-trabalho-digital',
  'ctps-digital-como-usar',
  'registro-empregado-prazo',
  'aviso-previo-como-funciona',
  'salario-13-quando-pagar',
  'ferias-quando-tirar',
  'ferias-proporcionais-calcular',
  'horas-extras-banco-de-horas-diferenca',
  'trabalho-noturno-adicional',
  'trabalho-aos-domingos-clt',
  'trabalho-em-feriado-clt',
  'teletrabalho-clt-regras',
  'estagio-direitos-2026',
  'jovem-aprendiz-direitos',
  'mei-contrato-trabalho',
  'pessoa-juridica-contrato-riscos',
  'pejotizacao-o-que-e',
  'terceirizacao-clt-2026',
  'cooperativa-trabalho-direitos',
  'trabalho-temporario-direitos',
  'trabalho-parcial-clt',
  'trabalho-intermitente-clt',
  'salario-familia-2026',
  'auxilio-educacao-clt',
  'plano-odontologico-clt',
  'previdencia-privada-clt',
  'participacao-lucros-ppr',
  'premio-clt-tributacao',
  'comissao-clt-como-calcular',
  'insalubridade-grau-maximo',
  'periculosidade-atividades',
  'acidente-trabalho-direitos',

  // ── Por profissão (20 slugs) ─────────────────────────────────────────────
  'inss-professor-2026',
  'inss-medico-autonomo',
  'inss-advogado-autonomo',
  'inss-engenheiro-autonomo',
  'inss-psicologo-autonomo',
  'inss-contador-autonomo',
  'rescisao-professor-clt',
  'rescisao-enfermeiro-clt',
  'rescisao-motorista-clt',
  'rescisao-vendedor-clt',
  'fgts-domestica-2026',
  'fgts-microempresa',
  'clt-enfermagem-2026',
  'clt-ti-programador-2026',
  'clt-saude-2026',
  'clt-comercio-2026',
  'clt-logistica-2026',
  'clt-construcao-civil-2026',
  'clt-agronegocio-2026',
  'clt-educacao-2026',

  // ── Comparativos e guias avançados (20 slugs) ────────────────────────────
  'quanto-custa-contratar-clt',
  'encargos-trabalhistas-empregador',
  'encargos-clt-percentual',
  'custo-real-empregado-clt',
  'pro-labore-vs-salario',
  'lucros-dividendos-vs-salario-clt',
  'reforma-trabalhista-2026',
  'nrfgt-rescisao-2026',
  'dissidio-coletivo-2026',
  'convencao-coletiva-trabalho',
  'acordo-coletivo-vs-convencao',
  'jornada-12x36-como-funciona',
  'jornada-6x1-calculo',
  'horas-in-itinere-2026',
  'sobreaviso-como-funciona',
  'prontidao-como-funciona',
  'adicional-transferencia-clt',
  'diaria-viagem-tributacao',
  'ajuda-de-custo-tributacao',
  'stock-options-tributacao',

  // ── Dúvidas comuns (25 slugs) ─────────────────────────────────────────────
  'posso-trabalhar-doente-clt',
  'pode-demitir-gente-doente',
  'o-que-e-justa-causa',
  'o-que-e-rescisao-indireta',
  'o-que-e-estabilidade-provisoria',
  'quantos-dias-ferias-tenho-direito',
  'posso-vender-ferias-clt',
  'quando-recebo-13-salario',
  'fgts-rende-quanto-por-mes',
  'inss-desconto-bruto-ou-liquido',
  'vale-transporte-descontado-salario',
  'posso-recusar-hora-extra',
  'salario-minimo-regional-2026',
  'anuenio-quinquenio-diferenca',
  'piso-categorias-obrigatorio',
  'contrato-verbal-tem-validade',
  'pode-demitir-grávida',
  'acidente-trabalho-seguro',
  'equiparação-salarial-como-pedir',
  'assédio-moral-o-que-fazer',
  'como-regularizar-ctps',
  'trabalho-sem-registro-direitos',
  'rescisao-indireta-como-fazer',
  'mediacao-clt-como-funciona',
  'reclamacao-trabalhista-prazo',

  // ── INSS por salário — valores adicionais (20 slugs) ──────────────────────
  'inss-salario-1600',
  'inss-salario-1700',
  'inss-salario-1800',
  'inss-salario-1900',
  'inss-salario-2100',
  'inss-salario-2200',
  'inss-salario-2300',
  'inss-salario-2400',
  'inss-salario-2600',
  'inss-salario-2700',
  'inss-salario-2800',
  'inss-salario-2900',
  'inss-salario-3200',
  'inss-salario-3500',
  'inss-salario-4500',
  'inss-salario-5500',
  'inss-salario-6500',
  'inss-salario-7000',
  'inss-salario-7500',
  'inss-salario-7786',

  // ── Rescisão por salário — valores adicionais (10 slugs) ─────────────────
  'rescisao-salario-1700',
  'rescisao-salario-1900',
  'rescisao-salario-2200',
  'rescisao-salario-2700',
  'rescisao-salario-4500',
  'rescisao-salario-7000',
  'rescisao-salario-9000',
  'rescisao-salario-12000',
  'rescisao-salario-15000',
  'rescisao-salario-20000',

  // ── FGTS por salário — valores adicionais (10 slugs) ─────────────────────
  'fgts-salario-1700',
  'fgts-salario-2500',
  'fgts-salario-4000',
  'fgts-salario-4500',
  'fgts-salario-6000',
  'fgts-salario-8000',
  'fgts-salario-9000',
  'fgts-salario-12000',
  'fgts-salario-15000',
  'fgts-salario-20000',

  // ── Salário líquido — valores adicionais (10 slugs) ──────────────────────
  'salario-liquido-clt-1518',
  'salario-liquido-clt-1700',
  'salario-liquido-clt-2500',
  'salario-liquido-clt-7000',
  'salario-liquido-clt-9000',
  'salario-liquido-clt-25000',
  'salario-liquido-clt-30000',
  'salario-liquido-clt-40000',
  'salario-liquido-clt-50000',
  'salario-liquido-clt-100000',

  // ── Rescisão por tempo — anos adicionais (10 slugs) ──────────────────────
  'rescisao-11-anos',
  'rescisao-12-anos',
  'rescisao-15-anos',
  'rescisao-18-anos',
  'rescisao-20-anos',
  'rescisao-25-anos',
  'rescisao-30-anos',
  'rescisao-6-meses',
  'rescisao-3-meses',
  'rescisao-1-mes',

  // ── Aposentadoria por anos — valores adicionais (10 slugs) ───────────────
  'aposentadoria-10-anos-contribuicao',
  'aposentadoria-12-anos-contribuicao',
  'aposentadoria-18-anos-contribuicao',
  'aposentadoria-22-anos-contribuicao',
  'aposentadoria-28-anos-contribuicao',
  'aposentadoria-32-anos-contribuicao',
  'aposentadoria-37-anos-contribuicao',
  'aposentadoria-38-anos-contribuicao',
  'aposentadoria-42-anos-contribuicao',
  'aposentadoria-45-anos-contribuicao',

  // ── Guias específicos por setor (40 slugs) ────────────────────────────────
  'holerite-como-ler',
  'holerite-o-que-e-cada-desconto',
  'contracheque-como-entender',
  'ppd-como-funciona',
  'pcd-contratacao-clt',
  'aprendiz-contrato-clt',
  'estagiario-contrato-clt',
  'terceirizado-direitos-clt',
  'trabalhador-intermitente-2026',
  'parcial-clt-jornada-reduzida',
  'teletrabalho-equipamentos-2026',
  'home-office-despesas-2026',
  'salario-confidencial-e-permitido',
  'recessos-e-feriados-2026',
  'feriado-nacional-2026',
  'carnaval-ponto-facultativo-2026',
  'semana-santa-trabalho-clt',
  'natal-dia-do-trabalhador-clt',
  'dia-do-trabalhador-2026',
  'recesso-fim-de-ano-clt',
  'banco-horas-negativo',
  'hora-extra-noturna-calculo',
  'hora-extra-domingo-calculo',
  'hora-extra-feriado-calculo',
  'adicional-insalubridade-grau-minimo',
  'adicional-insalubridade-grau-medio',
  'adicional-noturno-quem-tem-direito',
  'periculosidade-quem-tem-direito',
  'jornada-12x36-hora-extra',
  'jornada-4x3-calculo',
  'jornada-6x1-proibicao',
  'semana-4-dias-brasil',
  'contrato-trabalho-intermitente',
  'contrato-trabalho-prazo-determinado',
  'contrato-verde-amarelo-2026',
  'carteira-digital-como-assinar',
  'empregado-hibrido-clt',
  'trabalho-presencial-obrigatorio',
  'recusa-home-office-clt',
  'trabalho-exterior-clt-brasileiro',

  // ── Tributação e benefícios avançados (30 slugs) ─────────────────────────
  'irrf-sobre-13-salario',
  'irrf-sobre-ferias',
  'irrf-sobre-rescisao',
  'irrf-sobre-participacao-lucros',
  'irrf-sobre-hora-extra',
  'deducao-inss-ir-2026',
  'imposto-sobre-indenizacao',
  'tributacao-aviso-previo',
  'tributacao-ferias-indenizadas',
  'tributacao-pdv',
  'deducao-previdencia-privada-salario',
  'pgbl-no-salario-clt',
  'vgbl-no-salario-clt',
  'plano-saude-desconto-salario',
  'previdencia-empresa-como-funciona',
  'ppr-calculo-tributacao',
  'participacao-lucros-prazo-pagamento',
  'bonus-tributacao-clt',
  'comissao-calculo-inss-irrf',
  'gorjeta-clt-tributacao',
  'quebra-de-caixa-clt',
  'representante-comercial-clt',
  'autonomo-rir-como-declarar',
  'rpa-recibo-pagamento-autonomo',
  'nota-fiscal-prestacao-servico',
  'simples-nacional-pro-labore',
  'pro-labore-inss-como-calcular',
  'socio-clt-pode-ser-empregado',
  'dividend-clawback-tributacao',
  'juros-capital-proprio-tributacao',

  // ── Saúde e segurança no trabalho (20 slugs) ─────────────────────────────
  'ppra-o-que-e',
  'pcmso-o-que-e',
  'cipa-o-que-e',
  'nr-12-seguranca-maquinas',
  'nr-17-ergonomia',
  'nr-35-trabalho-altura',
  'epi-obrigatoriedade-clt',
  'cao-cao-acidente-trabalho',
  'cat-comunicacao-acidente',
  'nexo-causal-acidente',
  'auxilio-acidente-inss-valor',
  'readaptacao-profissional-inss',
  'doenca-ocupacional-direitos',
  'burnout-reconhecimento-clt-2026',
  'afastamento-saude-mental-2026',
  'licenca-medica-prazo-maximo',
  'alta-medica-retorno-trabalho',
  'demissao-pos-acidente',
  'indenizacao-acidente-trabalho',
  'seguro-acidente-trabalho-sat',

  // ── Contratos especiais e regimes (20 slugs) ─────────────────────────────
  'microempreendedor-pode-ser-clt',
  'mei-e-clt-ao-mesmo-tempo',
  'servidor-publico-e-clt-acumulo',
  'aposentado-pode-trabalhar-clt',
  'pensionista-pode-trabalhar-clt',
  'estrangeiro-trabalhar-brasil-clt',
  'contrato-minimo-clt',
  'salario-minimo-hora-clt',
  'jornada-parcial-20-horas',
  'jornada-parcial-30-horas',
  'regime-4x3-ilegal',
  'escala-5x1-clt',
  'escala-6x1-clt-validade',
  'plantao-medico-clt',
  'plantao-enfermagem-12x36',
  'professor-horas-aula-clt',
  'professor-hora-extra-clt',
  'professor-ferias-clt',
  'professor-abono-clt',
  'professor-salario-minimo-2026',

  // ── INSS — casos específicos adicionais (20 slugs) ───────────────────────
  'inss-quando-para-de-descontar',
  'inss-salario-teto-maximo',
  'inss-maximo-mensal-2026',
  'inss-calculo-manual-passo-a-passo',
  'inss-carne-2026',
  'gps-inss-como-pagar',
  'darf-inss-autonomo',
  'inss-em-atraso-como-regularizar',
  'inss-retroativo-limite',
  'inss-rural-como-funciona',
  'contribuicao-inss-voluntaria',
  'inss-deficiente-fisico',
  'inss-menor-aprendiz',
  'inss-estagiario',
  'inss-terceirizado',
  'inss-trabalho-temporario',
  'inss-intermitente',
  'inss-parcial',
  'inss-servidor-publico-federal',
  'inss-servidor-estadual',

  // ── FGTS — casos específicos adicionais (20 slugs) ───────────────────────
  'fgts-como-abrir-conta',
  'fgts-beneficiario-especial',
  'fgts-saldo-negativo-possivel',
  'fgts-transferencia-contas',
  'fgts-anterior-1988',
  'fgts-inscricao-individual',
  'fgts-multa-acordo-verde-amarelo',
  'fgts-desconto-empregado-domestico',
  'fgts-diferenca-entre-contas',
  'fgts-conta-inativa-o-que-e',
  'fgts-conta-ativa-o-que-e',
  'fgts-imposto-sobre-saque',
  'fgts-heranca',
  'fgts-falecimento-como-sacar',
  'fgts-desemprego-como-sacar',
  'fgts-doenca-cronica-saque',
  'fgts-nao-depositado-o-que-fazer',
  'fgts-empregador-atrasou-multa',
  'fgts-fiscalizacao-ministerio',
  'fgts-reclamar-na-justica',

  // ── Seguro Desemprego — guias (15 slugs) ──────────────────────────────────
  'seguro-desemprego-como-calcular',
  'seguro-desemprego-quantas-parcelas',
  'seguro-desemprego-valor-2026',
  'seguro-desemprego-prazo-solicitar',
  'seguro-desemprego-documentos',
  'seguro-desemprego-caged',
  'seguro-desemprego-emprego-novo',
  'seguro-desemprego-trabalhador-domestico',
  'seguro-desemprego-pescador',
  'seguro-desemprego-resgatado',
  'seguro-desemprego-intermitente',
  'seguro-desemprego-por-quantas-vezes',
  'seguro-desemprego-recusou-emprego',
  'seguro-desemprego-indeferido',
  'seguro-desemprego-recurso',

  // ── Contratação e RH — guias (20 slugs) ─────────────────────────────────
  'como-contratar-funcionario-2026',
  'registro-empregado-documentos',
  'exame-admissional-obrigatorio',
  'integracao-funcionario-clt',
  'experiencia-90-dias-prorrogacao',
  'salario-negociacao-como-pedir-aumento',
  'proximo-aumento-clt-quando',
  'dissidio-categoria-o-que-e',
  'piso-salarial-por-estado-2026',
  'piso-salarial-sp-2026',
  'piso-salarial-rj-2026',
  'piso-salarial-mg-2026',
  'piso-salarial-rs-2026',
  'piso-salarial-pr-2026',
  'piso-salarial-sc-2026',
  'piso-salarial-ba-2026',
  'rescisao-em-lote-empresa',
  'demissao-em-massa-clt',
  'layoff-suspensao-contrato',
  'reducao-salario-acordo-individual',

  // ── Financeiro e planejamento (20 slugs) ─────────────────────────────────
  'simulador-rescisao-2026',
  'simulador-aposentadoria-2026',
  'simulador-salario-liquido-clt',
  'planejamento-demissao-voluntaria',
  'quando-pedir-demissao-calculo',
  'negociar-rescisao-dicas',
  'acordo-rescisao-vale-a-pena',
  'pdv-plano-demissao-voluntaria',
  'indenizacao-adicional-pdv',
  'comparativo-emprego-proposta',
  'aumento-salario-percentual',
  'reajuste-inflacao-salario',
  'dissidio-percentual-2026',
  'negociar-beneficios-clt',
  'vale-refeicao-vs-vale-alimentacao',
  'plano-saude-individual-vs-clt',
  'previdencia-privada-clt-compensacao',
  'custo-oportunidade-clt-vs-pj',
  'imposto-salario-alta-renda',
  'planejamento-tributario-pessoa-fisica',

  // ── Trabalhistas por região e setor (20 slugs) ────────────────────────────
  'piso-salarial-metalurgico-2026',
  'piso-salarial-bancario-2026',
  'piso-salarial-comerciario-2026',
  'piso-salarial-motorista-2026',
  'piso-salarial-farmaceutico-2026',
  'piso-salarial-nutricionista-2026',
  'piso-salarial-fisioterapeuta-2026',
  'piso-salarial-assistente-social-2026',
  'piso-salarial-seguranca-2026',
  'piso-salarial-garcom-2026',
  'piso-salarial-porteiro-2026',
  'piso-salarial-zelador-2026',
  'piso-salarial-recepcionista-2026',
  'piso-salarial-telemarketing-2026',
  'piso-salarial-ti-2026',
  'piso-salarial-desenvolvedor-2026',
  'piso-salarial-contador-2026',
  'piso-salarial-advogado-2026',
  'piso-salarial-medico-2026',
  'piso-salarial-dentista-2026',

  // ── Cálculos práticos e exemplos (20 slugs) ───────────────────────────────
  'exemplo-holerite-salario-2000',
  'exemplo-holerite-salario-3000',
  'exemplo-holerite-salario-5000',
  'exemplo-holerite-salario-8000',
  'exemplo-holerite-salario-10000',
  'calculo-salario-hora-clt',
  'calculo-salario-dia-clt',
  'calculo-salario-semana-clt',
  'calculo-13-salario-proporcional',
  'calculo-ferias-vencidas',
  'calculo-ferias-proporcionais-meses',
  'calculo-aviso-previo-anos',
  'calculo-multa-atraso-rescisao',
  'calculo-inss-sobre-13',
  'calculo-inss-sobre-ferias',
  'calculo-fgts-mensal',
  'calculo-fgts-acumulado',
  'calculo-rescisao-completo',
  'calculo-custo-funcionario-clt',
  'calculo-encargos-trabalhistas',

  // ── Direito do trabalho aplicado (20 slugs) ───────────────────────────────
  'reclamacao-trabalhista-como-entrar',
  'jus-postulandi-trabalhista',
  'prescricao-trabalhista-prazo',
  'acordo-trabalhista-homologacao',
  'conciliacao-cct-jt',
  'audiencia-trabalhista-como-funciona',
  'prova-jornada-trabalho',
  'horas-extras-como-provar',
  'depoimento-pessoal-audiencia',
  'dano-moral-trabalhista',
  'assedio-sexual-clt',
  'assedio-moral-tipos',
  'discriminacao-trabalhista',
  'reintegracao-ao-emprego',
  'multa-173-clt',
  'multa-477-clt',
  'multa-467-clt',
  'horas-extras-nao-pagas-prazo',
  'verbas-nao-pagas-juros',
  'recurso-ordinario-tst',

  // ── INSS por salário — faixa fina (30 slugs) ──────────────────────────────
  'inss-salario-1520',
  'inss-salario-1550',
  'inss-salario-1600',
  'inss-salario-1650',
  'inss-salario-2050',
  'inss-salario-2150',
  'inss-salario-2250',
  'inss-salario-2350',
  'inss-salario-2450',
  'inss-salario-2550',
  'inss-salario-2650',
  'inss-salario-2750',
  'inss-salario-2850',
  'inss-salario-2950',
  'inss-salario-3100',
  'inss-salario-3300',
  'inss-salario-3600',
  'inss-salario-3700',
  'inss-salario-3800',
  'inss-salario-3900',
  'inss-salario-4100',
  'inss-salario-4200',
  'inss-salario-4300',
  'inss-salario-4400',
  'inss-salario-4600',
  'inss-salario-4700',
  'inss-salario-4800',
  'inss-salario-4900',
  'inss-salario-5200',
  'inss-salario-5500',

  // ── FGTS por meses acumulado (10 slugs) ──────────────────────────────────
  'fgts-acumulado-6-meses',
  'fgts-acumulado-1-ano',
  'fgts-acumulado-2-anos',
  'fgts-acumulado-3-anos',
  'fgts-acumulado-5-anos',
  'fgts-acumulado-10-anos',
  'fgts-acumulado-15-anos',
  'fgts-acumulado-20-anos',
  'fgts-acumulado-25-anos',
  'fgts-acumulado-30-anos',

  // ── Rescisão — variantes (10 slugs) ──────────────────────────────────────
  'rescisao-6-anos',
  'rescisao-7-anos',
  'rescisao-8-anos',
  'rescisao-9-anos',
  'rescisao-14-anos',
  'rescisao-16-anos',
  'rescisao-17-anos',
  'rescisao-19-anos',
  'rescisao-22-anos',
  'rescisao-23-anos',

  // ── Salário líquido por cargo/profissão (20 slugs) ────────────────────────
  'salario-liquido-medico-clt',
  'salario-liquido-enfermeiro-clt',
  'salario-liquido-advogado-clt',
  'salario-liquido-engenheiro-clt',
  'salario-liquido-professor-clt',
  'salario-liquido-programador-clt',
  'salario-liquido-contador-clt',
  'salario-liquido-administrador-clt',
  'salario-liquido-psicologo-clt',
  'salario-liquido-nutricionista-clt',
  'salario-liquido-fisioterapeuta-clt',
  'salario-liquido-farmaceutico-clt',
  'salario-liquido-arquiteto-clt',
  'salario-liquido-assistente-social-clt',
  'salario-liquido-assistente-administrativo-clt',
  'salario-liquido-analista-rh-clt',
  'salario-liquido-gerente-clt',
  'salario-liquido-diretor-clt',
  'salario-liquido-ceo-clt',
  'salario-liquido-estagiario-clt',

  // ── Guias comparativos adicionais (25 slugs) ──────────────────────────────
  'aumentar-salario-negociacao',
  'bonus-anual-clt',
  'decimo-quarto-salario-existe',
  'ppl-participacao-lucros-resultados',
  'opcao-compra-acoes-startup',
  'vale-combustivel-clt',
  'vale-cultura-clt',
  'plano-dental-clt',
  'seguro-de-vida-clt',
  'previdencia-privada-empresa',
  'plano-saude-familiar-clt',
  'day-off-aniversario-clt',
  'licenca-remota-clt',
  'auxilio-creche-clt',
  'beneficio-educacao-clt',
  'reembolso-home-office',
  'celular-corporativo-tributacao',
  'carro-corporativo-tributacao',
  'notebook-corporativo-propriedade',
  'moradia-fornecida-empresa',
  'passagens-viagem-clt',
  'diarias-viagem-limite-tributacao',
  'ajuda-mudanca-clt',
  'beneficio-alimentacao-x-refeicao',
  'teletransporte-beneficio-clt',

  // ── Últimos slugs para completar 800+ ────────────────────────────────────
  'rescisao-justa-causa-o-que-perder',
  'rescisao-indireta-como-provar',
  'estabilidade-sindical-clt',
  'estabilidade-cipa-clt',
  'membro-cipa-pode-demitir',
  'gravidez-estabilidade-prazo',
  'inss-salario-5800',
  'inss-salario-6200',
  'inss-salario-6800',
  'inss-salario-7200',
  'fgts-salario-2200',
  'fgts-salario-3500',
  'rescisao-salario-2800',
  'aposentadoria-especial-25-anos',
  'aposentadoria-especial-20-anos',
]

// ─── Detecção de tipo de slug ─────────────────────────────────────────────────

export type TipoSlug =
  | 'inss-salario'
  | 'inss-geral'
  | 'fgts-salario'
  | 'fgts-geral'
  | 'rescisao-anos'
  | 'rescisao-salario'
  | 'rescisao-geral'
  | 'salario-liquido-clt'
  | 'salario-minimo'
  | 'clt-geral'
  | 'aposentadoria-anos'
  | 'aposentadoria-geral'
  | 'guia-geral'

export function detectarTipo(slug: string): TipoSlug {
  // Padrões específicos por salário/anos (mais restritos, testados primeiro)
  if (/^inss-salario-\d+$/.test(slug)) return 'inss-salario'
  if (/^fgts-salario-\d+$/.test(slug)) return 'fgts-salario'
  if (/^rescisao-\d+-anos?$/.test(slug)) return 'rescisao-anos'
  if (/^rescisao-salario-\d+$/.test(slug)) return 'rescisao-salario'
  if (/^salario-liquido-clt-\d+$/.test(slug)) return 'salario-liquido-clt'
  if (/^aposentadoria-\d+-anos(-contribuicao)?$/.test(slug)) return 'aposentadoria-anos'
  // Salário líquido por profissão → usa guia-geral (gerarGuiaGeral)
  if (/^salario-liquido-\w+-clt$/.test(slug)) return 'clt-geral'
  // FGTS acumulado por período → fgts-geral
  if (/^fgts-acumulado-/.test(slug)) return 'fgts-geral'
  // Rescisão por meses → rescisao-geral
  if (/^rescisao-\d+-meses?$/.test(slug)) return 'rescisao-geral'
  // INSS
  if (slug.startsWith('inss-') || slug.startsWith('tabela-inss') || slug.startsWith('aliquota-inss') || slug.startsWith('teto-inss') || slug.startsWith('calculo-inss') || slug.startsWith('contribuicao-inss') || slug.startsWith('codigo-gps') || slug.startsWith('gps-inss') || slug.startsWith('darf-inss') || slug.startsWith('gps-')) return 'inss-geral'
  // FGTS
  if (slug.startsWith('fgts-') || slug.startsWith('calculo-fgts') || slug.startsWith('tabela-fgts') || slug.startsWith('multa-fgts') || slug.startsWith('saque-fgts') || slug.startsWith('rendimento-fgts')) return 'fgts-geral'
  // Rescisão / verbas
  if (slug.startsWith('rescisao-') || slug.startsWith('calculo-rescisao') || slug.startsWith('aviso-previo') || slug.startsWith('multa-rescisoria') || slug.startsWith('prazo-pagamento-rescisao') || slug.startsWith('ferias-') || slug.startsWith('calculo-ferias') || slug.startsWith('calculo-13') || slug.startsWith('como-calcular-13') || slug.startsWith('como-calcular-ferias') || slug.startsWith('verbas-')) return 'rescisao-geral'
  // Salário mínimo / piso
  if (slug.startsWith('salario-minimo') || slug.startsWith('piso-salarial') || slug.startsWith('reajuste-salario') || slug.startsWith('projecao-salario')) return 'salario-minimo'
  // Aposentadoria / INSS benefícios
  if (slug.startsWith('aposentadoria-') || slug.startsWith('calculo-aposentadoria') || slug.startsWith('pontos-aposentadoria') || slug.startsWith('teto-aposentadoria') || slug.startsWith('beneficio-de-prestacao') || slug.startsWith('quando-me-aposentar') || slug.startsWith('pensao-por-morte') || slug.startsWith('auxilio-') || slug.startsWith('bpc-') || slug.startsWith('salario-maternidade') || slug.startsWith('revisao-da-vida')) return 'aposentadoria-geral'
  // CLT geral / benefícios / jornada
  if (slug.startsWith('clt-') || slug.startsWith('direitos-clt') || slug.startsWith('horas-extras') || slug.startsWith('hora-extra') || slug.startsWith('banco-de-horas') || slug.startsWith('adicional-') || slug.startsWith('vale-') || slug.startsWith('jornada-') || slug.startsWith('licenca-') || slug.startsWith('plano-') || slug.startsWith('seguro-') || slug.startsWith('previdencia-') || slug.startsWith('salario-familia') || slug.startsWith('salario-liquido')) return 'clt-geral'
  return 'guia-geral'
}

export function extrairSalarioDoSlug(slug: string): number {
  const m = slug.match(/(\d+)$/)
  return m ? parseInt(m[1], 10) : 3000
}

export function extrairAnosDoSlug(slug: string): number {
  const m = slug.match(/(\d+)-anos?/)
  return m ? parseInt(m[1], 10) : 5
}
