// slugs.ts — Todos os slugs da seção de Nutrição
// Total: 300+ slugs para SSG

// ─── Calorias por Alimento (80 slugs) ───────────────────────────────────────

export const SLUGS_CALORIAS_ALIMENTO: string[] = [
  'calorias-arroz',
  'calorias-feijao',
  'calorias-frango',
  'calorias-carne-bovina',
  'calorias-ovo',
  'calorias-banana',
  'calorias-maca',
  'calorias-batata-doce',
  'calorias-pao-frances',
  'calorias-leite',
  'calorias-queijo',
  'calorias-iogurte',
  'calorias-aveia',
  'calorias-granola',
  'calorias-chocolate',
  'calorias-pizza',
  'calorias-hamburguer',
  'calorias-batata-frita',
  'calorias-refrigerante',
  'calorias-suco-laranja',
  'calorias-cerveja',
  'calorias-vinho',
  'calorias-whey-protein',
  'calorias-pasta-amendoim',
  'calorias-azeite',
  'calorias-manteiga',
  'calorias-margarina',
  'calorias-abacate',
  'calorias-castanha',
  'calorias-amendoim',
  'calorias-salmao',
  'calorias-atum',
  'calorias-camarao',
  'calorias-tapioca',
  'calorias-cuscuz',
  'calorias-macarrao',
  'calorias-batata-inglesa',
  'calorias-mandioca',
  'calorias-inhame',
  'calorias-brocolis',
  'calorias-espinafre',
  'calorias-cenoura',
  'calorias-beterraba',
  'calorias-tomate',
  'calorias-alface',
  'calorias-pao-integral',
  'calorias-torrada',
  'calorias-biscoito',
  'calorias-sorvete',
  'calorias-bolo',
  'calorias-acai',
  'calorias-pitaya',
  'calorias-morango',
  'calorias-uva',
  'calorias-laranja',
  'calorias-mamao',
  'calorias-melancia',
  'calorias-abacaxi',
  'calorias-manga',
  'calorias-coco',
  'calorias-pipoca',
  'calorias-chips',
  'calorias-nuggets',
  'calorias-salsicha',
  'calorias-presunto',
  'calorias-mortadela',
  'calorias-queijo-mussarela',
  'calorias-requeijao',
  'calorias-creme-de-leite',
  'calorias-achocolatado',
  'calorias-cafe-com-leite',
  'calorias-chia',
  'calorias-linhaça',
  'calorias-proteina-vegetal',
  'calorias-tofu',
  'calorias-lentilha',
  'calorias-grao-de-bico',
  'calorias-arroz-integral',
]

// ─── Cálculo por Peso e Objetivo (40 slugs) ─────────────────────────────────

export const SLUGS_CALCULO_CALORICO: string[] = [
  'quantas-calorias-por-dia',
  'caloria-para-emagrecer',
  'caloria-para-ganhar-massa',
  'caloria-para-manter-peso',
  'deficit-calorico-como-calcular',
  'superavit-calorico',
  'taxa-metabolismo-basal',
  'gasto-energetico-diario',
  'calorias-por-kg-peso',
  'quantas-calorias-mulher',
  'quantas-calorias-homem',
  'quantas-calorias-gestante',
  'quantas-calorias-amamentando',
  'quantas-calorias-crianca',
  'quantas-calorias-adolescente',
  'quantas-calorias-idoso',
  'calorias-atleta',
  'calorias-sedentario',
  'macros-emagrecimento',
  'macros-hipertrofia',
  'macros-cutting',
  'macros-bulking',
  'proteina-por-kg',
  'proteina-diaria-recomendada',
  'carboidrato-por-dia',
  'gordura-diaria-recomendada',
  'fibra-diaria-recomendada',
  'agua-por-dia-recomendada',
  'vitaminas-essenciais',
  'minerais-essenciais',
  'calorias-cafe-da-manha',
  'calorias-almoco',
  'calorias-jantar',
  'calorias-lanche',
  'refeicoes-por-dia',
  'intervalo-entre-refeicoes',
  'calorias-por-faixa-etaria',
  'calorias-gravidez-trimestre',
  'necessidade-calorica-diaria',
  'calculo-calorico-personalizado',
]

// ─── Dietas e Protocolos (50 slugs) ─────────────────────────────────────────

export const SLUGS_DIETAS: string[] = [
  'dieta-lowcarb-2026',
  'dieta-cetogenica-como-funciona',
  'dieta-mediterranea',
  'jejum-intermitente-16-8',
  'jejum-intermitente-24h',
  'jejum-intermitente-5-2',
  'dieta-vegana-proteina',
  'dieta-vegetariana-2026',
  'dieta-paleo',
  'dieta-dash',
  'dieta-anti-inflamatoria',
  'dieta-para-diabetes',
  'dieta-para-hipertensao',
  'dieta-para-colesterol-alto',
  'dieta-para-tireoide',
  'dieta-para-intestino',
  'dieta-para-pre-menopausa',
  'reeducacao-alimentar',
  'como-montar-dieta',
  'contagem-de-macros',
  'iifym-dieta-flexivel',
  'deficit-500-calorias-resultado',
  'quanto-tempo-emagrecer-10kg',
  'quanto-tempo-emagrecer-20kg',
  'plato-dieta-como-superar',
  'efeito-sanfona-como-evitar',
  'perder-barriga-como',
  'perder-gordura-localizada',
  'ganhar-massa-magra-dieta',
  'dieta-cutting-bodybuilding',
  'dieta-bulking-limpo',
  'pre-treino-alimentacao',
  'pos-treino-alimentacao',
  'janela-anabolica-mito-ou-real',
  'suplementacao-para-emagrecer',
  'creatina-como-usar',
  'whey-protein-como-usar',
  'bcaa-vale-a-pena',
  'glutamina-vale-a-pena',
  'omega3-beneficios',
  'vitamina-d-deficiencia',
  'magnesio-para-que-serve',
  'zinco-imunidade',
  'ferro-anemia',
  'colageno-hidrolisado-beneficios',
  'probiotico-para-que-serve',
  'prebiotico-alimentos',
  'cacau-beneficios',
  'curcuma-beneficios',
  'gengibre-beneficios',
]

// ─── Emagrecimento e Peso (50 slugs) ────────────────────────────────────────

export const SLUGS_EMAGRECIMENTO: string[] = [
  'imc-como-calcular',
  'imc-ideal-adulto',
  'imc-por-idade',
  'imc-crianca',
  'imc-adolescente',
  'peso-ideal-por-altura',
  'peso-ideal-mulher',
  'peso-ideal-homem',
  'obesidade-como-tratar',
  'sobrepeso-como-emagrecer',
  'emagrecer-sem-academia',
  'emagrecer-com-caminhada',
  'emagrecer-rapido-como',
  'remedio-para-emagrecer-2026',
  'ozempic-funciona-mesmo',
  'qsymia-brasil',
  'orlistat-2026',
  'sibutramina-proibida',
  'bariatrica-quando-indicada',
  'bariatrica-sleeve-vs-bypass',
  'bariatrica-custo-2026',
  'procedimentos-esteticos-gordura',
  'criolipolise-resultado',
  'lpg-estetica-resultado',
  'drenagem-linfatica-emagrecer',
  'celulite-como-tratar',
  'flacidez-apos-emagrecimento',
  'pele-apos-bariatrica',
  'plastica-pos-bariatrica',
  'abdominoplastia-indicacao',
  'cirurgia-plastica-sus',
  'como-manter-peso-perdido',
  'recuperacao-peso-pos-dieta',
  'comportamento-alimentar',
  'compulsao-alimentar',
  'ansiedade-e-comida',
  'alimentacao-emocional',
  'mindful-eating',
  'ortorexia-o-que-e',
  'anorexia-sintomas',
  'bulimia-sintomas',
  'transtorno-alimentar-tratamento',
  'gordura-visceral-como-reduzir',
  'gordura-corporal-percentual-saudavel',
  'balanca-de-bioimpedancia',
  'dexa-exame-composicao-corporal',
  'nutri-funcional',
  'nutricao-comportamental',
  'set-point-teoria',
  'metabolismo-adaptativo',
]

// ─── Exercício e Metabolismo (30 slugs) ─────────────────────────────────────

export const SLUGS_EXERCICIO: string[] = [
  'calorias-gastas-caminhada',
  'calorias-gastas-corrida',
  'calorias-gastas-ciclismo',
  'calorias-gastas-natacao',
  'calorias-gastas-musculacao',
  'exercicio-aerobico-vs-anaerobico',
  'hiit-como-funciona',
  'metabolismo-lento-como-acelerar',
  'treino-jejum-vale-a-pena',
  'cardio-antes-ou-depois-musculacao',
  'frequencia-cardiaca-ideal-treino',
  'vo2-maximo-como-melhorar',
  'sedentarismo-riscos-saude',
  'movimento-diario-recomendado',
  '10000-passos-por-dia-beneficios',
  'pilates-calorias-gasto',
  'yoga-calorias-gasto',
  'funcional-treino-2026',
  'cross-training-beneficios',
  'periodizacao-treino',
  'overtraining-sintomas',
  'descanso-treino-importancia',
  'sono-e-emagrecimento',
  'cortisol-gordura-abdominal',
  'estresse-engorda',
  'hormonios-emagrecimento',
  'insulina-gordura',
  'ghrelina-fome',
  'leptina-saciedade',
  'serotonina-alimentacao',
]

// ─── Slugs adicionais de nutrição geral (50 slugs) ──────────────────────────

export const SLUGS_NUTRICAO_GERAL: string[] = [
  'rotulagem-nutricional-como-ler',
  'ultra-processados-riscos',
  'aditivos-alimentares-seguros',
  'agrotoxicos-nos-alimentos',
  'alimentos-organicos-vale-a-pena',
  'alimentos-funcionais',
  'superalimentos-mito-ou-real',
  'antioxidantes-o-que-sao',
  'inflamacao-cronica-alimentacao',
  'gut-health-microbioma',
  'fermentados-saude-intestinal',
  'kefir-beneficios',
  'kombucha-beneficios',
  'jejum-limpo-vs-sujo',
  'comer-de-noite-engorda',
  'carboidrato-engorda',
  'gordura-satura-faz-mal',
  'colesterol-alimentacao',
  'acucar-x-adocante',
  'adocante-artificial-faz-mal',
  'proteina-em-excesso-faz-mal',
  'suplemento-de-vitaminas-necessario',
  'cafeina-beneficios-riscos',
  'alcool-e-dieta',
  'comer-de-4-em-4-horas-necessario',
  'cafe-da-manha-mais-importante',
  'dieta-low-fodmap',
  'intolerancia-lactose-dieta',
  'doenca-celiaca-dieta',
  'sindrome-intestino-irritavel-dieta',
  'refluxo-alimentacao',
  'gastrite-o-que-comer',
  'constipacao-alimentos',
  'diarreia-o-que-comer',
  'hipertensao-sal',
  'diabetes-tipo-2-alimentacao',
  'colesterol-alto-dieta',
  'anemia-ferropriv-alimentacao',
  'osteoporose-calcio-dieta',
  'tireoide-iodo-dieta',
  'tpm-alimentacao',
  'menopausa-alimentacao',
  'gestacao-alimentacao',
  'amamentacao-o-que-comer',
  'crianca-alimentacao-saudavel',
  'idoso-necessidades-nutricionais',
  'atleta-necessidades-nutricionais',
  'vegetariano-proteinas-completas',
  'vegano-b12-suplementacao',
  'alimentacao-sustentavel',
]

// ─── Array consolidado ───────────────────────────────────────────────────────

export const SLUGS_NUTRICAO: string[] = [
  ...SLUGS_CALORIAS_ALIMENTO,
  ...SLUGS_CALCULO_CALORICO,
  ...SLUGS_DIETAS,
  ...SLUGS_EMAGRECIMENTO,
  ...SLUGS_EXERCICIO,
  ...SLUGS_NUTRICAO_GERAL,
]

// ─── Funções de classificação de tipo de slug ────────────────────────────────

export type TipoSlugNutricao =
  | 'caloria-alimento'
  | 'calculo-calorico'
  | 'dieta'
  | 'emagrecimento'
  | 'exercicio'
  | 'nutricao-geral'

export function getTipoSlugNutricao(slug: string): TipoSlugNutricao {
  if (SLUGS_CALORIAS_ALIMENTO.includes(slug)) return 'caloria-alimento'
  if (SLUGS_CALCULO_CALORICO.includes(slug)) return 'calculo-calorico'
  if (SLUGS_DIETAS.includes(slug)) return 'dieta'
  if (SLUGS_EMAGRECIMENTO.includes(slug)) return 'emagrecimento'
  if (SLUGS_EXERCICIO.includes(slug)) return 'exercicio'
  return 'nutricao-geral'
}

/**
 * Extrai o slug do alimento de um slug do tipo "calorias-[alimento]"
 */
export function getAlimentoSlugDeCaloria(slug: string): string {
  return slug.replace(/^calorias-/, '')
}
