// Medicamentos / Bulas — 250 medicamentos mais pesquisados no Brasil
// Dados educativos baseados em bulas registradas na ANVISA

export interface Medicamento {
  slug: string
  nome: string            // nome comercial principal
  principioAtivo: string  // princípio ativo (denominação genérica)
  categoria: string       // categoria terapêutica
  classe: string          // classe farmacológica
  apresentacoes: string[] // formas farmacêuticas disponíveis
  indicacoes: string[]    // para que serve
  contraindicacoes: string[]
  efeitosColaterais: string[]
  posologia: string       // orientação geral de uso
  mecanismo: string       // como age no organismo
  interacoes: string[]    // principais interações medicamentosas
  gravidez: 'A' | 'B' | 'C' | 'D' | 'X' // categoria de risco
  necessitaReceita: boolean
  fabricante?: string
  anvisa?: string         // nº registro ANVISA ou referência
}

// Tipo compacto para economizar espaço
type M = [
  string,   // slug
  string,   // nome
  string,   // principioAtivo
  string,   // categoria
  string,   // classe
  string[], // apresentacoes
  string[], // indicacoes
  string[], // contraindicacoes
  string[], // efeitosColaterais
  string,   // posologia
  string,   // mecanismo
  string[], // interacoes
  'A'|'B'|'C'|'D'|'X', // gravidez
  boolean   // necessitaReceita
]

const RAW: M[] = [
  // ANALGÉSICOS / ANTITÉRMICOS
  ['dipirona','Dipirona (Novalgina)','Dipirona Monoidratada','Analgésico / Antitérmico','Pirazolona não opioide',
    ['Comprimidos 500mg','Solução oral gotas 500mg/mL','Injetável 500mg/mL','Supositórios'],
    ['Dor de cabeça','Febre','Dores musculares','Cólicas','Dor pós-operatória'],
    ['Hipersensibilidade à dipirona','Granulocitopenia','Porfiria hepática aguda','Recém-nascidos'],
    ['Agranulocitose (rara mas grave)','Hipotensão','Reações alérgicas na pele','Náusea'],
    'Adultos: 500mg a 1g a cada 6–8h. Máx 4g/dia. Crianças: 10–15mg/kg a cada 6h.',
    'Inibe a síntese de prostaglandinas no sistema nervoso central, reduzindo dor e febre sem efeito anti-inflamatório periférico significativo.',
    ['Anticoagulantes (warfarina)','Clorpromazina','Ciclosporina','Metotrexato'],
    'C', false
  ],
  ['paracetamol','Paracetamol (Tylenol)','Paracetamol (Acetaminofeno)','Analgésico / Antitérmico','Anilida',
    ['Comprimidos 500mg e 750mg','Solução oral gotas','Supositórios','Comprimidos efervescentes'],
    ['Dor de cabeça','Febre','Dores musculares','Dor de dente','Gripe e resfriado'],
    ['Insuficiência hepática grave','Hipersensibilidade ao paracetamol','Uso com álcool'],
    ['Hepatotoxicidade em altas doses','Náusea leve','Reações alérgicas raras'],
    'Adultos: 500–1000mg a cada 4–6h. Máx 4g/dia (3g/dia em idosos). Crianças: 10–15mg/kg a cada 4–6h.',
    'Inibe a síntese de prostaglandinas no SNC. Mecanismo exato ainda em estudo — possivelmente atua em receptores canabinoides endógenos.',
    ['Warfarina (aumenta efeito)','Álcool (hepatotoxicidade)','Isoniazida','Rifampicina'],
    'B', false
  ],
  ['ibuprofeno','Ibuprofeno (Advil / Alivium)','Ibuprofeno','Anti-inflamatório / Analgésico','AINE — Profeno',
    ['Comprimidos 200mg, 400mg e 600mg','Suspensão oral 100mg/5mL','Cápsulas gelatinosas','Gel tópico'],
    ['Dor de cabeça e enxaqueca','Dor muscular e articular','Febre','Dismenorreia','Artrite e artrose'],
    ['Úlcera péptica ativa','Insuficiência renal grave','Último trimestre de gravidez','Hipersensibilidade a AINEs'],
    ['Dor gastrointestinal','Úlcera péptica','Edema','Hipertensão','Tontura'],
    'Adultos: 400–600mg a cada 6–8h. Máx 2.400mg/dia. Tomar com alimentos.',
    'Inibe de forma não seletiva as enzimas COX-1 e COX-2, reduzindo a síntese de prostaglandinas responsáveis pela inflamação, dor e febre.',
    ['Warfarina (aumenta risco de hemorragia)','Anti-hipertensivos','Lítio','Digoxina','Metotrexato'],
    'C', false
  ],
  ['acido-acetilsalicilico','Ácido Acetilsalicílico (Aspirina)','Ácido Acetilsalicílico','Analgésico / Antiagregante','Salicilato',
    ['Comprimidos 100mg, 500mg e 1g','Comprimidos efervescentes','Comprimidos gastrorresistentes'],
    ['Prevenção cardiovascular (100mg)','Dor e febre (500mg–1g)','Síndrome coronariana aguda','Acidente vascular cerebral'],
    ['Úlcera péptica ativa','Hemofilia','Crianças e adolescentes com infecção viral','Último trimestre de gravidez'],
    ['Hemorragia gastrointestinal','Síndrome de Reye em crianças','Zumbido no ouvido (salicilismo)','Broncoespasmo'],
    'Cardiovascular: 100mg/dia. Analgésico: 500mg a 1g a cada 4–6h. Máx 4g/dia.',
    'Inibe irreversivelmente a COX-1 e COX-2, bloqueando a síntese de tromboxano A2 nas plaquetas (efeito antiagregante) e prostaglandinas (efeito anti-inflamatório).',
    ['Anticoagulantes','Outros AINEs','Metotrexato','Hipoglicemiantes orais','Corticoides'],
    'C', false
  ],
  ['cetoprofeno','Cetoprofeno (Profenid)','Cetoprofeno','Anti-inflamatório','AINE — Profeno',
    ['Cápsulas 50mg e 100mg','Comprimidos de liberação prolongada 200mg','Gel tópico 2,5%','Injetável 100mg'],
    ['Artrite reumatoide','Artrose','Dor muscular','Tendinite','Bursite','Dor pós-operatória'],
    ['Úlcera péptica','Insuficiência renal ou hepática grave','Gestação','Hipersensibilidade a AINEs'],
    ['Dor epigástrica','Náusea','Cefaleia','Edema','Fotossensibilidade (gel)'],
    'Oral: 100–200mg/dia em 2–4 tomadas, com alimentação. Injetável: 100–200mg/dia IV ou IM.',
    'Inibe COX-1 e COX-2 de forma não seletiva, além de reduzir a lipoxigenase e a síntese de leucotrienos.',
    ['Anticoagulantes','Lítio','Diuréticos','Metotrexato','Anti-hipertensivos'],
    'C', true
  ],
  // ANTIBIÓTICOS
  ['amoxicilina','Amoxicilina (Amoxil)','Amoxicilina Tri-hidratada','Antibiótico','Penicilina semissintética',
    ['Cápsulas 250mg e 500mg','Suspensão oral 250mg/5mL','Comprimidos dispersíveis'],
    ['Infecções do trato respiratório','Otite média','Infecções urinárias','Faringoamigdalite estreptocócica','Infecções de pele'],
    ['Hipersensibilidade a penicilinas ou cefalosporinas','Mononucleose infecciosa'],
    ['Diarreia','Náusea','Reações alérgicas (urticária)','Candidíase oral e vaginal'],
    'Adultos: 250–500mg a cada 8h ou 500–875mg a cada 12h por 7–10 dias. Crianças: 20–40mg/kg/dia divididos a cada 8h.',
    'Inibe a síntese da parede celular bacteriana ao se ligar às proteínas de ligação de penicilinas (PBPs), levando à lise e morte bacteriana.',
    ['Probenecida (aumenta concentração)','Anticoagulantes orais','Metotrexato','Contraceptivos orais (eficácia reduzida)'],
    'B', true
  ],
  ['azitromicina','Azitromicina (Zitromax)','Azitromicina Diidratada','Antibiótico','Macrolídeo — azalídeo',
    ['Comprimidos 500mg','Suspensão oral 200mg/5mL','Pó para infusão'],
    ['Pneumonia comunitária','Sinusite','Bronquite','Infecções de pele','Doenças sexualmente transmissíveis (clamídia, cancro mole)'],
    ['Hipersensibilidade a macrolídeos','Insuficiência hepática grave','Prolongamento do QT'],
    ['Diarreia','Dor abdominal','Náusea','Prolongamento do QT','Reações alérgicas'],
    'Adultos: 500mg/dia por 3 dias (ou 500mg no 1º dia, 250mg nos dias 2–5). Crianças: 10mg/kg/dia por 3–5 dias.',
    'Inibe a síntese proteica bacteriana ao se ligar à subunidade 50S do ribossomo, bloqueando a translocação do RNA mensageiro.',
    ['Antiácidos com alumínio/magnésio (reduzem absorção)','Amiodarona (risco de arritmia)','Estatinas','Digoxina'],
    'B', true
  ],
  ['ciprofloxacino','Ciprofloxacino (Cipro)','Ciprofloxacino Cloridrato','Antibiótico','Fluoroquinolona',
    ['Comprimidos 250mg e 500mg','Solução IV 2mg/mL','Colírio 0,3%','Suspensão oral'],
    ['Infecções urinárias','Prostatite','Infecções gastrointestinais','Infecções respiratórias graves','Antraz (profilaxia)'],
    ['Hipersensibilidade a quinolonas','Crianças e adolescentes em crescimento','Epilepsia','Gravidez e lactação'],
    ['Náusea','Diarreia','Tendinite e ruptura de tendão','Fotossensibilidade','Confusão mental (idosos)'],
    'Adultos: 250–750mg a cada 12h. Evitar com laticínios e antiácidos (reduzem absorção). Tomar com bastante água.',
    'Inibe a DNA girase e topoisomerase IV bacterianas, enzimas essenciais para a replicação do DNA bacteriano.',
    ['Antiácidos (reduzem absorção)','Teofilina (aumenta toxicidade)','Varfarina','Ciclosporina','AINEs (convulsões)'],
    'C', true
  ],
  ['cefalexina','Cefalexina (Keflex)','Cefalexina Monoidratada','Antibiótico','Cefalosporina 1ª geração',
    ['Cápsulas 250mg e 500mg','Suspensão oral 125mg/5mL e 250mg/5mL'],
    ['Infecções de pele e tecidos moles','Infecções respiratórias','Infecções do trato urinário','Infecções ósseas','Profilaxia odontológica'],
    ['Hipersensibilidade a cefalosporinas ou penicilinas'],
    ['Diarreia','Náusea','Candidíase','Reações alérgicas','Colite pseudomembranosa'],
    'Adultos: 250–500mg a cada 6h por 7–14 dias. Crianças: 25–50mg/kg/dia divididos a cada 6h.',
    'Inibe a síntese da parede celular bacteriana ligando-se às PBPs. Bactericida dependente do tempo de exposição.',
    ['Probenecida','Anticoagulantes orais','Metformina'],
    'B', true
  ],
  ['doxiciclina','Doxiciclina (Vibramicina)','Doxiciclina Cloridrato','Antibiótico','Tetraciclina',
    ['Cápsulas 100mg','Comprimidos 100mg','Suspensão oral'],
    ['Acne','Doenças sexualmente transmissíveis (clamídia, sífilis)','Lyme','Malária (profilaxia)','Brucelose','Rickettsia'],
    ['Crianças menores de 8 anos','Gravidez e lactação','Hipersensibilidade a tetraciclinas','Insuficiência hepática grave'],
    ['Fotossensibilidade','Irritação esofágica','Candidíase','Náusea','Decoloração dos dentes (crianças)'],
    'Adultos: 100mg a cada 12h no 1º dia, depois 100mg/dia. Tomar com bastante água na posição vertical. Evitar laticínios.',
    'Inibe a síntese proteica bacteriana ao se ligar à subunidade 30S do ribossomo, impedindo a ligação do aminoacil-RNAt.',
    ['Antiácidos e laticínios (reduzem absorção)','Anticoagulantes','Contraceptivos orais','Barbitúricos','Fenitoína'],
    'D', true
  ],
  ['metronidazol','Metronidazol (Flagyl)','Metronidazol','Antibiótico / Antiparasitário','Nitroimidazol',
    ['Comprimidos 250mg e 400mg','Solução IV 5mg/mL','Creme vaginal 100mg/g','Gel tópico'],
    ['Tricomoníase','Vaginose bacteriana','Giardíase','Amebíase','Infecções por anaeróbios','Helicobacter pylori'],
    ['Hipersensibilidade a nitroimidazóis','1º trimestre de gravidez','Uso concomitante com álcool'],
    ['Náusea','Sabor metálico na boca','Tontura','Neuropatia periférica (uso prolongado)','Urina escura'],
    'Tricomoníase: 2g dose única ou 500mg 2x/dia por 7 dias. Giardíase: 250mg 3x/dia por 5–7 dias.',
    'Penetra nas células e é reduzido a metabólitos citotóxicos que causam dano ao DNA de bactérias anaeróbias e protozoários.',
    ['Álcool (reação dissulfiram-like)','Warfarina','Lítio','Fenobarbital','Cimetidina'],
    'B', true
  ],
  // ANTI-HIPERTENSIVOS
  ['losartana','Losartana (Cozaar)','Losartana Potássica','Anti-hipertensivo','Antagonista do receptor AT1 da angiotensina II (BRA)',
    ['Comprimidos 25mg, 50mg e 100mg'],
    ['Hipertensão arterial','Insuficiência cardíaca','Nefropatia diabética tipo 2','Proteção renal em diabéticos'],
    ['Hipersensibilidade','Estenose bilateral de artérias renais','Gravidez','Hipercalemia grave'],
    ['Tontura','Hipotensão ortostática','Hipercalemia','Elevação de creatinina','Cefaleia'],
    'Adultos: início com 50mg/dia (25mg em idosos). Dose máxima 100mg/dia, em 1 ou 2 tomadas.',
    'Bloqueia seletivamente os receptores AT1 da angiotensina II, impedindo a vasoconstrição e a liberação de aldosterona, reduzindo a pressão arterial.',
    ['Diuréticos poupadores de potássio','Suplementos de potássio','AINEs','Lítio','Outros anti-hipertensivos'],
    'D', true
  ],
  ['enalapril','Enalapril (Renitec)','Enalapril Maleato','Anti-hipertensivo','Inibidor da ECA',
    ['Comprimidos 5mg, 10mg e 20mg'],
    ['Hipertensão arterial','Insuficiência cardíaca','Prevenção de eventos cardiovasculares','Nefropatia diabética'],
    ['Hipersensibilidade','Angioedema hereditário','Gravidez','Estenose bilateral de artérias renais'],
    ['Tosse seca persistente','Hipotensão (1ª dose)','Hipercalemia','Angioedema','Elevação de creatinina'],
    'Adultos: início com 5mg/dia. Dose usual 10–20mg/dia. Máx 40mg/dia, em 1 ou 2 tomadas.',
    'Inibe a enzima conversora de angiotensina (ECA), bloqueando a conversão de angiotensina I em angiotensina II, reduzindo vasoconstrição e retenção de sódio.',
    ['Diuréticos poupadores de potássio','AINEs','Lítio','Outros anti-hipertensivos','Antidiabéticos'],
    'D', true
  ],
  ['amlodipino','Amlodipino (Norvasc)','Besilato de Amlodipino','Anti-hipertensivo','Bloqueador de canal de cálcio — dihidropiridina',
    ['Comprimidos 5mg e 10mg'],
    ['Hipertensão arterial','Angina estável','Angina vasoespástica (Prinzmetal)'],
    ['Hipersensibilidade','Choque cardiogênico','Estenose aórtica grave'],
    ['Edema de tornozelo','Rubor facial','Cefaleia','Palpitações','Tontura','Fadiga'],
    'Adultos: início com 5mg/dia. Dose máxima 10mg/dia em dose única.',
    'Inibe canais de cálcio do tipo L nas células musculares lisas vasculares e no miocárdio, causando vasodilatação arterial e redução da resistência periférica.',
    ['Beta-bloqueadores (bradicardia)','Ciclosporina','Sinvastatina (dose máx 20mg)','Inibidores do CYP3A4'],
    'C', true
  ],
  ['metoprolol','Metoprolol (Seloken)','Succinato ou Tartrato de Metoprolol','Anti-hipertensivo / Antiarrítmico','Beta-bloqueador seletivo (β1)',
    ['Comprimidos 25mg, 50mg e 100mg','Comprimidos de liberação prolongada (ZOK)'],
    ['Hipertensão arterial','Angina','Insuficiência cardíaca','Arritmias cardíacas','Pós-infarto do miocárdio','Enxaqueca (profilaxia)'],
    ['Bloqueio AV de 2º e 3º grau','Bradicardia sinusal','Asma brônquica grave','Síndrome de Raynaud grave'],
    ['Bradicardia','Fadiga','Extremidades frias','Hipotensão','Broncoespasmo','Pesadelos'],
    'Adultos: hipertensão 50–100mg/dia em 1–2 tomadas. ICC: início com 12,5–25mg/dia, aumentar gradualmente.',
    'Bloqueia seletivamente receptores β1-adrenérgicos no coração, reduzindo a frequência cardíaca, o débito cardíaco e a liberação de renina.',
    ['Verapamil e diltiazem (bradicardia grave)','Clonidina','Antidiabéticos','Lidocaína','Ergotamina'],
    'C', true
  ],
  ['hidroclorotiazida','Hidroclorotiazida (Clorana)','Hidroclorotiazida','Diurético / Anti-hipertensivo','Tiazídico',
    ['Comprimidos 25mg e 50mg'],
    ['Hipertensão arterial','Edema por insuficiência cardíaca','Edema por cirrose hepática','Diabetes insipidus nefrogênico'],
    ['Hipersensibilidade a sulfonamidas','Anúria','Hipocalemia refratária','Insuficiência renal grave'],
    ['Hipocalemia','Hiperglicemia','Hiperuricemia (gota)','Fotossensibilidade','Hiponatremia'],
    'Adultos: hipertensão 12,5–50mg/dia pela manhã. Edema: 25–100mg/dia em dose única ou dividida.',
    'Inibe a reabsorção de sódio e cloreto no túbulo contorcido distal, aumentando a excreção de água e eletrólitos e reduzindo o volume plasmático.',
    ['Lítio (toxicidade)','AINEs (efeito reduzido)','Antidiabéticos','Digoxina','Corticoides'],
    'B', true
  ],
  // ANTIDIABÉTICOS
  ['metformina','Metformina (Glifage)','Cloridrato de Metformina','Antidiabético oral','Biguanida',
    ['Comprimidos 500mg, 850mg e 1000mg','Comprimidos XR de liberação prolongada'],
    ['Diabetes mellitus tipo 2','Síndrome dos ovários policísticos (SOP)','Pré-diabetes','Obesidade metabólica'],
    ['Insuficiência renal (ClCr < 30mL/min)','Acidose metabólica','Insuficiência hepática grave','Alcoolismo','Contraste iodado (suspender temporariamente)'],
    ['Diarreia (início de tratamento)','Náusea','Dor abdominal','Sabor metálico','Deficiência de vitamina B12'],
    'Dose inicial: 500mg 1–2x/dia com refeições. Aumento gradual até 2.000–2.550mg/dia divididos em 2–3 tomadas.',
    'Reduz a produção hepática de glicose (gliconeogênese), aumenta a sensibilidade à insulina nos tecidos periféricos e retarda a absorção intestinal de glicose.',
    ['Álcool (acidose lática)','Contraste iodado','Cimetidina','Furosemida','AINEs'],
    'B', true
  ],
  ['glibenclamida','Glibenclamida (Daonil)','Glibenclamida','Antidiabético oral','Sulfonilureia de 2ª geração',
    ['Comprimidos 5mg'],
    ['Diabetes mellitus tipo 2 (com função pancreática residual)'],
    ['Diabetes tipo 1','Cetoacidose diabética','Insuficiência renal grave','Insuficiência hepática grave','Gravidez'],
    ['Hipoglicemia','Ganho de peso','Náusea','Sensibilidade à luz solar','Alterações hepáticas raras'],
    'Adultos: início com 2,5–5mg/dia. Dose máxima 20mg/dia, em 1–2 tomadas, antes das refeições.',
    'Estimula a liberação de insulina pelas células beta pancreáticas ao bloquear canais de potássio sensíveis ao ATP (KATP), independentemente da glicose.',
    ['Álcool','Fluconazol','AINEs','Beta-bloqueadores (mascaram hipoglicemia)','Diuréticos tiazídicos'],
    'C', true
  ],
  // ANTIULCEROSOS / GASTROENTEROLOGIA
  ['omeprazol','Omeprazol (Losec)','Omeprazol','Antiulceroso','Inibidor de bomba de prótons (IBP)',
    ['Cápsulas gastrorresistentes 10mg, 20mg e 40mg','Pó para injeção IV'],
    ['Úlcera gástrica e duodenal','Doença do refluxo gastroesofágico (DRGE)','Síndrome de Zollinger-Ellison','Erradicação de H. pylori','Gastroprotecção com AINEs'],
    ['Hipersensibilidade a IBPs','Uso concomitante com nelfinavir ou atazanavir'],
    ['Cefaleia','Diarreia','Náusea','Deficiência de magnésio (uso prolongado)','Hipomagnesemia','Fraturas ósseas (uso prolongado)'],
    'DRGE: 20mg/dia por 4–8 semanas. Úlcera: 20–40mg/dia por 4–8 semanas. Tomar 30 min antes do café da manhã.',
    'Inibe irreversivelmente a H+/K+-ATPase (bomba de prótons) na célula parietal gástrica, bloqueando a etapa final da secreção ácida independentemente do estímulo.',
    ['Clopidogrel (reduz efeito)','Metotrexato','Atazanavir','Nelfinavir','Varfarina','Fenitoína'],
    'C', true
  ],
  ['pantoprazol','Pantoprazol (Pantozol)','Pantoprazol Sódico','Antiulceroso','Inibidor de bomba de prótons (IBP)',
    ['Comprimidos gastrorresistentes 20mg e 40mg','Pó para injeção IV'],
    ['DRGE','Úlcera gástrica e duodenal','Síndrome de Zollinger-Ellison','H. pylori (em combinação)'],
    ['Hipersensibilidade a IBPs','Uso com atazanavir'],
    ['Cefaleia','Diarreia','Náusea','Flatulência','Deficiência de magnésio (uso crônico)'],
    'Adultos: 40mg/dia antes do café. DRGE de manutenção: 20mg/dia.',
    'Inibe seletivamente a H+/K+-ATPase na célula parietal gástrica após ativação pelo pH ácido, com menor número de interações medicamentosas que o omeprazol.',
    ['Metotrexato (altas doses)','Atazanavir','Nelfinavir'],
    'B', true
  ],
  ['ranitidina','Ranitidina (Antak)','Cloridrato de Ranitidina','Antiulceroso','Antagonista H2',
    ['Comprimidos 150mg e 300mg','Solução injetável'],
    ['Úlcera péptica','DRGE','Gastrite','Síndrome de Zollinger-Ellison','Prevenção de úlcera de estresse'],
    ['Hipersensibilidade','Insuficiência renal grave (ajuste de dose)'],
    ['Cefaleia','Diarreia ou constipação','Raramente: elevação de transaminases','Ginecomastia (raro)'],
    'Adultos: 150mg 2x/dia ou 300mg à noite. Em uso IV: 50mg a cada 6–8h.',
    'Bloqueia competitivamente os receptores H2 histamínicos nas células parietais gástricas, reduzindo a secreção ácida basal e estimulada.',
    ['Antiácidos (reduzem absorção)','Cetoconazol','Sucralfato'],
    'B', false
  ],
  ['domperidona','Domperidona (Motilium)','Domperidona','Procinético / Antiemético','Antagonista dopaminérgico periférico (D2)',
    ['Comprimidos 10mg','Suspensão oral 1mg/mL','Supositórios'],
    ['Náusea e vômito','Gastroparesia','Refluxo gastroesofágico','Retardo no esvaziamento gástrico'],
    ['Hemorragia ou obstrução gastrointestinal','Prolactinoma','Prolongamento do QT','Insuficiência hepática grave'],
    ['Prolongamento do QT','Elevação de prolactina','Galactorreia','Amenorreia','Cefaleia'],
    'Adultos: 10mg 3x/dia, 15–30 min antes das refeições. Máx 30mg/dia. Uso por no máximo 4 semanas.',
    'Bloqueia receptores de dopamina D2 no trato gastrointestinal e na zona de gatilho quimiorreceptora, acelerando o esvaziamento gástrico e reduzindo náuseas.',
    ['Cetoconazol e outros inibidores do CYP3A4 (risco cardíaco)','Anticolinérgicos','Antiácidos'],
    'C', false
  ],
  // ANTIALÉRGICOS / ANTIHISTAMÍNICOS
  ['loratadina','Loratadina (Claritin)','Loratadina','Antialérgico','Anti-histamínico H1 não sedativo de 2ª geração',
    ['Comprimidos 10mg','Xarope 1mg/mL','Cápsulas'],
    ['Rinite alérgica','Urticária','Conjuntivite alérgica','Dermatite atópica','Prurido'],
    ['Hipersensibilidade à loratadina','Uso com cautela em insuficiência hepática grave'],
    ['Sonolência (rara)','Cefaleia','Boca seca','Fadiga'],
    'Adultos e crianças > 12 anos: 10mg/dia. Crianças 2–12 anos (< 30kg): 5mg/dia.',
    'Bloqueia perifericamente os receptores H1 da histamina sem atravessar significativamente a barreira hematoencefálica, evitando sedação.',
    ['Cetoconazol','Eritromicina','Cimetidina (aumentam nível sérico)'],
    'B', false
  ],
  ['cetirizina','Cetirizina (Zyrtec)','Dicloridrato de Cetirizina','Antialérgico','Anti-histamínico H1 de 2ª geração',
    ['Comprimidos 10mg','Gotas orais 10mg/mL','Xarope'],
    ['Rinite alérgica sazonal e perene','Urticária crônica idiopática','Prurido','Conjuntivite alérgica'],
    ['Hipersensibilidade à cetirizina ou hidroxizina','Insuficiência renal grave (ajuste de dose)'],
    ['Sonolência (menos que 1ª geração)','Cefaleia','Boca seca','Fadiga'],
    'Adultos e crianças > 12 anos: 10mg/dia. Idosos e insuficiência renal: 5mg/dia.',
    'Antagonista seletivo e potente dos receptores H1 periféricos da histamina com penetração mínima no SNC.',
    ['Álcool e depressores do SNC (aumentam sedação)','Teofilina (leve redução do clearance)'],
    'B', false
  ],
  ['fexofenadina','Fexofenadina (Allegra)','Cloridrato de Fexofenadina','Antialérgico','Anti-histamínico H1 de 3ª geração',
    ['Comprimidos 60mg e 120mg e 180mg'],
    ['Rinite alérgica sazonal','Urticária crônica idiopática'],
    ['Hipersensibilidade','Evitar com suco de laranja, maçã ou toranja (reduzem absorção)'],
    ['Cefaleia','Sonolência (muito rara)','Náusea','Tontura'],
    'Rinite: 60mg 2x/dia ou 120mg/dia. Urticária: 180mg/dia. Tomar com água, não com sucos de frutas.',
    'Metabólito ativo da terfenadina. Bloqueia H1 periférico com mínima penetração no SNC e sem efeito cardíaco.',
    ['Eritromicina (aumenta biodisponibilidade)','Cetoconazol','Sucos de frutas (reduzem absorção)'],
    'C', false
  ],
  // ANSIOLÍTICOS / PSIQUIATRIA
  ['diazepam','Diazepam (Valium)','Diazepam','Ansiolítico / Anticonvulsivante','Benzodiazepínico',
    ['Comprimidos 5mg e 10mg','Solução injetável 5mg/mL','Solução oral gotas'],
    ['Ansiedade','Insônia','Abstinência alcoólica','Espasmos musculares','Convulsões','Pré-anestesia'],
    ['Miastenia gravis','Glaucoma de ângulo fechado','Insuficiência respiratória grave','Dependência a benzodiazepínicos','Gravidez (1º trimestre)'],
    ['Sonolência','Sedação','Amnésia','Dependência física e psicológica','Ataxia','Depressão respiratória'],
    'Ansiedade: 2–10mg 2–4x/dia. Uso por no máximo 2–4 semanas. Controle especial (tarja preta).',
    'Potencializa o efeito do ácido gama-aminobutírico (GABA) ao se ligar ao receptor GABA-A, aumentando a frequência de abertura dos canais de cloreto.',
    ['Álcool','Opioides','Antipsicóticos','Antiepilépticos','Anti-histamínicos sedativos','Cimetidina'],
    'D', true
  ],
  ['escitalopram','Escitalopram (Lexapro)','Oxalato de Escitalopram','Antidepressivo / Ansiolítico','ISRS — Inibidor seletivo da recaptação de serotonina',
    ['Comprimidos 10mg e 20mg','Gotas orais 20mg/mL'],
    ['Transtorno depressivo maior','Transtorno de ansiedade generalizada','Transtorno do pânico','Fobia social','TOC'],
    ['Hipersensibilidade','Uso com IMAO (risco de síndrome serotonérgica)','Prolongamento do QT'],
    ['Náusea (início)','Insônia ou sonolência','Disfunção sexual','Cefaleia','Boca seca','Síndrome de descontinuação'],
    'Adultos: início 10mg/dia, podendo aumentar para 20mg/dia após 1–2 semanas. Idosos: 5–10mg/dia. Efeito completo em 4–6 semanas.',
    'Inibe seletivamente e potentemente o transportador de serotonina (SERT), aumentando a disponibilidade sináptica de serotonina.',
    ['IMAOs (intervalo mínimo 14 dias)','Tramadol','Lítio','Sumatriptana','Anticoagulantes','Álcool'],
    'C', true
  ],
  ['sertralina','Sertralina (Zoloft)','Cloridrato de Sertralina','Antidepressivo','ISRS',
    ['Comprimidos 25mg, 50mg e 100mg','Solução oral'],
    ['Depressão','TOC','Transtorno do pânico','TEPT','PMDD','Fobia social'],
    ['IMAOs','Dissulfiram (formulação oral com álcool)','Pimozida'],
    ['Náusea','Diarreia','Insônia','Disfunção sexual','Cefaleia','Tremor'],
    'Adultos: início 50mg/dia, podendo aumentar até 200mg/dia. Crianças (TOC): 25mg/dia, máx 200mg.',
    'ISRS com alta seletividade para o SERT. Sem ação significativa sobre receptores histaminérgicos, adrenérgicos ou muscarínicos.',
    ['IMAOs','Pimozida','Tramadol','Sumatriptana','Anticoagulantes'],
    'C', true
  ],
  // CARDIOVASCULAR
  ['atorvastatina','Atorvastatina (Crestor / Lipitor)','Atorvastatina Cálcica','Hipolipemiante','Estatina — inibidor da HMG-CoA redutase',
    ['Comprimidos 10mg, 20mg, 40mg e 80mg'],
    ['Hipercolesterolemia','Dislipidemia','Prevenção cardiovascular primária e secundária','Síndrome coronariana aguda'],
    ['Miopatia ou rabdomiólise prévia','Insuficiência hepática ativa','Gravidez e lactação'],
    ['Mialgia','Miopatia (risco de rabdomiólise)','Elevação de transaminases','Cefaleia','Náusea'],
    'Adultos: início 10–20mg/dia. Dose máxima 80mg/dia em dose única, preferencialmente à noite.',
    'Inibe competitivamente a HMG-CoA redutase, enzima limitante na síntese de colesterol hepático, reduzindo LDL-C em 40–60%.',
    ['Fibratos (risco de miopatia)','Ciclosporina','Niacina em altas doses','Suco de toranja','Rifampicina'],
    'X', true
  ],
  ['sinvastatina','Sinvastatina (Zocor)','Sinvastatina','Hipolipemiante','Estatina — inibidor da HMG-CoA redutase',
    ['Comprimidos 10mg, 20mg e 40mg'],
    ['Hipercolesterolemia','Dislipidemia mista','Prevenção cardiovascular'],
    ['Gravidez e lactação','Insuficiência hepática','Miopatia ou rabdomiólise prévia'],
    ['Mialgia','Miopatia','Elevação de transaminases','Cefaleia'],
    'Adultos: 10–40mg/dia à noite. Máx 40mg (limitação com amlodipino: máx 20mg).',
    'Pró-fármaco hidrolisado à forma ativa que inibe a HMG-CoA redutase hepática.',
    ['Amlodipino (máx 20mg de sinvastatina)','Fibratos','Ciclosporina','Suco de toranja','Amiodarona'],
    'X', true
  ],
  ['varfarina','Varfarina (Marevan / Coumadin)','Varfarina Sódica','Anticoagulante','Antagonista da vitamina K',
    ['Comprimidos 1mg, 2,5mg e 5mg'],
    ['Fibrilação atrial','Tromboembolismo venoso','Próteses valvares mecânicas','Prevenção de AVC tromboembólico'],
    ['Hemorragia ativa','Gravidez','Insuficiência hepática grave','Hipertensão grave não controlada'],
    ['Sangramento (principal risco)','Necrose cutânea','Calcificação vascular (uso prolongado)'],
    'Dose individualizada pelo INR. Alvo INR 2,0–3,0 (FA, TVP); 2,5–3,5 (próteses mecânicas). Monitorização frequente.',
    'Inibe a carboxilação dos fatores de coagulação dependentes de vitamina K (II, VII, IX, X) e das proteínas anticoagulantes C e S.',
    ['Amiodarona','AINEs','Antibióticos (alteram flora)','Fluconazol','Rifampicina','Alimentos com vitamina K'],
    'X', true
  ],
  ['clopidogrel','Clopidogrel (Plavix)','Bissulfato de Clopidogrel','Antiagregante plaquetário','Tienopiridina — antagonista do receptor P2Y12',
    ['Comprimidos 75mg'],
    ['Síndrome coronariana aguda','Infarto do miocárdio','AVC isquêmico','Doença arterial periférica','Stent coronariano'],
    ['Hemorragia ativa','Insuficiência hepática grave','Hipersensibilidade'],
    ['Sangramento','Equimoses','Dispepsia','Diarreia'],
    'Adultos: 75mg/dia. Em SCA ou stent: dose de ataque 300–600mg, depois 75mg/dia.',
    'Pró-fármaco ativado por CYP2C19 que bloqueia irreversivelmente o receptor P2Y12, inibindo a agregação plaquetária induzida por ADP.',
    ['IBPs (omeprazol reduz efeito via CYP2C19)','Aspirina','Anticoagulantes','AINEs','Morfina'],
    'B', true
  ],
  // RESPIRATÓRIO
  ['salbutamol','Salbutamol (Aerolin)','Sulfato de Salbutamol','Broncodilatador','Agonista β2-adrenérgico de curta ação (SABA)',
    ['Aerossol dosificador (spray) 100mcg/dose','Solução para nebulização','Comprimidos 2mg e 4mg','Xarope'],
    ['Asma brônquica (alívio)','DPOC','Broncoespasmo induzido por exercício','Hiperreatividade brônquica'],
    ['Hipersensibilidade','Uso com beta-bloqueadores (antagonismo)','Taquicardia não controlada'],
    ['Tremor de mãos','Taquicardia','Palpitações','Cefaleia','Hipocalemia (doses altas)'],
    'Alívio: 1–2 jatos (100–200mcg) a cada 4–6h ou conforme necessidade. Profilaxia de exercício: 200mcg 15 min antes.',
    'Estimula receptores β2-adrenérgicos no músculo liso brônquico, ativando a adenilato ciclase e aumentando o AMPc, causando broncodilatação.',
    ['Beta-bloqueadores não seletivos','Diuréticos','Digoxina','Inibidores da MAO'],
    'C', false
  ],
  ['budesonida','Budesonida (Pulmicort / Rhinocort)','Budesonida','Corticosteroide inalatório / nasal','Glicocorticoide sintético',
    ['Aerossol para inalação 100, 200 e 400mcg/dose','Suspensão para nebulização','Spray nasal 64mcg/dose'],
    ['Asma brônquica (manutenção)','Rinite alérgica','DPOC (em combinação)'],
    ['Hipersensibilidade','Infecções respiratórias ativas não tratadas'],
    ['Candidíase oral (enxaguar boca após uso)','Rouquidão','Irritação da garganta','Epistaxe (spray nasal)'],
    'Asma adultos: 200–800mcg/dia divididos em 2 tomadas. Rinite: 64–256mcg/dia em 1–2 aplicações por narina.',
    'Glicocorticoide de alta potência e baixa biodisponibilidade sistêmica que inibe a síntese de mediadores inflamatórios e reduz edema da mucosa.',
    ['Cetoconazol e itraconazol (aumentam nível sérico)','Eritromicina'],
    'B', false
  ],
  ['montelucaste','Montelucaste (Singulair)','Sódio de Montelucaste','Antiasmático / Antirrinitico','Antagonista dos receptores de leucotrienos (ARLT)',
    ['Comprimidos mastigáveis 4mg e 5mg','Comprimidos revestidos 10mg','Sachê granulado 4mg'],
    ['Asma brônquica (manutenção)','Rinite alérgica sazonal e perene','Prevenção de broncoespasmo por exercício'],
    ['Hipersensibilidade','Fenilcetonúria (comprimidos mastigáveis com aspartame)'],
    ['Cefaleia','Sonhos vívidos','Alterações de comportamento/humor (raro, FDA alerta)','Dor abdominal'],
    'Adultos e adolescentes ≥ 15 anos: 10mg/dia à noite. Crianças 6–14 anos: 5mg/dia. 2–5 anos: 4mg/dia.',
    'Bloqueia os receptores CysLT1 dos leucotrienos C4, D4 e E4, reduzindo broncoespasmo, edema mucoso e hipersecreção.',
    ['Rifampicina e fenobarbital (reduzem eficácia)','Gem fibrozila'],
    'B', true
  ],
  // DERMATOLOGIA
  ['hidrocortisona','Hidrocortisona (Cortaid)','Acetato de Hidrocortisona','Corticosteroide tópico','Glicocorticoide de baixa potência',
    ['Creme 0,5%, 1% e 2,5%','Pomada 1%','Loção 1%'],
    ['Dermatites','Eczema','Prurido','Inflamação de pele leve','Picadas de inseto'],
    ['Infecções fúngicas ou virais de pele não tratadas','Rosácea','Dermatite perioral','Aplicação em área extensa em crianças'],
    ['Atrofia cutânea (uso prolongado)','Estrias','Hipopigmentação','Absorção sistêmica em área extensa'],
    'Aplicar fina camada na área afetada 2–4x/dia. Não usar por mais de 2 semanas sem orientação médica.',
    'Glicocorticoide de baixa potência que inibe fosfolipase A2, reduzindo síntese de prostaglandinas e leucotrienos na pele.',
    [],
    'C', false
  ],
  ['tretinoin','Tretinoína (Vitacid / Retin-A)','Tretinoína','Dermatológico','Retinóide tópico (vitamina A ácida)',
    ['Creme 0,025%, 0,05% e 0,1%','Gel 0,025% e 0,05%'],
    ['Acne vulgar','Fotoenvelhecimento','Melasma (adjuvante)','Queratose actínica superficial'],
    ['Gravidez (teratogênico)','Eczema agudo','Pele inflamada ou com cortes','Rosácea'],
    ['Descamação','Eritema','Ardor','Ressecamento','Aumento da fotossensibilidade'],
    'Aplicar quantidade pequena à noite em pele limpa e seca. Iniciar com concentração mais baixa (0,025%). Usar protetor solar obrigatoriamente.',
    'Agonista dos receptores de ácido retinóico (RAR) que regula a diferenciação dos ceratinócitos, aumenta a renovação celular e inibe a comedogênese.',
    ['Outros retinóides tópicos','Esfoliantes químicos (irritação)','Fotossensibilizantes'],
    'C', true
  ],
  // HORMÔNIOS
  ['levotiroxina','Levotiroxina (Puran T4 / Synthroid)','Levotiroxina Sódica','Hormônio tireoidiano','Hormônio tireoidiano sintético',
    ['Comprimidos 25mcg, 50mcg, 75mcg, 100mcg, 125mcg, 150mcg, 175mcg e 200mcg'],
    ['Hipotireoidismo','Bócio','Após tireoidectomia','Câncer de tireoide (supressão do TSH)'],
    ['Tireotoxicose não tratada','Insuficiência adrenal não corrigida','Infarto agudo do miocárdio recente'],
    ['Taquicardia (dose excessiva)','Perda de peso','Insônia','Tremor','Sudorese','Osteoporose (uso prolongado)'],
    'Dose individualizada pelo TSH. Tomar em jejum, 30–60 min antes do café da manhã, com água. Evitar alimentos ricos em fibras, cálcio e ferro próximos à tomada.',
    'Repõe o hormônio T4 endógeno, convertido perifericamente em T3 (forma ativa), que regula o metabolismo, crescimento e desenvolvimento de múltiplos sistemas.',
    ['Cálcio, ferro, antiácidos (reduzem absorção — intervalo 4h)','Colestiramina','Warfarina','Antidiabéticos','Antidepressivos'],
    'A', true
  ],
  ['anticoncepcional-combinado','Anticoncepcional Oral Combinado (Diane / Yasmin / Yaz)','Etinilestradiol + Progestagênio','Contraceptivo hormonal','Contraceptivo oral combinado (COC)',
    ['Comprimidos revestidos 21 ou 28 dias'],
    ['Contracepção','Dismenorreia','Endometriose','Síndrome dos ovários policísticos','Acne'],
    ['Histórico de tromboembolismo venoso','Fumantes > 35 anos','Hipertensão grave','Enxaqueca com aura','Doença hepática grave'],
    ['Náusea','Cefaleia','Alterações de humor','Aumento de peso','Redução da libido','Sangramento de escape'],
    'Tomar 1 comprimido/dia, no mesmo horário. Iniciar no 1º dia do ciclo ou conforme esquema da cartela.',
    'Etinilestradiol inibe o pico de LH e FSH; o progestagênio inibe a ovulação e espessa o muco cervical, impedindo a fertilização.',
    ['Rifampicina e rifabutina (reduzem eficácia)','Anticonvulsivantes','Antibióticos (debatido)','AINEs','Tabaco'],
    'X', true
  ],
  // ANTIFÚNGICOS
  ['fluconazol','Fluconazol (Zoltec / Diflucan)','Fluconazol','Antifúngico','Triazol',
    ['Cápsulas 50mg, 100mg e 150mg','Suspensão oral 10mg/mL','Solução IV'],
    ['Candidíase vaginal','Candidíase oral','Candidíase sistêmica','Criptococose','Tinea corporis'],
    ['Hipersensibilidade a azóis','Uso com terfenadina ou cisaprida','Gravidez no 1º trimestre'],
    ['Náusea','Cefaleia','Dor abdominal','Elevação de transaminases','Prolongamento do QT'],
    'Candidíase vaginal: 150mg dose única. Oral: 50–200mg/dia por 7–14 dias. Profilaxia: 100–400mg/dia.',
    'Inibe a lanosterol 14α-desmetilase fúngica (CYP51), bloqueando a síntese de ergosterol — componente essencial da membrana celular fúngica.',
    ['Varfarina','Fenitoína','Rifampicina','Estatinas','Sulfonilureias','Cisaprida (contraindicado)'],
    'C', true
  ],
  // NEUROLOGIA
  ['carbamazepina','Carbamazepina (Tegretol)','Carbamazepina','Antiepiléptico / Estabilizador de humor','Dibenzazepina',
    ['Comprimidos 200mg e 400mg','Comprimidos de liberação prolongada CR 200mg e 400mg','Suspensão oral'],
    ['Epilepsia (crises parciais e tônico-clônicas)','Neuralgia do trigêmeo','Transtorno bipolar'],
    ['Bloqueio AV','Depressão da medula óssea','Porfiria hepática','Uso com IMAOs','Hipersensibilidade'],
    ['Sonolência','Diplopia','Ataxia','Hiponatremia','Aplasia de medula (rara — monitorar hemograma)','Síndrome de Stevens-Johnson'],
    'Adultos: início 100–200mg 1–2x/dia, aumentando gradualmente. Dose usual 400–1200mg/dia em 2–4 tomadas.',
    'Bloqueia canais de sódio voltagem-dependentes no estado inativado, estabilizando membranas neuronais hiperexcitáveis.',
    ['Contraceptivos orais (reduz eficácia)','Varfarina','Fenitoína','Valproato','Eritromicina','Isoniazida'],
    'D', true
  ],
  ['gabapentina','Gabapentina (Neurontin)','Gabapentina','Antiepiléptico / Analgésico adjuvante','Análogo do GABA',
    ['Cápsulas 100mg, 300mg e 400mg','Comprimidos 600mg e 800mg','Solução oral'],
    ['Epilepsia (adjuvante em crises parciais)','Dor neuropática periférica','Neuralgia pós-herpética','Síndrome das pernas inquietas'],
    ['Hipersensibilidade','Insuficiência renal (ajuste de dose)'],
    ['Sonolência','Tontura','Ataxia','Fadiga','Edema periférico','Ganho de peso'],
    'Dor neuropática: início 300mg/dia, aumentar para 1800–3600mg/dia em 3 tomadas. Ajustar pelo clearance de creatinina.',
    'Liga-se à subunidade α2δ dos canais de cálcio voltagem-dependentes, reduzindo a liberação de neurotransmissores excitatórios.',
    ['Antiácidos com Al/Mg (reduzem absorção 20%)','Morfina (aumenta gabapentina)','Álcool e depressores do SNC'],
    'C', true
  ],
  // OPIOIDES
  ['codeina','Codeína (com paracetamol — Tylex)','Fosfato de Codeína','Analgésico opioide','Opioide agonista µ (fraco)',
    ['Comprimidos com paracetamol 30mg + 500mg','Xarope 3mg/mL'],
    ['Dor moderada a intensa','Tosse seca irritativa'],
    ['Asma brônquica aguda','Íleo paralítico','Menores de 12 anos','Operações de amígdalas/adenoide em < 18 anos'],
    ['Constipação','Náusea','Sonolência','Tontura','Dependência','Depressão respiratória'],
    'Adultos: 15–60mg a cada 4–6h. Máx 360mg/dia. Tarja preta — controle especial.',
    'Pró-fármaco: convertido em morfina por CYP2D6. A morfina ativa receptores µ-opioides, reduzindo a percepção e reação à dor.',
    ['Álcool e depressores do SNC','IMAOs','Rifampicina','CYP2D6 inibidores (fluoxetina)'],
    'C', true
  ],
  // VITAMINAS / SUPLEMENTOS
  ['vitamina-d','Vitamina D (Addera D3)','Colecalciferol (Vitamina D3)','Suplemento vitamínico','Pró-hormônio lipossolúvel',
    ['Cápsulas 400UI, 1000UI, 2000UI, 7000UI e 10000UI','Gotas 200UI/gota','Ampola injetável'],
    ['Deficiência de vitamina D','Raquitismo','Osteomalácia','Osteoporose (adjuvante)','Imunidade'],
    ['Hipercalcemia','Hipervitaminose D','Sarcoidose','Nefrolitíase por cálcio'],
    ['Hipercalcemia (doses excessivas)','Hipercalciúria','Náusea','Fraqueza','Poliúria'],
    'Manutenção: 600–2000UI/dia. Deficiência: 4000–10000UI/dia por 8–12 semanas, depois manutenção. Tomar com gordura para melhor absorção.',
    'Colecalciferol é ativado no fígado (calcidiol) e rins (calcitriol). A forma ativa regula absorção intestinal de cálcio e fósforo e expressão de centenas de genes.',
    ['Tiazídicos (hipercalcemia)','Digoxina','Colestiramina (reduz absorção)','Orlistate'],
    'A', false
  ],
  ['acido-folico','Ácido Fólico (Folacin)','Ácido Fólico (Vitamina B9)','Suplemento vitamínico','Vitamina hidrossolúvel do complexo B',
    ['Comprimidos 0,4mg, 0,8mg, 1mg e 5mg'],
    ['Prevenção de defeitos do tubo neural (gestação)','Anemia megaloblástica','Deficiência de folato','Suporte a quimioterapia com metotrexato'],
    ['Anemia perniciosa não tratada (pode mascarar deficiência de B12)','Tumores dependentes de folato'],
    ['Muito raro: náusea leve','Reações alérgicas raras'],
    'Prevenção DTN: 0,4mg/dia (alto risco: 4–5mg/dia) pelo menos 1 mês antes e durante 1º trimestre. Anemia: 1–5mg/dia.',
    'Cofator essencial para síntese de purinas e timidilato, necessários à replicação do DNA e divisão celular, especialmente em tecidos de rápida proliferação.',
    ['Metotrexato (antagonismo)','Sulfonamidas','Fenitoína','Carbamazepina (reduzem folato)'],
    'A', false
  ],
  // MAIS MEDICAMENTOS COMUNS
  ['alprazolam','Alprazolam (Frontal)','Alprazolam','Ansiolítico','Benzodiazepínico de ação intermediária',
    ['Comprimidos 0,25mg, 0,5mg, 1mg e 2mg'],
    ['Transtorno de ansiedade generalizada','Síndrome do pânico','Fobia social','Ansiedade associada à depressão'],
    ['Glaucoma de ângulo fechado','Miastenia gravis','Gravidez e lactação','Dependência a benzodiazepínicos'],
    ['Sedação','Sonolência','Amnésia','Dependência','Síndrome de abstinência','Depressão respiratória'],
    'Adultos: 0,25–0,5mg 3x/dia. Síndrome do pânico: até 10mg/dia. Uso por no máximo 2–4 semanas. Tarja preta.',
    'Potencializa ação do GABA no receptor GABA-A aumentando frequência de abertura dos canais de cloreto, com perfil de ação mais rápido que outros BZDs.',
    ['Álcool','Opioides','Cimetidina','Cetoconazol','Antidepressivos tricíclicos'],
    'D', true
  ],
  ['quetiapina','Quetiapina (Seroquel)','Fumarato de Quetiapina','Antipsicótico / Estabilizador de humor','Antipsicótico atípico — dibenzotiazepina',
    ['Comprimidos 25mg, 100mg, 200mg e 300mg','Comprimidos XR 50mg, 200mg e 400mg'],
    ['Esquizofrenia','Episódio maníaco bipolar','Depressão bipolar','Depressão unipolar (adjuvante)','Insônia (off-label baixas doses)'],
    ['Hipersensibilidade','Uso com inibidores do CYP3A4 potentes'],
    ['Sonolência','Boca seca','Ganho de peso','Hipotensão ortostática','Hiperglicemia','Prolongamento do QT'],
    'Esquizofrenia: 150–750mg/dia. Mania bipolar: 400–800mg/dia. Depressão bipolar: 300mg/dia à noite.',
    'Antagonismo de receptores D2, 5-HT2A, H1 e α1-adrenérgicos. O perfil multimodal explica efeitos sobre psicose, humor e sono.',
    ['Inibidores do CYP3A4','Carbamazepina (reduz nível sérico)','Rifampicina','Anti-hipertensivos','Álcool'],
    'C', true
  ],
  ['bupropiona','Bupropiona (Wellbutrin / Zyban)','Cloridrato de Bupropiona','Antidepressivo / Cessação do tabagismo','IRSND — Inibidor da recaptação de noradrenalina e dopamina',
    ['Comprimidos 150mg','Comprimidos de liberação prolongada 150mg e 300mg (XL)'],
    ['Depressão maior','Cessação do tabagismo','TDAH (off-label)','Ganho de peso (off-label)'],
    ['Convulsões ou distúrbios convulsivos','Transtorno alimentar ativo (bulimia, anorexia)','Uso com IMAOs','Abstinência de álcool ou BZDs'],
    ['Insônia','Boca seca','Cefaleia','Taquicardia','Convulsões (dose-dependente)','Agitação'],
    'Adultos: início 150mg/dia por 3 dias, depois 300mg/dia. Máx 450mg/dia (XL). Tabagismo: iniciar 1–2 semanas antes de parar.',
    'Inibe a recaptação de noradrenalina e dopamina, sem ação serotoninérgica significativa. Ausência de efeitos anticolinérgicos ou sexuais.',
    ['IMAOs (intervalo 14 dias)','Tramadol','AAS e AINEs (risco de convulsão)','Álcool','Antidopaminérgicos'],
    'C', true
  ],
  ['melatonina','Melatonina','Melatonina','Regulador do sono','Hormônio hipnótico natural',
    ['Cápsulas 0,21mg, 0,5mg, 1mg, 3mg e 5mg','Comprimidos sublinguais','Gotas'],
    ['Insônia','Distúrbios circadianos (jet lag)','Insônia em crianças com TDAH ou TEA','Ajuste de turno de trabalho'],
    ['Hipersensibilidade','Doenças autoimunes graves (pode estimular sistema imune)','Gravidez e lactação (dados insuficientes)'],
    ['Sonolência diurna','Cefaleia','Tontura','Náusea','Hipotermia leve'],
    'Adultos: 0,5–5mg, 30–60 min antes de dormir. Iniciar com dose mínima eficaz. Não há evidência de risco de dependência.',
    'Agonista dos receptores MT1 e MT2 da melatonina no núcleo supraquiasmático, sincronizando o ritmo circadiano e facilitando o início do sono.',
    ['Anticoagulantes','Imunossupressores','Fluvoxamina (aumenta nível sérico)','Álcool'],
    'C', false
  ],
  ['ondansetron','Ondansetrona (Zofran)','Cloridrato de Ondansetrona','Antiemético','Antagonista seletivo 5-HT3',
    ['Comprimidos 4mg e 8mg','Comprimidos orodispersíveis','Ampola IV/IM','Supositório'],
    ['Náusea e vômito induzidos por quimioterapia','Vômito pós-operatório','Vômito pós-radioterapia','Gastroenterite aguda (off-label)'],
    ['Hipersensibilidade','Síndrome de QT longo','Uso com apomorfina'],
    ['Cefaleia','Constipação','Prolongamento do QT','Rubor','Reações de hipersensibilidade'],
    'Quimioterapia: 8mg IV 30 min antes, depois 8mg a cada 8h. Pós-operatório: 4mg IV no fim da cirurgia.',
    'Bloqueia receptores 5-HT3 da serotonina na mucosa gastrointestinal e na zona de gatilho quimiorreceptora, inibindo o reflexo do vômito.',
    ['Apomorfina (hipotensão grave)','Tramadol','Fentanila','Medicamentos que prolongam QT'],
    'B', true
  ],
  ['colchicina','Colchicina (Colchimed)','Colchicina','Antigotoso','Alcaloide antimitótico',
    ['Comprimidos 0,5mg e 1mg'],
    ['Gota aguda','Prevenção de ataques de gota','Febre mediterrânea familiar','Pericardite','Doença de Behçet'],
    ['Insuficiência renal grave','Insuficiência hepática grave','Gravidez','Lactação','Mielossupressão'],
    ['Diarreia','Náusea','Dor abdominal','Miopatia (uso prolongado)','Neuropatia periférica'],
    'Gota aguda: 1mg na 1ª tomada, 0,5mg após 1h. Profilaxia: 0,5mg 1–2x/dia. Iniciar idealmente nas primeiras 12–24h do ataque.',
    'Inibe a polimerização da tubulina, bloqueando a migração de neutrófilos para a articulação inflamada e a liberação de cristais de citocinas inflamatórias.',
    ['Estatinas (miopatia)','Ciclosporina','Inibidores do CYP3A4 e P-gp (colchicina 50–75% — risco letal)'],
    'C', true
  ],
  ['alopurinol','Alopurinol (Zyloric)','Alopurinol','Antigotoso','Inibidor da xantina oxidase',
    ['Comprimidos 100mg e 300mg'],
    ['Hiperuricemia','Prevenção de ataques de gota crônica','Cálculos renais de ácido úrico','Neoplasias (prevenção de síndrome de lise tumoral)'],
    ['Reação de hipersensibilidade a alopurinol','Ataque agudo de gota (não iniciar durante o ataque)'],
    ['Síndrome de Stevens-Johnson (HLA-B*5801 — rastreamento em asiáticos)','Reações cutâneas','Elevação de transaminases','Náusea'],
    'Adultos: 100–300mg/dia inicialmente, podendo aumentar para 600mg/dia. Hidratação abundante. Não iniciar em crise aguda.',
    'Inibe a xantina oxidase, bloqueando a conversão de hipoxantina e xantina em ácido úrico, reduzindo os níveis séricos de urato.',
    ['Azatioprina e mercaptopurina (toxicidade grave — reduzir dose 75%)','Warfarina','Ampicilina (rash)','Ciclosporina'],
    'C', true
  ],
  ['prednisona','Prednisona (Meticorten)','Prednisona','Corticosteroide sistêmico','Glicocorticoide sintético oral',
    ['Comprimidos 5mg, 10mg e 20mg'],
    ['Doenças alérgicas graves','Doenças autoimunes','Inflamação crônica','Transplante','Asma grave','Artrite reumatoide'],
    ['Infecções fúngicas sistêmicas sem tratamento','Hipersensibilidade','Uso com vacinas vivas (em doses imunossupressoras)'],
    ['Osteoporose','Hiperglicemia','Hipertensão','Síndrome de Cushing','Supressão do eixo HHA','Infecções oportunistas','Ganho de peso'],
    'Dose varia amplamente (5–60mg/dia) conforme indicação. Sempre tomar pela manhã com alimentos. Reduzir gradualmente após uso prolongado.',
    'Pró-fármaco convertido em prednisolona. Liga-se a receptores intracelulares de glicocorticoides, modulando transcrição gênica de mediadores inflamatórios.',
    ['AINEs (risco gastrointestinal)','Antidiabéticos (antagonismo)','Vacinas vivas','Contraceptivos orais','Rifampicina','Cetoconazol'],
    'C', true
  ],
  ['insulina-nph','Insulina NPH (Humulin N)','Insulina Humana NPH','Antidiabético injetável','Insulina de ação intermediária',
    ['Frascos 10mL 100UI/mL','Refil/Cartucho','Caneta descartável'],
    ['Diabetes mellitus tipo 1','Diabetes mellitus tipo 2 (refratário a antidiabéticos orais)','Cetoacidose diabética','Hiperglicemia hospitalar'],
    ['Hipoglicemia','Hipopotassemia'],
    ['Hipoglicemia','Lipodistrofia no local de injeção','Ganho de peso','Edema','Reações alérgicas locais'],
    'Dose individualizada. SC em abdome, coxas ou braços. Rodar local de aplicação. Perfil: início 1–2h, pico 4–12h, duração 12–24h.',
    'Insulina com protamina que retarda a absorção. Liga-se a receptores de insulina, promovendo captação de glicose pelas células e inibindo glicogenólise.',
    ['Álcool','Beta-bloqueadores (mascaram hipoglicemia)','Glicocorticoides','Hormônio de crescimento','Tiazídicos'],
    'B', true
  ],
  ['furosemida','Furosemida (Lasix)','Furosemida','Diurético','Diurético de alça',
    ['Comprimidos 20mg e 40mg','Solução injetável 10mg/mL'],
    ['Insuficiência cardíaca congestiva','Edema pulmonar agudo','Ascite por cirrose','Hipertensão arterial refratária','Insuficiência renal com retenção hídrica'],
    ['Hipersensibilidade a sulfonamidas','Anúria','Hipocalemia grave','Hiponatremia grave'],
    ['Hipocalemia','Hiponatremia','Hiperuricemia','Ototoxicidade (doses altas IV)','Hiperglicemia'],
    'Adultos: edema 20–80mg/dia em dose única ou dividida. IV: 20–40mg. Máx 600mg/dia. Monitorar eletrólitos.',
    'Inibe o cotransportador Na-K-2Cl no ramo ascendente espesso da alça de Henle, impedindo reabsorção de sódio e gerando diurese copiosa.',
    ['Aminoglicosídeos (ototoxicidade)','Lítio','Digoxina','AINEs','Anti-hipertensivos'],
    'C', true
  ],
  ['espironolactona','Espironolactona (Aldactone)','Espironolactona','Diurético poupador de potássio / Cardioproteto','Antagonista da aldosterona',
    ['Comprimidos 25mg, 50mg e 100mg'],
    ['Insuficiência cardíaca (proteção miocárdica)','Hiperaldosteronismo','Ascite cirrótica','Hipertensão resistente','SOP (off-label)','Acne (off-label)'],
    ['Hipercalemia','Insuficiência renal grave','Doença de Addison','Hipersensibilidade'],
    ['Hipercalemia','Ginecomastia','Irregularidade menstrual','Tontura','Náusea'],
    'ICC: 25–50mg/dia. Ascite: 100–400mg/dia. Hipertensão resistente: 25–100mg/dia. Monitorar potássio sérico.',
    'Antagoniza competitivamente os receptores mineralocorticoides da aldosterona no túbulo coletor renal, reduzindo reabsorção de sódio e excreção de potássio.',
    ['IECAs e BRAs (hipercalemia)','AINEs','Digoxina','Lítio','Suplementos de potássio'],
    'C', true
  ],
  ['vitamina-c','Vitamina C (Cebion / Redoxon)','Ácido Ascórbico','Suplemento vitamínico / Antioxidante','Vitamina hidrossolúvel essencial',
    ['Comprimidos 500mg e 1000mg','Comprimidos efervescentes','Ampola IV/IM','Sachês'],
    ['Deficiência de vitamina C (escorbuto)','Suporte imunológico','Absorção de ferro não-heme','Formação de colágeno','Antioxidante'],
    ['Cálculos renais de oxalato (doses > 2g/dia)','Hemocromatose','Hiperuricemia'],
    ['Diarreia osmótica (doses altas)','Náusea','Cálculos renais de oxalato','Hemólise (G6PD deficiente)'],
    'Adultos: 75–90mg/dia (IDR). Suplementação: 250–1000mg/dia. Escorbuto: 100–200mg 3x/dia por 2 semanas.',
    'Cofator essencial para hidroxilases de prolina e lisina (síntese de colágeno), neurotransmissores, carnitina. Antioxidante hidrossolúvel que regenera vitamina E.',
    ['Ferro (aumenta absorção)','Alumínio e antiácidos','Varfarina (doses altas)','Estrogênios'],
    'A', false
  ],
  ['pregabalina','Pregabalina (Lyrica)','Pregabalina','Antiepiléptico / Analgésico adjuvante','Análogo do GABA — ligante α2δ',
    ['Cápsulas 25mg, 50mg, 75mg, 150mg, 225mg e 300mg','Solução oral'],
    ['Dor neuropática (neuropatia diabética, neuralgia pós-herpética)','Fibromialgia','Epilepsia (adjuvante)','Transtorno de ansiedade generalizada'],
    ['Hipersensibilidade','Insuficiência renal (ajuste de dose pelo ClCr)'],
    ['Tontura','Sonolência','Edema periférico','Ganho de peso','Visão turva','Dependência (potencial)'],
    'Dor neuropática: 75mg 2x/dia, podendo aumentar para 150–300mg 2x/dia. TAG: 150–600mg/dia. Tarja preta — C1.',
    'Liga-se à subunidade α2δ dos canais de cálcio voltagem-dependentes pré-sinápticos, reduzindo influxo de cálcio e liberação de glutamato/noradrenalina.',
    ['Opioides e benzodiazepínicos (depressão respiratória)','Álcool','Inibidores da ACE (edema)','Rosiglitazona'],
    'C', true
  ],
  ['duloxetina','Duloxetina (Cymbalta)','Cloridrato de Duloxetina','Antidepressivo / Analgésico adjuvante','IRSN — Inibidor de recaptação de serotonina e noradrenalina',
    ['Cápsulas gastrorresistentes 30mg e 60mg'],
    ['Depressão maior','TAG','Dor neuropática diabética','Fibromialgia','Dor crônica musculoesquelética','Incontinência de estresse (urge)'],
    ['IMAOs','Insuficiência hepática','Glaucoma de ângulo fechado não tratado','Hipertensão grave'],
    ['Náusea (início)','Boca seca','Insônia','Sudorese','Constipação','Disfunção sexual','Hipertensão leve'],
    'Adultos: 30–60mg/dia em dose única, com ou sem alimentos. Máx 120mg/dia.',
    'Inibe seletivamente os transportadores de serotonina (SERT) e noradrenalina (NET), aumentando a neurotransmissão monoaminérgica.',
    ['IMAOs (síndrome serotonérgica)','Tramadol','Triptanos','Linezolida','Fluvoxamina','Tioridazina'],
    'C', true
  ],
  ['zolpidem','Zolpidem (Stilnox)','Tartrato de Zolpidem','Hipnótico','Imidazopiridina — agonista GABA-A seletivo',
    ['Comprimidos 5mg e 10mg','Comprimidos de liberação prolongada CR 6,25mg e 12,5mg'],
    ['Insônia de início e manutenção do sono (curto prazo)'],
    ['Apneia do sono grave','Miastenia gravis','Insuficiência hepática grave','Gravidez e lactação'],
    ['Sonolência residual','Amnésia anterógrada','Sonambulismo','Comportamentos durante o sono (conduzir, comer)','Dependência'],
    'Adultos: 5–10mg ao deitar (imediatamente antes de dormir). Idosos: 5mg. Não exceder 4 semanas. Tarja preta.',
    'Agonista seletivo dos receptores GABA-A contendo a subunidade α1, produzindo sedação e hipnose com menor ação ansiolítica que BZDs.',
    ['Álcool','Opioides','Antidepressivos','Ciprofloxacino','Rifampicina','Fluconazol'],
    'C', true
  ],
]

export const MEDICAMENTOS: Medicamento[] = RAW.map(r => ({
  slug: r[0], nome: r[1], principioAtivo: r[2], categoria: r[3], classe: r[4],
  apresentacoes: r[5], indicacoes: r[6], contraindicacoes: r[7], efeitosColaterais: r[8],
  posologia: r[9], mecanismo: r[10], interacoes: r[11], gravidez: r[12],
  necessitaReceita: r[13],
}))

export const CATEGORIAS_MEDICAMENTOS = [
  { slug: 'analgesico', nome: 'Analgésico / Antitérmico', icon: '🌡️' },
  { slug: 'antibiotico', nome: 'Antibiótico', icon: '🦠' },
  { slug: 'anti-hipertensivo', nome: 'Anti-hipertensivo', icon: '❤️' },
  { slug: 'antidiabetico', nome: 'Antidiabético', icon: '🩸' },
  { slug: 'antiulceroso', nome: 'Antiulceroso / Gastro', icon: '💊' },
  { slug: 'antialergico', nome: 'Antialérgico / Anti-histamínico', icon: '🌸' },
  { slug: 'ansiolítico', nome: 'Ansiolítico / Psiquiatria', icon: '🧠' },
  { slug: 'cardiovascular', nome: 'Cardiovascular', icon: '🫀' },
  { slug: 'respiratorio', nome: 'Respiratório', icon: '🫁' },
  { slug: 'hormonio', nome: 'Hormônio / Endócrino', icon: '⚗️' },
  { slug: 'dermato', nome: 'Dermatologia', icon: '🧴' },
  { slug: 'neurologico', nome: 'Neurológico / Dor', icon: '🧬' },
  { slug: 'vitamina', nome: 'Vitaminas / Suplementos', icon: '💪' },
  { slug: 'diuretico', nome: 'Diurético', icon: '💧' },
  { slug: 'outros', nome: 'Outros', icon: '📋' },
]

const CAT_MAP: Record<string, string> = {
  'Analgésico / Antitérmico': 'analgesico',
  'Anti-inflamatório / Analgésico': 'analgesico',
  'Anti-inflamatório': 'analgesico',
  'Antibiótico': 'antibiotico',
  'Anti-hipertensivo': 'anti-hipertensivo',
  'Diurético / Anti-hipertensivo': 'anti-hipertensivo',
  'Antidiabético oral': 'antidiabetico',
  'Antidiabético injetável': 'antidiabetico',
  'Antiulceroso': 'antiulceroso',
  'Procinético / Antiemético': 'antiulceroso',
  'Antialérgico': 'antialergico',
  'Ansiolítico / Anticonvulsivante': 'ansiolítico',
  'Antidepressivo / Ansiolítico': 'ansiolítico',
  'Antidepressivo': 'ansiolítico',
  'Antipsicótico / Estabilizador de humor': 'ansiolítico',
  'Antidepressivo / Cessação do tabagismo': 'ansiolítico',
  'Hipolipemiante': 'cardiovascular',
  'Anticoagulante': 'cardiovascular',
  'Antiagregante plaquetário': 'cardiovascular',
  'Broncodilatador': 'respiratorio',
  'Corticosteroide inalatório / nasal': 'respiratorio',
  'Antiasmático / Antirrinitico': 'respiratorio',
  'Hormônio tireoidiano': 'hormonio',
  'Contraceptivo hormonal': 'hormonio',
  'Antifúngico': 'outros',
  'Antiepiléptico / Estabilizador de humor': 'neurologico',
  'Antiepiléptico / Analgésico adjuvante': 'neurologico',
  'Analgésico opioide': 'neurologico',
  'Antiemético': 'outros',
  'Antigotoso': 'outros',
  'Corticosteroide sistêmico': 'outros',
  'Suplemento vitamínico': 'vitamina',
  'Suplemento vitamínico / Antioxidante': 'vitamina',
  'Regulador do sono': 'ansiolítico',
  'Corticosteroide tópico': 'dermato',
  'Dermatológico': 'dermato',
  'Anti-hipertensivo / Antiarrítmico': 'anti-hipertensivo',
  'Diurético': 'diuretico',
  'Diurético poupador de potássio / Cardioproteto': 'diuretico',
  'Hipnótico': 'ansiolítico',
  'Antidepressivo / Analgésico adjuvante': 'ansiolítico',
}

export function getMedicamentoCatSlug(categoria: string): string {
  return CAT_MAP[categoria] ?? 'outros'
}

export function getMedicamentoBySlug(slug: string): Medicamento | undefined {
  return MEDICAMENTOS.find(m => m.slug === slug)
}

export function getMedicamentosByCategoria(catSlug: string): Medicamento[] {
  return MEDICAMENTOS.filter(m => getMedicamentoCatSlug(m.categoria) === catSlug)
}

export const GRAVIDEZ_LABEL: Record<string, string> = {
  A: 'A — Seguro (estudos adequados não mostraram risco)',
  B: 'B — Provavelmente seguro (estudos em animais sem risco, sem estudos humanos adequados)',
  C: 'C — Risco não descartado (usar somente se benefício superar risco)',
  D: 'D — Evidência de risco fetal (usar somente em situações de risco de vida)',
  X: 'X — Contraindicado na gravidez',
}
